// AUTO-GENERATED by rlx-torch-import (flow style) — do not edit by hand.
#![allow(nonstandard_style, unused_imports, unused_mut, unused_variables, dead_code, clippy::all)]

use rlx_flow::{ModelFlow, FlowStage};
use rlx_flow::blocks::CustomStage;
use rlx_ir::HirGraphExt;
use rlx_ir::op::{Activation, MaskKind};

fn rlx_torch_fill(value: f64, dtype: rlx_ir::DType, numel: usize) -> Vec<u8> {
    let one: Vec<u8> = match dtype {
        rlx_ir::DType::F32 => (value as f32).to_le_bytes().to_vec(),
        rlx_ir::DType::F64 => value.to_le_bytes().to_vec(),
        rlx_ir::DType::I64 => (value as i64).to_le_bytes().to_vec(),
        rlx_ir::DType::I32 => (value as i32).to_le_bytes().to_vec(),
        _ => vec![],
    };
    let mut out = Vec::with_capacity(one.len() * numel);
    for _ in 0..numel { out.extend_from_slice(&one); }
    out
}

/// Build a `ModelFlow`; params are pulled from the `WeightSource` at build time.
pub fn build_flow() -> ModelFlow {
    ModelFlow::new("mlp")
        .input("x", rlx_ir::Shape::new(&[2, 4, 16], rlx_ir::DType::F32))
        .stage(FlowStage::Custom(CustomStage::new(|emit, _input| {
            let t_x = emit.flow_input("x")?.hir_id();
            let t_p_ln_weight = emit.load_param("ln.weight", false)?;
            let t_p_ln_bias = emit.load_param("ln.bias", false)?;
            let t_p_fc1_weight = emit.load_param("fc1.weight", false)?;
            let t_p_fc1_bias = emit.load_param("fc1.bias", false)?;
            let t_p_fc2_weight = emit.load_param("fc2.weight", false)?;
            let t_p_fc2_bias = emit.load_param("fc2.bias", false)?;
            let mut b = rlx_ir::hir::HirMut::new(emit.hir());
    // aten.layer_norm.default  (x[2, 4, 16], p_ln_weight[16], p_ln_bias[16]) -> [2, 4, 16] f32
    let t_layer_norm = b.ln(t_x, t_p_ln_weight, t_p_ln_bias, 0.00001f32);
    // aten.view.default  (layer_norm[2, 4, 16]) -> [8, 16] f32
    let t_view = b.reshape_(t_layer_norm, vec![8i64, 16i64]);
    // aten.permute.default  (p_fc1_weight[32, 16]) -> [16, 32] f32
    let t_permute = b.transpose_(t_p_fc1_weight, vec![1usize, 0usize]);
    let t_addmm__mm = b.mm(t_view, t_permute);
    // aten.addmm.default  (p_fc1_bias[32], view[8, 16], permute[16, 32]) -> [8, 32] f32
    let t_addmm = b.add(t_addmm__mm, t_p_fc1_bias);
    // aten.view.default  (addmm[8, 32]) -> [2, 4, 32] f32
    let t_view_1 = b.reshape_(t_addmm, vec![2i64, 4i64, 32i64]);
    // aten.gelu.default  (view_1[2, 4, 32]) -> [2, 4, 32] f32
    let s_t_gelu = b.shape(t_view_1).clone();
    let t_gelu = b.activation(Activation::Gelu, t_view_1, s_t_gelu);
    // aten.view.default  (gelu[2, 4, 32]) -> [8, 32] f32
    let t_view_2 = b.reshape_(t_gelu, vec![8i64, 32i64]);
    // aten.permute.default  (p_fc2_weight[16, 32]) -> [32, 16] f32
    let t_permute_1 = b.transpose_(t_p_fc2_weight, vec![1usize, 0usize]);
    let t_addmm_1__mm = b.mm(t_view_2, t_permute_1);
    // aten.addmm.default  (p_fc2_bias[16], view_2[8, 32], permute_1[32, 16]) -> [8, 16] f32
    let t_addmm_1 = b.add(t_addmm_1__mm, t_p_fc2_bias);
    // aten.view.default  (addmm_1[8, 16]) -> [2, 4, 16] f32
    let t_view_3 = b.reshape_(t_addmm_1, vec![2i64, 4i64, 16i64]);
            let out_shape = b.shape(t_view_3).clone();
            drop(b);
            Ok(Some(emit.wrap(t_view_3, out_shape)))
        })))
        .output("output")
}
