// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Emit the artifact set for a [`Model`]: `qnn_model.cpp`, `verify.py`, and
//! `run_qnn.sh`.
//!
//! Milestone 1: a single rank-2 matmul as one `MatMul` node with two runtime
//! activation inputs (`in0[M,K]`, `in1[K,N]`) and one output (`out[M,N]`). The
//! C++ is composed with the `qnn_wrapper_api` surface — the same shape the
//! `qnn-onnx-converter` emits — so it builds into a `.so` with
//! `qnn-model-lib-generator` and runs under `qnn-net-run`. Two runtime inputs
//! (rather than a baked-in static weight) keep the validation loop closeable
//! with stock tooling; static-weight `.bin` packing is a later milestone (see
//! the crate docs).

use std::path::Path;

use crate::cpp::Cpp;
use crate::model::{Layer, Model};

/// One emitted file: its relative path and its full contents.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Artifact {
    pub path: String,
    pub contents: String,
}

/// Build every artifact for `model` in memory (no filesystem I/O).
pub fn collect_artifacts(model: &Model) -> Result<Vec<Artifact>, String> {
    let layer = match model.layers.as_slice() {
        [single] => single,
        other => {
            return Err(format!(
                "rlx-qnn milestone 1 emits exactly one layer; model has {}",
                other.len()
            ));
        }
    };
    let Layer::MatMul { m, k, n, .. } = layer;
    let (m, k, n) = (*m, *k, *n);

    if m == 0 || k == 0 || n == 0 {
        return Err(format!(
            "MatMul dims must be non-zero; got M={m} K={k} N={n}"
        ));
    }

    Ok(vec![
        Artifact {
            path: "qnn_model.cpp".to_string(),
            contents: emit_qnn_model_cpp(m, k, n),
        },
        Artifact {
            path: "verify.py".to_string(),
            contents: emit_verify_py(m, k, n),
        },
        Artifact {
            path: "run_qnn.sh".to_string(),
            contents: emit_run_qnn_sh(),
        },
    ])
}

/// Emit all artifacts for `model` into `out_dir` (created if absent).
pub fn emit_model(model: &Model, out_dir: &Path) -> std::io::Result<()> {
    let artifacts = collect_artifacts(model).map_err(std::io::Error::other)?;
    std::fs::create_dir_all(out_dir)?;
    for a in &artifacts {
        std::fs::write(out_dir.join(&a.path), &a.contents)?;
    }
    Ok(())
}

/// `qnn_model.cpp` — compose the matmul graph with the `qnn_wrapper_api`
/// surface: two `APP_WRITE` input tensors, one `MatMul` node, one `APP_READ`
/// output. `qnn-model-lib-generator` turns this into `libqnn_model.so`.
fn emit_qnn_model_cpp(m: usize, k: usize, n: usize) -> String {
    let mut c = Cpp::new();
    c.banner("Generated by rlx-qnn — QNN AI Engine Direct model graph.");
    c.comment("out[M,N] = in0[M,K] * in1[K,N], row-major f32.");
    c.comment("Composed with the qnn_wrapper_api surface (the qnn-onnx-converter shape).");
    c.comment(
        "Build:  qnn-model-lib-generator -c qnn_model.cpp -t x86_64-linux-clang -o model_libs",
    );
    c.comment(
        "Run:    qnn-net-run --backend libQnnCpu.so --model libqnn_model.so ...  (see run_qnn.sh)",
    );
    c.blank();
    c.line("#include \"QnnModel.hpp\"");
    c.line("#include \"QnnOpDef.h\"");
    c.blank();
    c.comment("Have the backend validate each op node as it is added.");
    c.line("#define DO_GRAPH_NODE_VALIDATIONS 1");
    c.blank();
    c.line("using namespace qnn_wrapper_api;");
    c.blank();
    c.line("extern \"C\" {");
    c.blank();
    c.line("QNN_API");
    c.line("ModelError_t QnnModel_composeGraphs(Qnn_BackendHandle_t backendHandle,");
    c.line("                                    QNN_INTERFACE_VER_TYPE interface,");
    c.line("                                    Qnn_ContextHandle_t contextHandle,");
    c.line("                                    const GraphConfigInfo_t** graphsConfigInfo,");
    c.line("                                    const uint32_t numGraphsConfigInfo,");
    c.line("                                    GraphInfoPtr_t** graphsInfo,");
    c.line("                                    uint32_t* numGraphsInfo,");
    c.line("                                    bool debug,");
    c.line("                                    QnnLog_Callback_t logCallback,");
    c.line("                                    QnnLog_Level_t maxLogLevel) {");
    c.block(|c| {
        c.line("ModelError_t err = MODEL_NO_ERROR;");
        c.blank();
        c.line("QnnModel matmul_graph;");
        c.line("const QnnGraph_Config_t** graphConfigs = nullptr;");
        c.line("VALIDATE(getQnnGraphConfigFromInfo(\"matmul_graph\", graphsConfigInfo, numGraphsConfigInfo, graphConfigs), err);");
        c.line("VALIDATE(matmul_graph.initialize(backendHandle, interface, contextHandle, \"matmul_graph\", debug, DO_GRAPH_NODE_VALIDATIONS, graphConfigs), err);");
        c.blank();
        c.comment("graph input in0 [M, K]");
        c.line(&format!("uint32_t dimensions_in0[] = {{{m}, {k}}};"));
        c.tensor_v1(
            "VALIDATE(matmul_graph.addTensor(\"in0\", ",
            "in0",
            "QNN_TENSOR_TYPE_APP_WRITE",
            "dimensions_in0",
            "), err);",
        );
        c.blank();
        c.comment("graph input in1 [K, N]");
        c.line(&format!("uint32_t dimensions_in1[] = {{{k}, {n}}};"));
        c.tensor_v1(
            "VALIDATE(matmul_graph.addTensor(\"in1\", ",
            "in1",
            "QNN_TENSOR_TYPE_APP_WRITE",
            "dimensions_in1",
            "), err);",
        );
        c.blank();
        c.comment("MatMul node: out[M, N] = in0 * in1  (no transpose)");
        c.line("const char* inputs_matmul_0[] = {\"in0\", \"in1\"};");
        c.line(&format!("uint32_t dimensions_out[] = {{{m}, {n}}};"));
        c.line("Qnn_Tensor_t outputs_matmul_0[] = {");
        c.block(|c| {
            c.tensor_v1("", "out", "QNN_TENSOR_TYPE_APP_READ", "dimensions_out", "");
        });
        c.line("};");
        c.line("Qnn_Param_t params_matmul_0[] = {");
        c.block(|c| {
            c.line("{.paramType = QNN_PARAMTYPE_SCALAR, .name = QNN_OP_MAT_MUL_PARAM_TRANSPOSE_IN0,");
            c.line(" .scalarParam = {.dataType = QNN_DATATYPE_BOOL_8, {.bool8Value = 0}}},");
            c.line("{.paramType = QNN_PARAMTYPE_SCALAR, .name = QNN_OP_MAT_MUL_PARAM_TRANSPOSE_IN1,");
            c.line(" .scalarParam = {.dataType = QNN_DATATYPE_BOOL_8, {.bool8Value = 0}}}");
        });
        c.line("};");
        c.line("VALIDATE(matmul_graph.addNode(");
        c.block(|c| {
            c.line("QNN_OPCONFIG_VERSION_1,        // Op_Config version");
            c.line("\"matmul_0\",                    // node name");
            c.line("QNN_OP_PACKAGE_NAME_QTI_AISW,  // op package");
            c.line("QNN_OP_MAT_MUL,                // QNN op type");
            c.line("params_matmul_0, 2,            // params + count");
            c.line("inputs_matmul_0, 2,            // input tensor names + count");
            c.line("outputs_matmul_0, 1            // output tensors + count");
        });
        c.line("), err);");
        c.blank();
        c.comment("Collect the constructed graph into the output variables. The");
        c.comment("graph is finalized later by the runtime (e.g. qnn-net-run).");
        c.line("QnnModel* models[] = {&matmul_graph};");
        c.line("uint32_t numModels = 1;");
        c.line("VALIDATE(getGraphInfoFromModels(*models, numModels, graphsInfo), err);");
        c.line("*numGraphsInfo = numModels;");
        c.blank();
        c.line("return err;");
    });
    c.line("}");
    c.blank();
    c.line("QNN_API");
    c.line("ModelError_t QnnModel_freeGraphsInfo(GraphInfoPtr_t** graphsInfo, uint32_t numGraphsInfo) {");
    c.block(|c| {
        c.line("return qnn_wrapper_api::freeGraphsInfo(graphsInfo, numGraphsInfo);");
    });
    c.line("}");
    c.blank();
    c.line("}  // extern \"C\"");
    c.into_string()
}

/// `verify.py` — two modes. `--gen` writes `in0.raw` / `in1.raw` /
/// `input_list.txt` / `expected.raw` (numpy, seed 0); `--check` reshapes the
/// `qnn-net-run` output and asserts it against numpy. Validates the model on
/// the QNN x86 reference backend without Snapdragon hardware.
fn emit_verify_py(m: usize, k: usize, n: usize) -> String {
    format!(
        r#"#!/usr/bin/env python3
# Generated by rlx-qnn. Host harness for the emitted QNN matmul model.
#
#   python3 verify.py --gen     # write in0.raw, in1.raw, input_list.txt, expected.raw
#   python3 verify.py --check   # compare qnn-net-run output vs numpy in0 @ in1
#
# run_qnn.sh calls both around qnn-model-lib-generator + qnn-net-run.

import argparse
import numpy as np

M, K, N = {m}, {k}, {n}


def gen():
    rng = np.random.default_rng(0)
    in0 = rng.standard_normal((M, K)).astype(np.float32)
    in1 = rng.standard_normal((K, N)).astype(np.float32)
    in0.tofile("in0.raw")
    in1.tofile("in1.raw")
    (in0 @ in1).astype(np.float32).tofile("expected.raw")
    with open("input_list.txt", "w") as f:
        f.write("in0:=in0.raw in1:=in1.raw\n")
    print("wrote in0.raw, in1.raw, input_list.txt, expected.raw")


def check():
    out = np.fromfile("output/Result_0/out.raw", dtype=np.float32).reshape(M, N)
    expected = np.fromfile("expected.raw", dtype=np.float32).reshape(M, N)
    np.testing.assert_allclose(out, expected, atol=1e-3, rtol=1e-3)
    print("SUCCESS!")


parser = argparse.ArgumentParser()
parser.add_argument("--gen", action="store_true", help="write inputs + expected")
parser.add_argument("--check", action="store_true", help="check qnn-net-run output")
args = parser.parse_args()
if args.gen:
    gen()
elif args.check:
    check()
else:
    parser.error("pass --gen or --check")
"#
    )
}

/// `run_qnn.sh` — generate inputs, build the model lib, run it on the x86 CPU
/// reference backend (`libQnnCpu.so`), and check the output. No Snapdragon
/// device needed; swap the backend to `libQnnHtp.so` to run on the NPU.
fn emit_run_qnn_sh() -> String {
    "#!/usr/bin/env bash\n\
     # Generated by rlx-qnn. Build + run the QNN matmul model on the x86\n\
     # reference backend (libQnnCpu.so) — no Snapdragon hardware required.\n\
     set -e\n\
     \n\
     : \"${QNN_SDK_ROOT:?set QNN_SDK_ROOT to your Qualcomm AI Engine Direct SDK}\"\n\
     source \"$QNN_SDK_ROOT/bin/envsetup.sh\"\n\
     \n\
     TARGET=x86_64-linux-clang\n\
     BACKEND=\"$QNN_SDK_ROOT/lib/$TARGET/libQnnCpu.so\"\n\
     \n\
     # 1. inputs + expected output (numpy, seed 0)\n\
     python3 verify.py --gen\n\
     \n\
     # 2. compile the composed graph into a shared library (lib<name>.so)\n\
     MODEL_LIB=qnn_model\n\
     qnn-model-lib-generator -c qnn_model.cpp -t $TARGET -l $MODEL_LIB -o model_libs\n\
     \n\
     # 3. run on the CPU reference backend (swap to libQnnHtp.so for the NPU)\n\
     qnn-net-run \\\n\
       --backend \"$BACKEND\" \\\n\
       --model model_libs/$TARGET/lib${MODEL_LIB}.so \\\n\
       --input_list input_list.txt \\\n\
       --output_dir output\n\
     \n\
     # 4. check device output against numpy\n\
     python3 verify.py --check\n"
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn artifact<'a>(arts: &'a [Artifact], path: &str) -> &'a str {
        &arts
            .iter()
            .find(|a| a.path == path)
            .expect("artifact present")
            .contents
    }

    /// Net (open − close) for `()`, `{}`, `[]`, ignoring `//` comments and
    /// `"…"` string literals. `(0, 0, 0)` iff balanced. Guards the
    /// hand-written designated-initializer brace nesting in `cpp::tensor_v1`.
    fn delimiter_residual(src: &str) -> (i32, i32, i32) {
        let (mut paren, mut brace, mut brack) = (0i32, 0i32, 0i32);
        for line in src.lines() {
            let chars: Vec<char> = line.chars().collect();
            let mut in_string = false;
            let mut i = 0;
            while i < chars.len() {
                let c = chars[i];
                if in_string {
                    if c == '\\' {
                        i += 2;
                        continue;
                    }
                    if c == '"' {
                        in_string = false;
                    }
                    i += 1;
                    continue;
                }
                match c {
                    '"' => in_string = true,
                    '/' if i + 1 < chars.len() && chars[i + 1] == '/' => break,
                    '(' => paren += 1,
                    ')' => paren -= 1,
                    '{' => brace += 1,
                    '}' => brace -= 1,
                    '[' => brack += 1,
                    ']' => brack -= 1,
                    _ => {}
                }
                i += 1;
            }
        }
        (paren, brace, brack)
    }

    #[test]
    fn qnn_model_cpp_is_delimiter_balanced() {
        // The MatMul tensor literals nest five braces each; a miscount silently
        // emits C++ that qnn-model-lib-generator rejects. Check several shapes.
        for (m, k, n) in [(1, 1, 1), (3, 5, 7), (8, 16, 4), (32, 64, 32)] {
            let arts = collect_artifacts(&Model::single_matmul("mm", m, k, n)).unwrap();
            let cpp = artifact(&arts, "qnn_model.cpp");
            assert_eq!(
                delimiter_residual(cpp),
                (0, 0, 0),
                "qnn_model.cpp unbalanced for {m}x{k}x{n}"
            );
        }
    }

    #[test]
    fn emits_full_artifact_set() {
        let model = Model::single_matmul("mm", 3, 5, 7);
        let arts = collect_artifacts(&model).unwrap();
        let paths: Vec<&str> = arts.iter().map(|a| a.path.as_str()).collect();
        assert_eq!(paths, ["qnn_model.cpp", "verify.py", "run_qnn.sh"]);
    }

    #[test]
    fn qnn_model_carries_dims_and_node() {
        let model = Model::single_matmul("mm", 3, 5, 7);
        let arts = collect_artifacts(&model).unwrap();
        let cpp = artifact(&arts, "qnn_model.cpp");
        assert!(cpp.contains("QnnModel_composeGraphs"));
        assert!(cpp.contains("#define DO_GRAPH_NODE_VALIDATIONS 1"));
        assert!(cpp.contains("uint32_t dimensions_in0[] = {3, 5};"));
        assert!(cpp.contains("uint32_t dimensions_in1[] = {5, 7};"));
        assert!(cpp.contains("uint32_t dimensions_out[] = {3, 7};"));
        assert!(cpp.contains("QNN_OP_MAT_MUL"));
        assert!(cpp.contains("matmul_graph.addNode("));
        assert!(cpp.contains(".v1 = {"));
        assert!(cpp.contains(".name           = \"in0\","));
        // Real wrapper API has no freeze(); finalize happens in the runtime.
        assert!(!cpp.contains("freeze"));
        assert!(cpp.contains("getGraphInfoFromModels(*models, numModels, graphsInfo)"));
        assert!(cpp.contains("QnnModel_freeGraphsInfo"));
    }

    #[test]
    fn verify_uses_dims_and_checks() {
        let model = Model::single_matmul("mm", 4, 6, 8);
        let arts = collect_artifacts(&model).unwrap();
        let v = artifact(&arts, "verify.py");
        assert!(v.contains("M, K, N = 4, 6, 8"));
        assert!(v.contains("in0 @ in1"));
        assert!(v.contains("np.testing.assert_allclose"));
    }

    #[test]
    fn run_sh_invokes_qnn_tools() {
        let model = Model::single_matmul("mm", 2, 2, 2);
        let arts = collect_artifacts(&model).unwrap();
        let sh = artifact(&arts, "run_qnn.sh");
        assert!(sh.contains("qnn-model-lib-generator"));
        assert!(sh.contains("qnn-net-run"));
        assert!(sh.contains("libQnnCpu.so"));
    }

    #[test]
    fn rejects_zero_dims() {
        let model = Model::single_matmul("bad", 0, 4, 4);
        assert!(collect_artifacts(&model).is_err());
    }

    #[test]
    fn emit_model_writes_files() {
        let dir = tempfile::tempdir().unwrap();
        let model = Model::single_matmul("mm", 2, 3, 4);
        emit_model(&model, dir.path()).unwrap();
        for f in ["qnn_model.cpp", "verify.py", "run_qnn.sh"] {
            assert!(dir.path().join(f).exists(), "{f} written");
        }
    }
}
