// AUTO-GENERATED by rlx-torch-import (tensor style) — do not edit by hand.
// SPDX-License-Identifier: MIT OR Apache-2.0
#![allow(nonstandard_style, unused_parens, clippy::all)]

use rlx_ir::op::MaskKind;

/// Weight keys to bind after compiling (loaded from safetensors).
pub const PARAM_KEYS: &[&str] = &["ln.weight", "ln.bias", "fc1.weight", "fc1.bias", "fc2.weight", "fc2.bias"];
/// Synthesized zero params (key, numel).
pub const ZERO_PARAMS: &[(&str, usize)] = &[];

/// Build the model as an `rlx_tensor` graph (PyTorch-like DSL).
pub fn build_graph() -> rlx_ir::Graph {
    rlx_tensor::graph("mlp", |g| {
        let t_x = g.input("x", rlx_ir::Shape::new(&[2, 4, 16], rlx_ir::DType::F32));
        let t_p_ln_weight = g.param("ln.weight", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
        let t_p_ln_bias = g.param("ln.bias", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
        let t_p_fc1_weight = g.param("fc1.weight", rlx_ir::Shape::new(&[32, 16], rlx_ir::DType::F32));
        let t_p_fc1_bias = g.param("fc1.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
        let t_p_fc2_weight = g.param("fc2.weight", rlx_ir::Shape::new(&[16, 32], rlx_ir::DType::F32));
        let t_p_fc2_bias = g.param("fc2.bias", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
        // aten.layer_norm.default  (x[2, 4, 16], p_ln_weight[16], p_ln_bias[16]) -> [2, 4, 16] f32
        let t_layer_norm = t_x.layer_norm(&t_p_ln_weight, &t_p_ln_bias, 0.00001f32);
        // aten.view.default  (layer_norm[2, 4, 16]) -> [8, 16] f32
        let t_view = t_layer_norm.reshape(vec![8i64, 16i64]);
        // aten.permute.default  (p_fc1_weight[32, 16]) -> [16, 32] f32
        let t_permute = t_p_fc1_weight.transpose(vec![1usize, 0usize]);
        let t_addmm__mm = t_view.mm(&t_permute);
        // aten.addmm.default  (p_fc1_bias[32], view[8, 16], permute[16, 32]) -> [8, 32] f32
        let t_addmm = (&t_addmm__mm + &t_p_fc1_bias);
        // aten.view.default  (addmm[8, 32]) -> [2, 4, 32] f32
        let t_view_1 = t_addmm.reshape(vec![2i64, 4i64, 32i64]);
        // aten.gelu.default  (view_1[2, 4, 32]) -> [2, 4, 32] f32
        let t_gelu = t_view_1.gelu();
        // aten.view.default  (gelu[2, 4, 32]) -> [8, 32] f32
        let t_view_2 = t_gelu.reshape(vec![8i64, 32i64]);
        // aten.permute.default  (p_fc2_weight[16, 32]) -> [32, 16] f32
        let t_permute_1 = t_p_fc2_weight.transpose(vec![1usize, 0usize]);
        let t_addmm_1__mm = t_view_2.mm(&t_permute_1);
        // aten.addmm.default  (p_fc2_bias[16], view_2[8, 32], permute_1[32, 16]) -> [8, 16] f32
        let t_addmm_1 = (&t_addmm_1__mm + &t_p_fc2_bias);
        // aten.view.default  (addmm_1[8, 16]) -> [2, 4, 16] f32
        let t_view_3 = t_addmm_1.reshape(vec![2i64, 4i64, 16i64]);
        t_view_3
    })
}
