// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
// SPDX-License-Identifier: MIT OR Apache-2.0

// Element-wise unary / activation. One kernel covers every per-element
// f32 → f32 transform via an op-kind selector.
//
// The `rlx_activation_apply(op, x)` function is @generated by rlxsl
// and prepended to this file at build time (see build.rs). The activation math
// is defined ONCE in `rlxsl::activation_expr` and shared with the
// other backends' emitters — this file only owns the kernel plumbing. The op
// ids follow `rlx_ir::opcodes::Activation::opcode_relu_first`.

struct Params {
    n: u32,
    in_off: u32,
    out_off: u32,
    op: u32,
    _p0: u32, _p1: u32, _p2: u32, _p3: u32,
};

@group(0) @binding(0) var<storage, read_write> arena: array<f32>;
@group(0) @binding(1) var<uniform>              params: Params;

@compute @workgroup_size(64)
fn unary(@builtin(global_invocation_id) gid: vec3<u32>, @builtin(num_workgroups) ngs: vec3<u32>) {
    let i = gid.x + gid.y * ngs.x * 64u;
    if (i >= params.n) { return; }
    let x = arena[params.in_off + i];
    arena[params.out_off + i] = rlx_activation_apply(params.op, x);
}
