// AUTO-GENERATED by rlx-torch-import — do not edit by hand.
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Provenance: this RLX graph was imported from a PyTorch `torch.export`
// graph. Each op below is annotated with its original aten op + shapes so
// the source model can be traced / reconstructed.
//
// Original aten op histogram:
//      3  _getitem
//      2  aten._native_batch_norm_legit_no_training.default
//      2  aten.convolution.default
//      2  aten.relu.default
//      1  aten.addmm.default
//      1  aten.max_pool2d_with_indices.default
//      1  aten.mean.dim
//      1  aten.permute.default
//      1  aten.view.default

use std::collections::HashMap;
use rlx_ir::hir::{HirMut, HirNodeId};
use rlx_ir::op::{Activation, BinaryOp, MaskKind, ReduceOp};
use rlx_ir::{HirGraphExt, HirModule};

use crate::weights::LoadedWeights;

fn rlx_torch_fill(value: f64, dtype: rlx_ir::DType, numel: usize) -> Vec<u8> {
    let one: Vec<u8> = match dtype {
        rlx_ir::DType::F32 => (value as f32).to_le_bytes().to_vec(),
        rlx_ir::DType::F64 => value.to_le_bytes().to_vec(),
        rlx_ir::DType::I64 => (value as i64).to_le_bytes().to_vec(),
        rlx_ir::DType::I32 => (value as i32).to_le_bytes().to_vec(),
        _ => vec![],
    };
    let mut out = Vec::with_capacity(one.len() * numel);
    for _ in 0..numel { out.extend_from_slice(&one); }
    out
}

/// Build the model graph and assemble its parameter map.
pub fn build_graph(
    w: &LoadedWeights,
) -> anyhow::Result<(HirModule, HashMap<String, Vec<f32>>)> {
    let mut hir = HirModule::new("cnn");
    let mut b = HirMut::new(&mut hir);
    let mut params: HashMap<String, Vec<f32>> = HashMap::new();

    let t_x = b.input("x", rlx_ir::Shape::new(&[2, 3, 16, 16], rlx_ir::DType::F32));

    let t_p_c1_weight = b.param("c1.weight", rlx_ir::Shape::new(&[8, 3, 3, 3], rlx_ir::DType::F32));
    params.insert("c1.weight".to_string(), w.get("c1.weight")?);
    let t_p_c1_bias = b.param("c1.bias", rlx_ir::Shape::new(&[8], rlx_ir::DType::F32));
    params.insert("c1.bias".to_string(), w.get("c1.bias")?);
    let t_p_b1_weight = b.param("b1.weight", rlx_ir::Shape::new(&[8], rlx_ir::DType::F32));
    params.insert("b1.weight".to_string(), w.get("b1.weight")?);
    let t_p_b1_bias = b.param("b1.bias", rlx_ir::Shape::new(&[8], rlx_ir::DType::F32));
    params.insert("b1.bias".to_string(), w.get("b1.bias")?);
    let t_p_c2_weight = b.param("c2.weight", rlx_ir::Shape::new(&[16, 8, 3, 3], rlx_ir::DType::F32));
    params.insert("c2.weight".to_string(), w.get("c2.weight")?);
    let t_p_c2_bias = b.param("c2.bias", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
    params.insert("c2.bias".to_string(), w.get("c2.bias")?);
    let t_p_b2_weight = b.param("b2.weight", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
    params.insert("b2.weight".to_string(), w.get("b2.weight")?);
    let t_p_b2_bias = b.param("b2.bias", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
    params.insert("b2.bias".to_string(), w.get("b2.bias")?);
    let t_p_head_weight = b.param("head.weight", rlx_ir::Shape::new(&[10, 16], rlx_ir::DType::F32));
    params.insert("head.weight".to_string(), w.get("head.weight")?);
    let t_p_head_bias = b.param("head.bias", rlx_ir::Shape::new(&[10], rlx_ir::DType::F32));
    params.insert("head.bias".to_string(), w.get("head.bias")?);
    let t_b_b1_running_mean = b.param("b1.running_mean", rlx_ir::Shape::new(&[8], rlx_ir::DType::F32));
    params.insert("b1.running_mean".to_string(), w.get("b1.running_mean")?);
    let t_b_b1_running_var = b.param("b1.running_var", rlx_ir::Shape::new(&[8], rlx_ir::DType::F32));
    params.insert("b1.running_var".to_string(), w.get("b1.running_var")?);
    let t_b_b1_num_batches_tracked = b.param("b1.num_batches_tracked", rlx_ir::Shape::new(&[], rlx_ir::DType::I64));
    params.insert("b1.num_batches_tracked".to_string(), w.get("b1.num_batches_tracked")?);
    let t_b_b2_running_mean = b.param("b2.running_mean", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
    params.insert("b2.running_mean".to_string(), w.get("b2.running_mean")?);
    let t_b_b2_running_var = b.param("b2.running_var", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
    params.insert("b2.running_var".to_string(), w.get("b2.running_var")?);
    let t_b_b2_num_batches_tracked = b.param("b2.num_batches_tracked", rlx_ir::Shape::new(&[], rlx_ir::DType::I64));
    params.insert("b2.num_batches_tracked".to_string(), w.get("b2.num_batches_tracked")?);

    let t_convolution__conv = b.conv2d(t_x, t_p_c1_weight, [3, 3], [1, 1], [1, 1], 1, rlx_ir::Shape::new(&[2, 8, 16, 16], rlx_ir::DType::F32));
    let t_convolution__bias = b.reshape_(t_p_c1_bias, vec![1i64, 8i64, 1i64, 1i64]);
    // aten.convolution.default  (x[2, 3, 16, 16], p_c1_weight[8, 3, 3, 3], p_c1_bias[8]) -> [2, 8, 16, 16] f32
    let t_convolution = b.add(t_convolution__conv, t_convolution__bias);
    let bytes_t__native_batch_norm_legit_no_training__scalar = rlx_torch_fill(0.000009999999747378752f64, rlx_ir::DType::F32, 1);
    let t__native_batch_norm_legit_no_training__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t__native_batch_norm_legit_no_training__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    let t__native_batch_norm_legit_no_training__vpe = b.add(t_b_b1_running_var, t__native_batch_norm_legit_no_training__scalar);
    let s_t__native_batch_norm_legit_no_training__inv = b.shape(t__native_batch_norm_legit_no_training__vpe).clone();
    let t__native_batch_norm_legit_no_training__inv = b.activation(Activation::Rsqrt, t__native_batch_norm_legit_no_training__vpe, s_t__native_batch_norm_legit_no_training__inv);
    let t__native_batch_norm_legit_no_training__scale = b.mul(t_p_b1_weight, t__native_batch_norm_legit_no_training__inv);
    let t__native_batch_norm_legit_no_training__ms = b.mul(t_b_b1_running_mean, t__native_batch_norm_legit_no_training__scale);
    let t__native_batch_norm_legit_no_training__shift = b.sub(t_p_b1_bias, t__native_batch_norm_legit_no_training__ms);
    let t__native_batch_norm_legit_no_training__scr = b.reshape_(t__native_batch_norm_legit_no_training__scale, vec![1i64, 8i64, 1i64, 1i64]);
    let t__native_batch_norm_legit_no_training__shr = b.reshape_(t__native_batch_norm_legit_no_training__shift, vec![1i64, 8i64, 1i64, 1i64]);
    let t__native_batch_norm_legit_no_training__xs = b.mul(t_convolution, t__native_batch_norm_legit_no_training__scr);
    // aten._native_batch_norm_legit_no_training.default  (convolution[2, 8, 16, 16], p_b1_weight[8], p_b1_bias[8], b_b1_running_mean[8], b_b1_running_var[8]) -> [2, 8, 16, 16] f32
    let t__native_batch_norm_legit_no_training = b.add(t__native_batch_norm_legit_no_training__xs, t__native_batch_norm_legit_no_training__shr);
    // aten.relu.default  (getitem[2, 8, 16, 16]) -> [2, 8, 16, 16] f32
    let s_t_relu = b.shape(t__native_batch_norm_legit_no_training).clone();
    let t_relu = b.activation(Activation::Relu, t__native_batch_norm_legit_no_training, s_t_relu);
    // aten.max_pool2d_with_indices.default  (relu[2, 8, 16, 16]) -> [2, 8, 8, 8] f32
    let t_max_pool2d_with_indices = b.add_node(rlx_ir::Op::Pool { kind: rlx_ir::op::ReduceOp::Max, kernel_size: vec![2usize, 2usize], stride: vec![2usize, 2usize], padding: vec![0usize, 0usize] }, vec![t_relu], rlx_ir::Shape::new(&[2, 8, 8, 8], rlx_ir::DType::F32));
    let t_convolution_1__conv = b.conv2d(t_max_pool2d_with_indices, t_p_c2_weight, [3, 3], [1, 1], [1, 1], 1, rlx_ir::Shape::new(&[2, 16, 8, 8], rlx_ir::DType::F32));
    let t_convolution_1__bias = b.reshape_(t_p_c2_bias, vec![1i64, 16i64, 1i64, 1i64]);
    // aten.convolution.default  (getitem_3[2, 8, 8, 8], p_c2_weight[16, 8, 3, 3], p_c2_bias[16]) -> [2, 16, 8, 8] f32
    let t_convolution_1 = b.add(t_convolution_1__conv, t_convolution_1__bias);
    let bytes_t__native_batch_norm_legit_no_training_1__scalar = rlx_torch_fill(0.000009999999747378752f64, rlx_ir::DType::F32, 1);
    let t__native_batch_norm_legit_no_training_1__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t__native_batch_norm_legit_no_training_1__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    let t__native_batch_norm_legit_no_training_1__vpe = b.add(t_b_b2_running_var, t__native_batch_norm_legit_no_training_1__scalar);
    let s_t__native_batch_norm_legit_no_training_1__inv = b.shape(t__native_batch_norm_legit_no_training_1__vpe).clone();
    let t__native_batch_norm_legit_no_training_1__inv = b.activation(Activation::Rsqrt, t__native_batch_norm_legit_no_training_1__vpe, s_t__native_batch_norm_legit_no_training_1__inv);
    let t__native_batch_norm_legit_no_training_1__scale = b.mul(t_p_b2_weight, t__native_batch_norm_legit_no_training_1__inv);
    let t__native_batch_norm_legit_no_training_1__ms = b.mul(t_b_b2_running_mean, t__native_batch_norm_legit_no_training_1__scale);
    let t__native_batch_norm_legit_no_training_1__shift = b.sub(t_p_b2_bias, t__native_batch_norm_legit_no_training_1__ms);
    let t__native_batch_norm_legit_no_training_1__scr = b.reshape_(t__native_batch_norm_legit_no_training_1__scale, vec![1i64, 16i64, 1i64, 1i64]);
    let t__native_batch_norm_legit_no_training_1__shr = b.reshape_(t__native_batch_norm_legit_no_training_1__shift, vec![1i64, 16i64, 1i64, 1i64]);
    let t__native_batch_norm_legit_no_training_1__xs = b.mul(t_convolution_1, t__native_batch_norm_legit_no_training_1__scr);
    // aten._native_batch_norm_legit_no_training.default  (convolution_1[2, 16, 8, 8], p_b2_weight[16], p_b2_bias[16], b_b2_running_mean[16], b_b2_running_var[16]) -> [2, 16, 8, 8] f32
    let t__native_batch_norm_legit_no_training_1 = b.add(t__native_batch_norm_legit_no_training_1__xs, t__native_batch_norm_legit_no_training_1__shr);
    // aten.relu.default  (getitem_5[2, 16, 8, 8]) -> [2, 16, 8, 8] f32
    let s_t_relu_1 = b.shape(t__native_batch_norm_legit_no_training_1).clone();
    let t_relu_1 = b.activation(Activation::Relu, t__native_batch_norm_legit_no_training_1, s_t_relu_1);
    // aten.mean.dim  (relu_1[2, 16, 8, 8]) -> [2, 16, 1, 1] f32
    let t_mean = b.mean(t_relu_1, vec![3usize, 2usize], true);
    // aten.view.default  (mean[2, 16, 1, 1]) -> [2, 16] f32
    let t_view = b.reshape_(t_mean, vec![2i64, 16i64]);
    // aten.permute.default  (p_head_weight[10, 16]) -> [16, 10] f32
    let t_permute = b.transpose_(t_p_head_weight, vec![1usize, 0usize]);
    let t_addmm__mm = b.mm(t_view, t_permute);
    // aten.addmm.default  (p_head_bias[10], view[2, 16], permute[16, 10]) -> [2, 10] f32
    let t_addmm = b.add(t_addmm__mm, t_p_head_bias);

    b.set_outputs(vec![t_addmm]);
    Ok((hir, params))
}
