//! Native RLX model `mlp` — generated by `rlx-torch-import` (flow style).
#![allow(nonstandard_style, unused_imports, clippy::all)]

pub mod graph;
pub mod weights;

pub use weights::load_weights;

/// Compile the model on `device`, binding weights from `dir/weights.safetensors`.
pub fn compile(
    device: rlx_runtime::Device,
    dir: &std::path::Path,
) -> anyhow::Result<rlx_runtime::CompiledGraph> {
    let mut weights = load_weights(dir)?;
    let built = graph::build_flow().build(&mut weights)?;
    let (hir, params) = built.into_parts()?;
    let mut compiled = rlx_runtime::Session::new(device)
        .compile_hir_with(hir, &rlx_runtime::CompileOptions::default())
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    for (name, data) in params {
        compiled.set_param(name.as_str(), &data);
    }
    Ok(compiled)
}
