// SPDX-License-Identifier: MIT OR Apache-2.0
//! Native RLX model `mlp` — generated by `rlx-torch-import` from a
//! PyTorch `torch.export` graph. Do not edit `graph.rs` / `weights.rs` by hand.
#![allow(nonstandard_style, unused_imports, unused_parens, dead_code, clippy::all)]

pub mod graph;
pub mod weights;

pub use graph::build_graph;
pub use weights::{load_weights, LoadedWeights};

/// Compile the model on `device`, binding weights from `dir/weights.safetensors`.
pub fn compile(
    device: rlx_runtime::Device,
    dir: &std::path::Path,
) -> anyhow::Result<rlx_runtime::CompiledGraph> {
    let w = load_weights(dir)?;
    let (hir, params) = build_graph(&w)?;
    let mut compiled = rlx_runtime::Session::new(device)
        .compile_hir_with(hir, &rlx_runtime::CompileOptions::default())
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    for (name, data) in params {
        compiled.set_param(name.as_str(), &data);
    }
    Ok(compiled)
}

/// Input names + shapes (row-major, f32 on the wire).
pub const INPUTS: &[(&str, &[usize])] = &[
    ("x", &[2, 4, 16]),
];
