"""Type stubs for ``pyrlx._pyrlx`` (PyO3 extension).

The public package ``pyrlx`` re-exports these symbols and adds the pure-Python
DSL: ``graph()``, ``Node``, ``set_param``, ``run``. Stubs here cover the native
layer only; see ``python/pyrlx/__init__.py`` for the full surface.
"""

from __future__ import annotations

from typing import Any, Literal, Mapping, Sequence, overload

import numpy as np
import numpy.typing as npt

__version__: str

# ── Devices ─────────────────────────────────────────────────────────

DeviceName = Literal[
    "cpu", "metal", "mlx", "ane",
    "cuda", "rocm",
    "gpu", "vulkan", "opengl", "directx", "webgpu",
]

PrecisionName = Literal["f32", "f16", "bf16", "float32", "float16", "bfloat16"]

DTypeName = Literal[
    "f32", "f16", "bf16", "f64",
    "i8", "u8", "i16", "i32", "u32", "i64",
    "bool",
]

ActivationName = Literal[
    "gelu", "gelu_approx", "silu", "relu", "sigmoid",
    "tanh", "exp", "log", "sqrt", "rsqrt", "neg", "abs",
]

BinaryOpName = Literal[
    "add", "sub", "mul", "div", "max", "min", "pow",
    "+", "-", "*", "/",
]
CompareName = Literal[
    "eq", "ne", "lt", "le", "gt", "ge",
    "==", "!=", "<", "<=", ">", ">=",
]
ReduceName = Literal["sum", "mean", "max", "min", "prod"]
FftNormName = Literal["backward", "none", "forward", "ortho", "orthonormal"]
MaskKindName = Literal["none", "causal"] | str  # also "sliding:<N>"

NodeId = int

def available_devices() -> list[str]: ...
def is_available(name: str) -> bool: ...
def parse_device_py(name: str) -> str: ...
def backends_manifest() -> str: ...
def fastest_device_for_py(graph: Graph) -> str: ...
def device_report_py(device: str) -> str: ...

def grad(graph: Graph, wrt: Sequence[str]) -> Graph: ...
def jvp(graph: Graph, wrt: Sequence[str]) -> Graph: ...
def hvp(graph: Graph, wrt: Sequence[str]) -> Graph: ...
def nth_order_grad(graph: Graph, order: int, wrt: Sequence[str]) -> Graph: ...
def directional_nth_grad(
    graph: Graph, order: int, wrt: Sequence[str], direction: Mapping[str, npt.NDArray[Any]]
) -> Graph: ...
def vmap(graph: Graph, in_axes: Mapping[str, int], batch_size: int) -> Graph: ...

class Graph:
    """Symbolic RLX graph. Consumed by ``Session.compile``.

    Methods return integer node ids. Shape-inferred builders (``matmul``,
    ``gelu``, ``conv2d``, ``constant``, …) omit ``out_shape``; explicit-shape
    variants exist for LoRA, sampling, and hand-declared layouts.

    Reserved names use a trailing underscore: ``where_``, ``eq_``, ``lt_``,
    ``gt_``, ``ge_``, ``ne_``.
    """

    def __init__(self, name: str) -> None: ...

    # I/O + literals
    def input(self, name: str, shape: Sequence[int], dtype: DTypeName) -> NodeId: ...
    def param(self, name: str, shape: Sequence[int], dtype: DTypeName) -> NodeId: ...
    def constant(self, value: float, dtype: DTypeName = "f32") -> NodeId: ...
    def set_outputs(self, outputs: Sequence[NodeId]) -> None: ...
    def shape_of(self, id: NodeId) -> tuple[list[int], str]: ...

    # Linear algebra
    def matmul(self, lhs: NodeId, rhs: NodeId) -> NodeId: ...
    def matmul_with_shape(
        self, lhs: NodeId, rhs: NodeId,
        out_shape: Sequence[int], dtype: DTypeName,
    ) -> NodeId: ...
    def lora_matmul(
        self, x: NodeId, w: NodeId, a: NodeId, b: NodeId, scale: float,
        out_shape: Sequence[int], dtype: DTypeName,
    ) -> NodeId: ...
    def dense_solve(
        self, a: NodeId, b: NodeId, out_shape: Sequence[int], dtype: DTypeName,
    ) -> NodeId: ...
    def batched_dense_solve(
        self, a: NodeId, b: NodeId, out_shape: Sequence[int], dtype: DTypeName,
    ) -> NodeId: ...
    def custom_fn(
        self,
        inputs: Sequence[NodeId],
        fwd_body: Graph,
        vjp_body: Graph | None = ...,
        jvp_body: Graph | None = ...,
    ) -> NodeId: ...
    def fused_matmul_bias_act(
        self, input: NodeId, weight: NodeId, bias: NodeId,
        out_shape: Sequence[int], dtype: DTypeName,
        activation: ActivationName | None = ...,
    ) -> NodeId: ...

    # Element-wise
    def binary(self, op: BinaryOpName, lhs: NodeId, rhs: NodeId) -> NodeId: ...
    def add(self, a: NodeId, b: NodeId) -> NodeId: ...
    def sub(self, a: NodeId, b: NodeId) -> NodeId: ...
    def mul(self, a: NodeId, b: NodeId) -> NodeId: ...
    def div(self, a: NodeId, b: NodeId) -> NodeId: ...
    def activation(self, kind: ActivationName, input: NodeId) -> NodeId: ...
    def gelu(self, x: NodeId) -> NodeId: ...
    def gelu_approx(self, x: NodeId) -> NodeId: ...
    def silu(self, x: NodeId) -> NodeId: ...
    def relu(self, x: NodeId) -> NodeId: ...
    def exp(self, x: NodeId) -> NodeId: ...
    def sqrt(self, x: NodeId) -> NodeId: ...
    def neg(self, x: NodeId) -> NodeId: ...
    def tanh(self, x: NodeId) -> NodeId: ...
    def stop_gradient(self, x: NodeId) -> NodeId: ...
    def resize_nearest_2x(self, x: NodeId) -> NodeId: ...

    # Convolution
    def conv2d(
        self, input: NodeId, weight: NodeId,
        kernel_size: Sequence[int], stride: Sequence[int],
        padding: Sequence[int], dilation: Sequence[int],
        groups: int = 1,
    ) -> NodeId: ...
    def conv_transpose2d(
        self, input: NodeId, weight: NodeId,
        kernel_size: Sequence[int], stride: Sequence[int],
        padding: Sequence[int], dilation: Sequence[int],
        output_padding: Sequence[int], groups: int = 1,
    ) -> NodeId: ...

    # Comparison + select
    def compare(self, op: CompareName, lhs: NodeId, rhs: NodeId) -> NodeId: ...
    def eq_(self, a: NodeId, b: NodeId) -> NodeId: ...
    def lt_(self, a: NodeId, b: NodeId) -> NodeId: ...
    def gt_(self, a: NodeId, b: NodeId) -> NodeId: ...
    def ge_(self, a: NodeId, b: NodeId) -> NodeId: ...
    def ne_(self, a: NodeId, b: NodeId) -> NodeId: ...
    def where_(self, cond: NodeId, a: NodeId, b: NodeId) -> NodeId: ...

    # Reduction
    def reduce(
        self, input: NodeId, op: ReduceName,
        axes: Sequence[int], keep_dim: bool = ...,
    ) -> NodeId: ...
    def sum(self, x: NodeId, axes: Sequence[int], keep_dim: bool) -> NodeId: ...
    def mean(self, x: NodeId, axes: Sequence[int], keep_dim: bool) -> NodeId: ...
    def softmax(self, input: NodeId, axis: int = -1) -> NodeId: ...
    def cumsum(self, input: NodeId, axis: int, exclusive: bool = ...) -> NodeId: ...
    def sample(
        self, logits: NodeId, top_k: int, top_p: float,
        temperature: float, seed: int,
        output_shape: Sequence[int], dtype: DTypeName = ...,
    ) -> NodeId: ...

    # Shape ops
    def reshape(self, x: NodeId, new_shape: Sequence[int]) -> NodeId: ...
    def transpose(self, x: NodeId, perm: Sequence[int]) -> NodeId: ...
    def narrow(self, x: NodeId, axis: int, start: int, length: int) -> NodeId: ...
    def concat(self, inputs: Sequence[NodeId], axis: int) -> NodeId: ...
    def gather(self, table: NodeId, indices: NodeId, axis: int) -> NodeId: ...
    def cast(self, x: NodeId, to: DTypeName) -> NodeId: ...

    # FFT
    def fft(self, x: NodeId, inverse: bool = ...) -> NodeId: ...
    def fft_norm(self, x: NodeId, inverse: bool = ..., norm: FftNormName = ...) -> NodeId: ...
    def fft_real(self, x: NodeId, norm: FftNormName = ...) -> tuple[NodeId, NodeId]: ...
    def rfft(self, x: NodeId, norm: FftNormName = ...) -> tuple[NodeId, NodeId]: ...
    def irfft(self, re: NodeId, im: NodeId, n: int, norm: FftNormName = ...) -> NodeId: ...
    def fftfreq(self, n: int) -> NodeId: ...
    def rfftfreq(self, n: int) -> NodeId: ...
    def psd(self, re: NodeId, im: NodeId) -> NodeId: ...
    def psd_real(self, x: NodeId, norm: FftNormName = ...) -> NodeId: ...

    # Normalization
    def layer_norm(
        self, input: NodeId, gamma: NodeId, beta: NodeId,
        axis: int = -1, eps: float = 1e-5,
    ) -> NodeId: ...
    def layer_norm2d(
        self, input: NodeId, gamma: NodeId, beta: NodeId, eps: float = 1e-5,
    ) -> NodeId: ...
    def group_norm(
        self, input: NodeId, gamma: NodeId, beta: NodeId,
        num_groups: int, eps: float = 1e-5,
    ) -> NodeId: ...
    def rms_norm(
        self, input: NodeId, gamma: NodeId, beta: NodeId, eps: float = 1e-5,
    ) -> NodeId: ...

    # Attention + RoPE
    def attention(
        self, q: NodeId, k: NodeId, v: NodeId, mask: NodeId,
        num_heads: int, head_dim: int,
    ) -> NodeId: ...
    def attention_kind(
        self, q: NodeId, k: NodeId, v: NodeId,
        num_heads: int, head_dim: int, mask_kind: str,
    ) -> NodeId: ...
    def rope(self, x: NodeId, cos: NodeId, sin: NodeId, head_dim: int) -> NodeId: ...
    def rope_n(
        self, x: NodeId, cos: NodeId, sin: NodeId,
        head_dim: int, n_rot: int,
    ) -> NodeId: ...

    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class Session:
    """Binds compile + execute to one backend and precision."""
    def __init__(self, device: str = "cpu", precision: str = "f32") -> None: ...
    @property
    def device(self) -> str: ...
    @property
    def precision(self) -> str: ...
    def compile(self, graph: Graph) -> CompiledGraph: ...
    def compile_with(
        self,
        graph: Graph,
        fusion_options: FusionOptions | None = ...,
        kernel_dispatch: str | None = ...,
    ) -> CompiledGraph: ...
    def __repr__(self) -> str: ...

class CompiledGraph:
    """Compiled executable; upload params then call ``run`` or ``run_typed``."""
    @property
    def device(self) -> str: ...
    def set_param(self, name: str, data: npt.NDArray[np.float32]) -> None: ...
    def run(
        self, inputs: Mapping[str, npt.NDArray[np.float32]],
    ) -> list[npt.NDArray[np.float32]]: ...
    def run_flat(
        self, inputs: Mapping[str, npt.NDArray[np.float32]],
    ) -> list[npt.NDArray[np.float32]]: ...
    def set_param_typed(self, name: str, data: bytes, dtype: DTypeName) -> None: ...
    def run_typed(
        self, inputs: Mapping[str, tuple[bytes, DTypeName]],
    ) -> list[tuple[bytes, str]]: ...
    def __repr__(self) -> str: ...

class FusionOptions:
    skip_fusion: bool
    unfuse_elementwise_regions: bool
    keep_elementwise_regions: bool
    decompose_fusion_regions: bool
    fk_fusion: bool
    fuse_region_prologue: bool
    fuse_batch_preprocess: bool
    native_fk_regions: bool
    def __init__(
        self,
        skip_fusion: bool = ...,
        unfuse_elementwise_regions: bool = ...,
        keep_elementwise_regions: bool = ...,
        decompose_fusion_regions: bool = ...,
        fk_fusion: bool = ...,
        fuse_region_prologue: bool = ...,
        fuse_batch_preprocess: bool = ...,
        native_fk_regions: bool = ...,
    ) -> None: ...
    @staticmethod
    def native_fk() -> FusionOptions: ...
    def __repr__(self) -> str: ...

class DevicePolicy:
    @staticmethod
    def all() -> DevicePolicy: ...
    @staticmethod
    def only(devices: Sequence[str]) -> DevicePolicy: ...
    @staticmethod
    def from_env() -> DevicePolicy: ...
    def with_deny(self, devices: Sequence[str]) -> DevicePolicy: ...
    def with_prefer(self, devices: Sequence[str]) -> DevicePolicy: ...
    def with_benchmark_pick(self, runs: int) -> DevicePolicy: ...
    def __repr__(self) -> str: ...

class DeviceCandidate:
    device: str
    available: bool
    reason: str | None
    def __repr__(self) -> str: ...

class DeviceBenchResult:
    device: str
    median_ns: int
    def __repr__(self) -> str: ...

class GraphDevices:
    def __init__(self, graph: Graph, policy: DevicePolicy | None = ...) -> None: ...
    @staticmethod
    def from_env(graph: Graph) -> GraphDevices: ...
    def devices(self) -> list[str]: ...
    def fastest(self) -> str: ...
    def report(self) -> list[DeviceCandidate]: ...
    def set_param(self, name: str, data: npt.NDArray[np.float32]) -> None: ...
    def set_param_typed(self, name: str, data: bytes, dtype: DTypeName) -> None: ...
    def warm_all(self) -> list[str]: ...
    def benchmark(
        self, inputs: Mapping[str, npt.NDArray[np.float32]], runs: int = ...,
    ) -> list[DeviceBenchResult]: ...
    def run(
        self, device: str, inputs: Mapping[str, npt.NDArray[np.float32]],
    ) -> list[npt.NDArray[np.float32]]: ...
    def run_resolved(
        self, inputs: Mapping[str, npt.NDArray[np.float32]],
    ) -> tuple[str, list[npt.NDArray[np.float32]]]: ...
    def run_try(
        self, inputs: Mapping[str, npt.NDArray[np.float32]],
    ) -> tuple[str, list[npt.NDArray[np.float32]]]: ...
    def run_chain(
        self, inputs: Mapping[str, npt.NDArray[np.float32]],
    ) -> tuple[str, list[npt.NDArray[np.float32]]]: ...
    def run_resolved_with_inputs(
        self, inputs: Mapping[str, npt.NDArray[np.float32]],
    ) -> tuple[str, list[npt.NDArray[np.float32]]]: ...
    def __repr__(self) -> str: ...

class FlexibleSession:
    def __init__(self, policy: DevicePolicy | None = ...) -> None: ...
    @staticmethod
    def from_env() -> FlexibleSession: ...
    def compile_resolved(self, graph: Graph) -> tuple[str, CompiledGraph]: ...
    def compile_with_resolved(
        self,
        graph: Graph,
        fusion_options: FusionOptions | None = ...,
        kernel_dispatch: str | None = ...,
    ) -> tuple[str, CompiledGraph]: ...
    def __repr__(self) -> str: ...

class DeviceRouter:
    def __init__(self, graph: Graph, policy: DevicePolicy | None = ...) -> None: ...
    @staticmethod
    def from_env(graph: Graph) -> DeviceRouter: ...
    def with_rebench_on_throttle(self, enabled: bool) -> None: ...
    def devices(self) -> list[str]: ...
    def set_param(self, name: str, data: npt.NDArray[np.float32]) -> None: ...
    def set_param_typed(self, name: str, data: bytes, dtype: DTypeName) -> None: ...
    def run_on(
        self, device: str, inputs: Mapping[str, npt.NDArray[np.float32]],
    ) -> list[npt.NDArray[np.float32]]: ...
    def run(
        self, inputs: Mapping[str, npt.NDArray[np.float32]],
    ) -> tuple[str, list[npt.NDArray[np.float32]]]: ...
    def run_chain(
        self, inputs: Mapping[str, npt.NDArray[np.float32]],
    ) -> tuple[str, list[npt.NDArray[np.float32]]]: ...
    def __repr__(self) -> str: ...

# ── GGUF quantize / dequant ────────────────────────────────────────

def quantize_gguf(
    weights: npt.NDArray[np.float32],
    dtype: str,
) -> npt.NDArray[np.uint8]: ...
def dequant_gguf(
    packed: npt.NDArray[np.uint8],
    dtype: str,
    *,
    num_elements: int | None = ...,
) -> npt.NDArray[np.float32]: ...

class GgufFile:
    @staticmethod
    def load(path: str) -> GgufFile: ...
    def tensor_names(self) -> list[str]: ...
    def tensor_info(self, name: str) -> dict[str, object]: ...
    def dequant_tensor(self, name: str) -> npt.NDArray[np.float32]: ...
    def read_tensor_bytes(self, name: str) -> npt.NDArray[np.uint8]: ...
    @property
    def architecture(self) -> str | None: ...
    def metadata(self) -> dict[str, object]: ...

def load_gguf(path: str) -> GgufFile: ...
def write_gguf(
    path: str,
    tensors: Mapping[str, Mapping[str, object]],
    *,
    architecture: str | None = ...,
    metadata: Mapping[str, object] | None = ...,
) -> None: ...

class GgufConvertReport:
    @property
    def tensors(self) -> int: ...
    @property
    def input_bytes(self) -> int: ...
    @property
    def output_bytes(self) -> int: ...
    @property
    def output_path(self) -> str: ...
    def compression_ratio(self) -> float: ...
    def schemes(self) -> list[tuple[str, str]]: ...

def convert_to_gguf(
    input_path: str,
    output_path: str,
    scheme: str,
    *,
    architecture: str | None = ...,
    skip_norm_bias: bool = ...,
    scheme_overrides: Mapping[str, str] | None = ...,
) -> GgufConvertReport: ...
