// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
// SPDX-License-Identifier: MIT OR Apache-2.0
//! Bit-exactness against the reference implementations.
//!
//! This crate's only reason to exist is producing the *same* stream numpy and
//! torch produce — an RNG that is merely well-distributed would be useless for
//! reproducing a published result. Every vector below was generated by running
//! the reference (numpy 2.4.3, torch 2.11.0) and pasting the output, so these
//! tests fail if the port drifts rather than if the distribution shifts.
//!
//! Generator script, for regenerating after a reference upgrade:
//! ```text
//! np.random.RandomState(12345).random_sample()      -> rs_double
//! np.random.RandomState(12345).normal(0, 1, 8)      -> rs_normal
//! np.random.Generator(np.random.PCG64(12345))       -> gen_*
//! np.random.SeedSequence(12345).generate_state(4)   -> seedseq
//! torch.manual_seed(42); torch.randperm(10)         -> randperm
//! ```

use rlx_rng::numpy;
use rlx_rng::torch;

/// numpy stores doubles to full precision; anything above f64 round-off here is
/// a port bug, not accumulation.
const EPS: f64 = 1e-15;

fn close(a: f64, b: f64) -> bool {
    (a - b).abs() <= EPS * b.abs().max(1.0)
}

#[test]
fn random_state_doubles_match_numpy() {
    let expect = [
        0.929_616_092_817_147_9,
        0.316_375_554_581_785_9,
        0.183_918_811_677_094_45,
        0.204_560_278_553_039_7,
        0.567_725_029_081_686_6,
        0.595_544_702_979_251_6,
    ];
    let mut rs = numpy::RandomState::new(12345);
    for (i, e) in expect.iter().enumerate() {
        let got = rs.random_double();
        assert!(close(got, *e), "draw {i}: {got:.17} != {e:.17}");
    }
}

#[test]
fn random_state_gaussian_matches_numpy() {
    // The polar method returns two variates per loop and numpy caches the
    // second. If the cache were dropped, draw 0 would still match and every
    // odd-indexed draw after it would not — which is why this checks eight.
    let expect = [
        -0.204_707_659_484_712_95,
        0.478_943_338_057_548_24,
        -0.519_438_715_056_738_1,
        -0.555_730_304_347_49,
        1.965_780_572_502_714_2,
        1.393_405_832_972_990_4,
        0.092_907_876_743_717_67,
        0.281_746_152_830_202_5,
    ];
    let mut rs = numpy::RandomState::new(12345);
    let got = rs.normal(0.0, 1.0, expect.len());
    for (i, (g, e)) in got.iter().zip(&expect).enumerate() {
        assert!(close(*g, *e), "draw {i}: {g:.17} != {e:.17}");
    }
}

#[test]
fn random_state_honours_loc_and_scale() {
    let expect = [
        3.767_894_277_850_267,
        2.150_546_972_094_375_5,
        2.524_615_122_758_938_4,
        2.805_637_212_247_381,
        1.908_307_728_530_696,
    ];
    let mut rs = numpy::RandomState::new(7);
    let got = rs.normal(2.5, 0.75, expect.len());
    for (i, (g, e)) in got.iter().zip(&expect).enumerate() {
        assert!(close(*g, *e), "draw {i}: {g:.17} != {e:.17}");
    }
}

#[test]
fn gaussian_random_matrix_matches_sklearn() {
    // sklearn's GaussianRandomProjection draws N(0, 1/k) row-major.
    let expect = [
        0.248_357_076_505_616_34,
        -0.069_132_150_585_592_33,
        0.323_844_269_050_346_25,
        0.761_514_928_204_012_7,
        -0.117_076_687_361_667_99,
        -0.117_068_478_474_590_27,
        0.789_606_407_753_695_7,
        0.383_717_364_576_454_4,
        -0.234_737_192_967_476_05,
        0.271_280_021_792_982_33,
        -0.231_708_846_406_231_13,
        -0.232_864_876_785_128_43,
        0.120_981_135_783_017_06,
        -0.956_640_122_328_899,
        -0.862_458_916_256_516_4,
        -0.281_143_764_620_486_35,
        -0.506_415_560_167_211_9,
        0.157_123_666_297_636_94,
        -0.454_012_037_760_605_56,
        -0.706_151_850_667_645_9,
        0.732_824_384_460_777,
        -0.112_888_150_243_267_83,
        0.033_764_102_343_961_92,
        -0.712_374_093_106_728_4,
    ];
    let got = numpy::gaussian_random_matrix(4, 6, 42);
    assert_eq!(got.len(), expect.len());
    for (i, (g, e)) in got.iter().zip(&expect).enumerate() {
        assert!(close(*g, *e), "entry {i}: {g:.17} != {e:.17}");
    }
}

#[test]
fn seed_sequence_matches_numpy() {
    let expect = [
        2_688_385_916u32,
        3_048_105_090,
        4_196_366_895,
        3_152_189_807,
    ];
    let got = numpy::SeedSequence::new(12345).generate_state(4);
    assert_eq!(got, expect, "SeedSequence(12345).generate_state(4)");
}

#[test]
fn generator_wide_integers_match_numpy() {
    let expect = [
        2_096_804_712_593_481_934u64,
        2_921_580_012_919_480_943,
        7_354_398_262_316_660_716,
        6_237_348_419_996_972_168,
        3_607_348_892_368_485_766,
        3_069_666_675_758_614_433,
    ];
    let mut g = numpy::Generator::new(12345);
    let got = numpy::integers(&mut g, 1u64 << 63, expect.len());
    assert_eq!(got, expect, "Generator(PCG64(12345)).integers(0, 2**63)");
}

#[test]
fn generator_small_range_takes_the_32_bit_path() {
    // `high` under 2^32 makes numpy's Lemire bounded sampler dispatch to its
    // 32-bit variant, which buffers the unused high half of each 64-bit draw.
    // A port that always uses the 64-bit path is still uniform and still wrong.
    let expect = [6u64, 2, 7, 3, 2, 7, 6, 6, 9, 3, 8, 3];
    let mut g = numpy::Generator::new(12345);
    let got = numpy::integers(&mut g, 10, expect.len());
    assert_eq!(got, expect, "Generator(PCG64(12345)).integers(0, 10)");
}

#[test]
fn generator_rejects_above_the_lemire_threshold() {
    // 1000003 is prime, so the rejection branch is actually reachable rather
    // than a power-of-two fast path.
    let expect = [
        813_897u64, 778_827, 174_203, 172_249, 180_901, 713_574, 102_547, 750_337,
    ];
    let mut g = numpy::Generator::new(999);
    let got = numpy::integers(&mut g, 1_000_003, expect.len());
    assert_eq!(got, expect, "Generator(PCG64(999)).integers(0, 1000003)");
}

#[test]
fn torch_randperm_matches() {
    let expect = [2usize, 6, 1, 8, 4, 5, 0, 9, 3, 7];
    assert_eq!(
        torch::randperm(10, 42),
        expect,
        "torch.randperm(10) @ seed 42"
    );
}

#[test]
fn torch_randperm_is_a_permutation_at_a_larger_n() {
    let expect = [
        15usize, 5, 19, 23, 1, 12, 0, 4, 6, 18, 3, 24, 17, 22, 9, 8, 16, 7, 20, 2, 21, 14, 11, 13,
        10,
    ];
    let got = torch::randperm(25, 7);
    assert_eq!(got, expect, "torch.randperm(25) @ seed 7");
    let mut sorted = got.clone();
    sorted.sort_unstable();
    assert_eq!(sorted, (0..25).collect::<Vec<_>>(), "not a permutation");
}

#[test]
fn the_two_numpy_generators_are_different_streams() {
    // Guards against someone "simplifying" one into the other: they share a
    // distribution but not a stream, and silently swapping them would change
    // every reproduced result while every statistical test still passed.
    let mut rs = numpy::RandomState::new(12345);
    let legacy: Vec<f64> = (0..4).map(|_| rs.random_double()).collect();
    let mut g = numpy::Generator::new(12345);
    let modern = numpy::integers(&mut g, 1u64 << 53, 4);
    let modern_f: Vec<f64> = modern
        .iter()
        .map(|v| *v as f64 / (1u64 << 53) as f64)
        .collect();
    assert!(
        legacy
            .iter()
            .zip(&modern_f)
            .any(|(a, b)| (a - b).abs() > 1e-9),
        "RandomState and Generator produced the same stream"
    );
}
