// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
// SPDX-License-Identifier: MIT OR Apache-2.0
//! Bit-exactness against the reference implementations.
//!
//! This crate's only reason to exist is producing the *same* stream numpy and
//! torch produce — an RNG that is merely well-distributed would be useless for
//! reproducing a published result. Every vector below was generated by running
//! the reference (numpy 2.4.3, torch 2.11.0) and pasting the output, so these
//! tests fail if the port drifts rather than if the distribution shifts.
//!
//! Generator script, for regenerating after a reference upgrade:
//! ```text
//! np.random.RandomState(12345).random_sample()      -> rs_double
//! np.random.RandomState(12345).normal(0, 1, 8)      -> rs_normal
//! np.random.Generator(np.random.PCG64(12345))       -> gen_*
//! np.random.SeedSequence(12345).generate_state(4)   -> seedseq
//! torch.manual_seed(42); torch.randperm(10)         -> randperm
//! np.random.Generator(np.random.PCG64(12345)).random(8)        -> gen_random
//! rs=np.random.RandomState(12345); [rs.choice(4,p=P4)]*12      -> choice_p_4
//! rs=np.random.RandomState(777);   [rs.choice(2,p=P2)]*12      -> choice_p_2
//! torch.manual_seed(42); torch.rand(5)                          -> torch_rand
//! torch.manual_seed(42); torch.rand(1); torch.randperm(6)       -> randperm_after_rand
//! ```

use rlx_rng::numpy;
use rlx_rng::torch;

/// numpy stores doubles to full precision; anything above f64 round-off here is
/// a port bug, not accumulation.
const EPS: f64 = 1e-15;

fn close(a: f64, b: f64) -> bool {
    (a - b).abs() <= EPS * b.abs().max(1.0)
}

#[test]
fn random_state_doubles_match_numpy() {
    let expect = [
        0.929_616_092_817_147_9,
        0.316_375_554_581_785_9,
        0.183_918_811_677_094_45,
        0.204_560_278_553_039_7,
        0.567_725_029_081_686_6,
        0.595_544_702_979_251_6,
    ];
    let mut rs = numpy::RandomState::new(12345);
    for (i, e) in expect.iter().enumerate() {
        let got = rs.random_double();
        assert!(close(got, *e), "draw {i}: {got:.17} != {e:.17}");
    }
}

#[test]
fn random_state_gaussian_matches_numpy() {
    // The polar method returns two variates per loop and numpy caches the
    // second. If the cache were dropped, draw 0 would still match and every
    // odd-indexed draw after it would not — which is why this checks eight.
    let expect = [
        -0.204_707_659_484_712_95,
        0.478_943_338_057_548_24,
        -0.519_438_715_056_738_1,
        -0.555_730_304_347_49,
        1.965_780_572_502_714_2,
        1.393_405_832_972_990_4,
        0.092_907_876_743_717_67,
        0.281_746_152_830_202_5,
    ];
    let mut rs = numpy::RandomState::new(12345);
    let got = rs.normal(0.0, 1.0, expect.len());
    for (i, (g, e)) in got.iter().zip(&expect).enumerate() {
        assert!(close(*g, *e), "draw {i}: {g:.17} != {e:.17}");
    }
}

#[test]
fn random_state_honours_loc_and_scale() {
    let expect = [
        3.767_894_277_850_267,
        2.150_546_972_094_375_5,
        2.524_615_122_758_938_4,
        2.805_637_212_247_381,
        1.908_307_728_530_696,
    ];
    let mut rs = numpy::RandomState::new(7);
    let got = rs.normal(2.5, 0.75, expect.len());
    for (i, (g, e)) in got.iter().zip(&expect).enumerate() {
        assert!(close(*g, *e), "draw {i}: {g:.17} != {e:.17}");
    }
}

#[test]
fn gaussian_random_matrix_matches_sklearn() {
    // sklearn's GaussianRandomProjection draws N(0, 1/k) row-major.
    let expect = [
        0.248_357_076_505_616_34,
        -0.069_132_150_585_592_33,
        0.323_844_269_050_346_25,
        0.761_514_928_204_012_7,
        -0.117_076_687_361_667_99,
        -0.117_068_478_474_590_27,
        0.789_606_407_753_695_7,
        0.383_717_364_576_454_4,
        -0.234_737_192_967_476_05,
        0.271_280_021_792_982_33,
        -0.231_708_846_406_231_13,
        -0.232_864_876_785_128_43,
        0.120_981_135_783_017_06,
        -0.956_640_122_328_899,
        -0.862_458_916_256_516_4,
        -0.281_143_764_620_486_35,
        -0.506_415_560_167_211_9,
        0.157_123_666_297_636_94,
        -0.454_012_037_760_605_56,
        -0.706_151_850_667_645_9,
        0.732_824_384_460_777,
        -0.112_888_150_243_267_83,
        0.033_764_102_343_961_92,
        -0.712_374_093_106_728_4,
    ];
    let got = numpy::gaussian_random_matrix(4, 6, 42);
    assert_eq!(got.len(), expect.len());
    for (i, (g, e)) in got.iter().zip(&expect).enumerate() {
        assert!(close(*g, *e), "entry {i}: {g:.17} != {e:.17}");
    }
}

#[test]
fn seed_sequence_matches_numpy() {
    let expect = [
        2_688_385_916u32,
        3_048_105_090,
        4_196_366_895,
        3_152_189_807,
    ];
    let got = numpy::SeedSequence::new(12345).generate_state(4);
    assert_eq!(got, expect, "SeedSequence(12345).generate_state(4)");
}

#[test]
fn generator_wide_integers_match_numpy() {
    let expect = [
        2_096_804_712_593_481_934u64,
        2_921_580_012_919_480_943,
        7_354_398_262_316_660_716,
        6_237_348_419_996_972_168,
        3_607_348_892_368_485_766,
        3_069_666_675_758_614_433,
    ];
    let mut g = numpy::Generator::new(12345);
    let got = numpy::integers(&mut g, 1u64 << 63, expect.len());
    assert_eq!(got, expect, "Generator(PCG64(12345)).integers(0, 2**63)");
}

#[test]
fn generator_small_range_takes_the_32_bit_path() {
    // `high` under 2^32 makes numpy's Lemire bounded sampler dispatch to its
    // 32-bit variant, which buffers the unused high half of each 64-bit draw.
    // A port that always uses the 64-bit path is still uniform and still wrong.
    let expect = [6u64, 2, 7, 3, 2, 7, 6, 6, 9, 3, 8, 3];
    let mut g = numpy::Generator::new(12345);
    let got = numpy::integers(&mut g, 10, expect.len());
    assert_eq!(got, expect, "Generator(PCG64(12345)).integers(0, 10)");
}

#[test]
fn generator_rejects_above_the_lemire_threshold() {
    // 1000003 is prime, so the rejection branch is actually reachable rather
    // than a power-of-two fast path.
    let expect = [
        813_897u64, 778_827, 174_203, 172_249, 180_901, 713_574, 102_547, 750_337,
    ];
    let mut g = numpy::Generator::new(999);
    let got = numpy::integers(&mut g, 1_000_003, expect.len());
    assert_eq!(got, expect, "Generator(PCG64(999)).integers(0, 1000003)");
}

#[test]
fn torch_randperm_matches() {
    let expect = [2usize, 6, 1, 8, 4, 5, 0, 9, 3, 7];
    assert_eq!(
        torch::randperm(10, 42),
        expect,
        "torch.randperm(10) @ seed 42"
    );
}

#[test]
fn torch_randperm_is_a_permutation_at_a_larger_n() {
    let expect = [
        15usize, 5, 19, 23, 1, 12, 0, 4, 6, 18, 3, 24, 17, 22, 9, 8, 16, 7, 20, 2, 21, 14, 11, 13,
        10,
    ];
    let got = torch::randperm(25, 7);
    assert_eq!(got, expect, "torch.randperm(25) @ seed 7");
    let mut sorted = got.clone();
    sorted.sort_unstable();
    assert_eq!(sorted, (0..25).collect::<Vec<_>>(), "not a permutation");
}

#[test]
fn the_two_numpy_generators_are_different_streams() {
    // Guards against someone "simplifying" one into the other: they share a
    // distribution but not a stream, and silently swapping them would change
    // every reproduced result while every statistical test still passed.
    let mut rs = numpy::RandomState::new(12345);
    let legacy: Vec<f64> = (0..4).map(|_| rs.random_double()).collect();
    let mut g = numpy::Generator::new(12345);
    let modern = numpy::integers(&mut g, 1u64 << 53, 4);
    let modern_f: Vec<f64> = modern
        .iter()
        .map(|v| *v as f64 / (1u64 << 53) as f64)
        .collect();
    assert!(
        legacy
            .iter()
            .zip(&modern_f)
            .any(|(a, b)| (a - b).abs() > 1e-9),
        "RandomState and Generator produced the same stream"
    );
}

#[test]
fn generator_random_matches_numpy() {
    // `Generator.random()` is `(next_u64() >> 11) * 2^-53` — the top 53 bits of
    // ONE 64-bit draw. `RandomState::random_double` assembles 53 bits from TWO
    // 32-bit draws instead; the two are not interchangeable.
    let expect = [
        0.22733602246716966,
        0.31675833970975287,
        0.7973654573327341,
        0.6762546707509746,
        0.391109550601909,
        0.33281392786638453,
        0.5983087535871898,
        0.18673418560371335,
    ];
    let mut g = numpy::Generator::new(12345);
    for (i, e) in expect.iter().enumerate() {
        let got = g.random();
        assert!(close(got, *e), "gen.random()[{i}]: {got} != {e}");
    }
}

#[test]
fn generator_uniform_is_bit_identical_to_random() {
    // numpy's `random_uniform(state, off, rng)` is `off + rng * next_double`, so
    // the default range makes `uniform()` the same VALUE and the same stream
    // position as `random()`. Verified against numpy 2.4.3 rather than assumed —
    // if a future numpy adds an offset step, this is where it surfaces.
    let mut a = numpy::Generator::new(12345);
    let mut b = numpy::Generator::new(12345);
    for i in 0..8 {
        let (x, y) = (a.random(), b.uniform());
        assert_eq!(x.to_bits(), y.to_bits(), "uniform() != random() at {i}");
    }
}

#[test]
fn default_rng_seeding_matches_generator() {
    // `np.random.default_rng(s)` is `Generator(PCG64(s))` — the same SeedSequence
    // path. torch_brain's `TriangleDistribution` uses `default_rng`, so this is
    // the edge its parity rests on.
    let mut g = numpy::Generator::new(12345);
    assert!(
        close(g.random(), 0.22733602246716966),
        "default_rng(12345) first draw"
    );
}

#[test]
fn legacy_choice_p_matches_numpy() {
    // ONE `random_sample()` per call and `searchsorted(cdf, u, side='right')`.
    // A rejection loop would also be a valid weighted sampler and would consume
    // the stream differently, desynchronising everything after it.
    let p4 = [0.1, 0.2, 0.3, 0.4];
    let expect4 = [3usize, 2, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3];
    let mut rs = numpy::RandomState::new(12345);
    for (i, e) in expect4.iter().enumerate() {
        assert_eq!(rs.choice_p(&p4), *e, "choice(4, p) draw {i}");
    }

    // Unnormalised weights: numpy divides by `cdf[-1]`, so [1, 3] == [0.25, 0.75].
    let p2 = [1.0, 3.0];
    let expect2 = [0usize, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0];
    let mut rs2 = numpy::RandomState::new(777);
    for (i, e) in expect2.iter().enumerate() {
        assert_eq!(rs2.choice_p(&p2), *e, "choice(2, unnormalised p) draw {i}");
    }
}

#[test]
fn choice_p_consumes_exactly_one_draw() {
    // The stream position after one choice_p must equal the position after one
    // random_sample. If this fails, every draw downstream of a RandomChoice
    // diverges from the reference even though the choices themselves look right.
    let p = [0.3, 0.7];
    let mut a = numpy::RandomState::new(99);
    a.choice_p(&p);
    let after_choice = a.random_double();

    let mut b = numpy::RandomState::new(99);
    b.random_sample();
    let after_sample = b.random_double();

    assert_eq!(after_choice.to_bits(), after_sample.to_bits());
}

#[test]
fn choice_p_edges() {
    let mut rs = numpy::RandomState::new(1);
    assert_eq!(rs.choice_p(&[]), 0, "empty p");
    assert_eq!(rs.choice_p(&[1.0]), 0, "single outcome");
    // A zero-weight outcome must never be selected: its cdf entry equals the
    // previous one, so no `u` can land strictly between them.
    let p = [0.5, 0.0, 0.5];
    let mut rs2 = numpy::RandomState::new(4);
    for _ in 0..200 {
        assert_ne!(rs2.choice_p(&p), 1, "zero-weight outcome was chosen");
    }
}

#[test]
fn torch_rand_is_a_float32_draw() {
    // `torch.rand` defaults to float32: 24 bits out of one 32-bit word, scaled by
    // 2^-24. Reading the call site as an f64 draw would give plausible values that
    // diverge from torch immediately — `torch.rand(1, dtype=torch.float64)` at the
    // same seed is 0.05815448596142969, nothing like the first value below.
    let expect: [f64; 5] = [
        0.8822692632675171,
        0.9150039553642273,
        0.38286375999450684,
        0.9593056440353394,
        0.3904482126235962,
    ];
    let mut g = torch::RandomState::new(42);
    for (i, e) in expect.iter().enumerate() {
        let got = g.rand();
        assert_eq!(
            got.to_bits(),
            e.to_bits(),
            "torch.rand()[{i}]: {got} != {e}"
        );
    }
}

#[test]
fn torch_randperm_continues_a_shared_generator() {
    // A sampler that draws a jitter with `rand` and then shuffles with `randperm`
    // passes ONE generator to both, so the shuffle must continue the stream.
    // Restarting from the seed is a different permutation — the two are recorded
    // here so the distinction cannot be lost.
    let mut g = torch::RandomState::new(42);
    let _jitter = g.rand();
    assert_eq!(
        g.randperm(6),
        vec![5, 2, 4, 3, 0, 1],
        "randperm continuing the stream after one rand"
    );
    assert_eq!(
        torch::randperm(6, 42),
        vec![0, 3, 2, 4, 1, 5],
        "randperm from a fresh seed — different, as it must be"
    );
}

#[test]
fn the_free_randperm_still_matches_the_method() {
    for n in [0usize, 1, 2, 7, 25] {
        let mut g = torch::RandomState::new(3);
        assert_eq!(torch::randperm(n, 3), g.randperm(n), "n = {n}");
    }
}
