// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Write a [`SeqModel`] out as SystemVerilog plus memory images.
//!
//! The datapath and the activation LUT are fixed RTL shipped with the crate;
//! everything model-specific is a generated header or a `.mem` file, so
//! re-exporting a retrained network touches no hand-written Verilog.

use std::fs;
use std::path::Path;

use super::{Descriptor, SeqModel};

/// The engine and LUT are the same for every graph.
const CORE_SV: &str = include_str!("../../rtl/seq/tv_core.sv");
const LUT_SV: &str = include_str!("../../rtl/seq/tv_lut.sv");

fn hex16(v: i16) -> String {
    format!("{:04x}\n", v as u16)
}

/// Pack a LUT as `{value, delta-to-next}` so interpolation is one read. The
/// final entry's delta is zero, so a saturated index returns the endpoint.
fn pack_lut(tab: &[i16]) -> String {
    let mut out = String::with_capacity(tab.len() * 9);
    for (i, &v) in tab.iter().enumerate() {
        let d = tab.get(i + 1).map_or(0i16, |&nx| nx.wrapping_sub(v));
        out.push_str(&format!("{:04x}{:04x}\n", v as u16, d as u16));
    }
    out
}

fn lut_table(n: usize, hi: f32, f: impl Fn(f64) -> f64) -> Vec<i16> {
    (0..=n)
        .map(|i| {
            let x = f64::from(hi) * i as f64 / n as f64;
            (f(x) * 32768.0).round().min(32767.0) as i16
        })
        .collect()
}

pub fn emit(model: &SeqModel, out_dir: &Path) -> Result<Vec<String>, String> {
    fs::create_dir_all(out_dir).map_err(|e| format!("rlx-fpga/seq: {out_dir:?}: {e}"))?;
    let cfg = &model.cfg;
    let mut files = Vec::new();

    let mut write = |name: &str, body: &str| -> Result<(), String> {
        fs::write(out_dir.join(name), body).map_err(|e| format!("rlx-fpga/seq: {name}: {e}"))?;
        files.push(name.to_string());
        Ok(())
    };

    write(
        "weights.mem",
        &model.weights.iter().copied().map(hex16).collect::<String>(),
    )?;
    let offs = if model.offsets.is_empty() {
        "0000\n".to_string()
    } else {
        model
            .offsets
            .iter()
            .map(|&v| format!("{v:04x}\n"))
            .collect()
    };
    write("offsets.mem", &offs)?;

    let sig = lut_table(cfg.lut_n, cfg.lut_hi, |x| 1.0 / (1.0 + (-x).exp()));
    let tanh = lut_table(cfg.lut_n, cfg.lut_hi, f64::tanh);
    write("sigmoid.mem", &pack_lut(&sig))?;
    write("tanh.mem", &pack_lut(&tanh))?;

    let field_w = model
        .descriptors
        .iter()
        .flat_map(|d| Descriptor::FIELDS.iter().map(move |f| d.field(f)))
        .map(|v| 32 - v.leading_zeros())
        .max()
        .unwrap_or(16)
        .max(16);

    let defs = format!(
        "// @generated by rlx-fpga (seq target) -- do not edit by hand.\n\
         `ifndef TV_DEFS_SVH\n`define TV_DEFS_SVH\n\n\
         `define TV_ARAM      {aram}      // activation words\n\
         `define TV_WRAM      {wram}      // int16 weights\n\
         `define TV_OFFN      {offn}\n\
         `define TV_UCODE_N   {ucode}\n\
         `define TV_ACT_FRAC  {af}\n\
         `define TV_LUT_N     {lutn}\n\
         `define TV_LUT_SHIFT {lsh}\n\
         `define TV_FEAT_BASE {fb}\n\
         `define TV_FEAT_N    {fn_}\n\
         `define TV_PROB_ADDR {pa}\n\
         `define TV_HIDDEN    {hid}\n\
         `define TV_ACC_W     48\n\
         `define TV_FIELD_W   {fw}\n\n\
         `define TV_OP_MATVEC 0\n`define TV_OP_POOL   1\n\
         `define TV_OP_GATE   2\n`define TV_OP_DONE   3\n\
         `define TV_ACT_NONE  0\n`define TV_ACT_RELU  1\n`define TV_ACT_SIG   2\n\n\
         `endif\n",
        // Size the RAM to what the graph reaches, not to the budget: a
        // liveness-allocated graph often needs a fraction of it, and the
        // difference is BRAM blocks.
        aram = model.aram_used.max(1).next_power_of_two(),
        wram = model.weights.len().max(1),
        offn = model.offsets.len().max(1),
        ucode = model.descriptors.len(),
        af = cfg.act_frac,
        lutn = cfg.lut_n,
        lsh = cfg.lut_shift(),
        fb = model.feat_base,
        fn_ = model.feat_len,
        pa = model.prob_addr,
        hid = model
            .descriptors
            .iter()
            .find(|d| d.op == super::SeqOp::Gate as u32)
            .map_or(0, |d| d.n_i),
        fw = field_w,
    );
    write("tv_defs.svh", &defs)?;

    let mut u = String::from(
        "// @generated by rlx-fpga (seq target) -- do not edit by hand.\n\
         // One descriptor per network stage, in execution order.\ncase (pc)\n",
    );
    for (i, d) in model.descriptors.iter().enumerate() {
        let label = model.labels.get(i).map_or("", String::as_str);
        u.push_str(&format!("  {i}: begin // {label}\n"));
        for f in Descriptor::FIELDS {
            u.push_str(&format!("    {f} = {};\n", d.field(f)));
        }
        u.push_str("  end\n");
    }
    u.push_str("  default: begin\n");
    for f in Descriptor::FIELDS {
        u.push_str(&format!("    {f} = 0;\n"));
    }
    u.push_str("  end\nendcase\n");
    write("tv_ucode.svh", &u)?;

    write("tv_core.sv", CORE_SV)?;
    write("tv_lut.sv", LUT_SV)?;
    Ok(files)
}
