// AUTO-GENERATED by rlx-torch-import (flow style).
use rlx_flow::MapWeights;
use std::path::Path;

/// Load `weights.safetensors` into an in-memory `MapWeights` (WeightSource).
pub fn load_weights(dir: &Path) -> anyhow::Result<MapWeights> {
    let bytes = std::fs::read(dir.join("weights.safetensors"))?;
    let mut mw = MapWeights::default();
    if !bytes.is_empty() {
        let st = safetensors::SafeTensors::deserialize(&bytes)?;
        for name in st.names() {
            let v = st.tensor(name)?;
            let shape: Vec<usize> = v.shape().to_vec();
            let raw = v.data();
            let data: Vec<f32> = match v.dtype() {
                safetensors::Dtype::F32 => raw.chunks_exact(4).map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]])).collect(),
                safetensors::Dtype::F16 => raw.chunks_exact(2).map(|c| half::f16::from_le_bytes([c[0], c[1]]).to_f32()).collect(),
                safetensors::Dtype::BF16 => raw.chunks_exact(2).map(|c| half::bf16::from_le_bytes([c[0], c[1]]).to_f32()).collect(),
                safetensors::Dtype::F64 => raw.chunks_exact(8).map(|c| f64::from_le_bytes(c.try_into().unwrap()) as f32).collect(),
                safetensors::Dtype::I64 => raw.chunks_exact(8).map(|c| i64::from_le_bytes(c.try_into().unwrap()) as f32).collect(),
                other => anyhow::bail!("unsupported weight dtype {other:?}"),
            };
            mw.insert(name.to_string(), data, shape);
        }
    }
    Ok(mw)
}
