// AUTO-GENERATED by rlx-torch-import (flow style) — do not edit by hand.
#![allow(nonstandard_style, unused_imports, unused_mut, unused_variables, dead_code, clippy::all)]

use rlx_flow::{ModelFlow, FlowStage};
use rlx_flow::blocks::CustomStage;
use rlx_ir::HirGraphExt;
use rlx_ir::op::{Activation, MaskKind};

fn rlx_torch_fill(value: f64, dtype: rlx_ir::DType, numel: usize) -> Vec<u8> {
    let one: Vec<u8> = match dtype {
        rlx_ir::DType::F32 => (value as f32).to_le_bytes().to_vec(),
        rlx_ir::DType::F64 => value.to_le_bytes().to_vec(),
        rlx_ir::DType::I64 => (value as i64).to_le_bytes().to_vec(),
        rlx_ir::DType::I32 => (value as i32).to_le_bytes().to_vec(),
        _ => vec![],
    };
    let mut out = Vec::with_capacity(one.len() * numel);
    for _ in 0..numel { out.extend_from_slice(&one); }
    out
}

/// Build a `ModelFlow`; params are pulled from the `WeightSource` at build time.
pub fn build_flow() -> ModelFlow {
    ModelFlow::new("mnist")
        .input("x", rlx_ir::Shape::new(&[4, 1, 28, 28], rlx_ir::DType::F32))
        .stage(FlowStage::Custom(CustomStage::new(|emit, _input| {
            let t_x = emit.flow_input("x")?.hir_id();
            let t_p_c1_weight = emit.load_param("c1.weight", false)?;
            let t_p_c1_bias = emit.load_param("c1.bias", false)?;
            let t_p_c2_weight = emit.load_param("c2.weight", false)?;
            let t_p_c2_bias = emit.load_param("c2.bias", false)?;
            let t_p_fc_weight = emit.load_param("fc.weight", false)?;
            let t_p_fc_bias = emit.load_param("fc.bias", false)?;
            let mut b = rlx_ir::hir::HirMut::new(emit.hir());
    let t_convolution__conv = b.conv2d(t_x, t_p_c1_weight, [3, 3], [1, 1], [1, 1], 1, rlx_ir::Shape::new(&[4, 8, 28, 28], rlx_ir::DType::F32));
    let t_convolution__bias = b.reshape_(t_p_c1_bias, vec![1i64, 8i64, 1i64, 1i64]);
    // aten.convolution.default  (x[4, 1, 28, 28], p_c1_weight[8, 1, 3, 3], p_c1_bias[8]) -> [4, 8, 28, 28] f32
    let t_convolution = b.add(t_convolution__conv, t_convolution__bias);
    // aten.relu.default  (convolution[4, 8, 28, 28]) -> [4, 8, 28, 28] f32
    let s_t_relu = b.shape(t_convolution).clone();
    let t_relu = b.activation(Activation::Relu, t_convolution, s_t_relu);
    // aten.max_pool2d_with_indices.default  (relu[4, 8, 28, 28]) -> [4, 8, 14, 14] f32
    let t_max_pool2d_with_indices = b.add_node(rlx_ir::Op::Pool { kind: rlx_ir::op::ReduceOp::Max, kernel_size: vec![2usize, 2usize], stride: vec![2usize, 2usize], padding: vec![0usize, 0usize] }, vec![t_relu], rlx_ir::Shape::new(&[4, 8, 14, 14], rlx_ir::DType::F32));
    let t_convolution_1__conv = b.conv2d(t_max_pool2d_with_indices, t_p_c2_weight, [3, 3], [1, 1], [1, 1], 1, rlx_ir::Shape::new(&[4, 16, 14, 14], rlx_ir::DType::F32));
    let t_convolution_1__bias = b.reshape_(t_p_c2_bias, vec![1i64, 16i64, 1i64, 1i64]);
    // aten.convolution.default  (getitem[4, 8, 14, 14], p_c2_weight[16, 8, 3, 3], p_c2_bias[16]) -> [4, 16, 14, 14] f32
    let t_convolution_1 = b.add(t_convolution_1__conv, t_convolution_1__bias);
    // aten.relu.default  (convolution_1[4, 16, 14, 14]) -> [4, 16, 14, 14] f32
    let s_t_relu_1 = b.shape(t_convolution_1).clone();
    let t_relu_1 = b.activation(Activation::Relu, t_convolution_1, s_t_relu_1);
    // aten.max_pool2d_with_indices.default  (relu_1[4, 16, 14, 14]) -> [4, 16, 7, 7] f32
    let t_max_pool2d_with_indices_1 = b.add_node(rlx_ir::Op::Pool { kind: rlx_ir::op::ReduceOp::Max, kernel_size: vec![2usize, 2usize], stride: vec![2usize, 2usize], padding: vec![0usize, 0usize] }, vec![t_relu_1], rlx_ir::Shape::new(&[4, 16, 7, 7], rlx_ir::DType::F32));
    // aten.mean.dim  (getitem_2[4, 16, 7, 7]) -> [4, 16, 1, 1] f32
    let t_mean = b.mean(t_max_pool2d_with_indices_1, vec![3usize, 2usize], true);
    // aten.view.default  (mean[4, 16, 1, 1]) -> [4, 16] f32
    let t_view = b.reshape_(t_mean, vec![4i64, 16i64]);
    // aten.permute.default  (p_fc_weight[10, 16]) -> [16, 10] f32
    let t_permute = b.transpose_(t_p_fc_weight, vec![1usize, 0usize]);
    let t_addmm__mm = b.mm(t_view, t_permute);
    // aten.addmm.default  (p_fc_bias[10], view[4, 16], permute[16, 10]) -> [4, 10] f32
    let t_addmm = b.add(t_addmm__mm, t_p_fc_bias);
            let out_shape = b.shape(t_addmm).clone();
            drop(b);
            Ok(Some(emit.wrap(t_addmm, out_shape)))
        })))
        .output("output")
}
