// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Emit the artifact set for a [`Model`]: `layout.csl`, `pe_program.csl`,
//! `run.py`, and `commands_wse{2,3}.sh`.
//!
//! Milestone 1: a single rank-2 matmul on one PE. Host data (`X`, `W`) is
//! streamed in and `Y` read back via the `memcpy` library — the structure of
//! the SDK's `gemv-03-memcpy` tutorial, parameterized by `M`/`K`/`N`. The
//! compute kernel is plain scalar loops (correctness first; the DSD/`@fmacs`
//! vectorization and multi-PE tiling come later — see the crate docs).

use std::path::Path;

use crate::csl::Csl;
use crate::model::{Layer, Model};

/// One emitted file: its relative path and its full contents.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Artifact {
    pub path: String,
    pub contents: String,
}

/// Single-PE memory budget note: a WSE PE has ~48 kB of local memory, so
/// `(M*K + K*N + M*N) * 4` bytes must fit comfortably. This is a guideline,
/// not a hard check — `cslc` is the authority — but it's why single-PE dims
/// stay small until multi-PE tiling lands.
const PE_MEM_BYTES: usize = 48 * 1024;

/// Build every artifact for `model` in memory (no filesystem I/O).
pub fn collect_artifacts(model: &Model) -> Result<Vec<Artifact>, String> {
    let layer = match model.layers.as_slice() {
        [single] => single,
        other => {
            return Err(format!(
                "rlx-cerebras milestone 1 emits exactly one layer; model has {}",
                other.len()
            ));
        }
    };
    let Layer::MatMul { m, k, n, .. } = layer;
    let (m, k, n) = (*m, *k, *n);

    let footprint = (m * k + k * n + m * n) * 4;
    if footprint > PE_MEM_BYTES {
        return Err(format!(
            "single-PE footprint {footprint} B exceeds ~{PE_MEM_BYTES} B PE memory \
             for M={m} K={k} N={n}; multi-PE tiling (next milestone) is required"
        ));
    }

    Ok(vec![
        Artifact {
            path: "layout.csl".to_string(),
            contents: emit_layout(),
        },
        Artifact {
            path: "pe_program.csl".to_string(),
            contents: emit_pe_program(m, k, n),
        },
        Artifact {
            path: "run.py".to_string(),
            contents: emit_run_py(m, k, n),
        },
        Artifact {
            path: "commands_wse2.sh".to_string(),
            contents: emit_commands("wse2"),
        },
        Artifact {
            path: "commands_wse3.sh".to_string(),
            contents: emit_commands("wse3"),
        },
    ])
}

/// Emit all artifacts for `model` into `out_dir` (created if absent).
pub fn emit_model(model: &Model, out_dir: &Path) -> std::io::Result<()> {
    let artifacts = collect_artifacts(model).map_err(std::io::Error::other)?;
    std::fs::create_dir_all(out_dir)?;
    for a in &artifacts {
        std::fs::write(out_dir.join(&a.path), &a.contents)?;
    }
    Ok(())
}

/// `layout.csl` — places a 1×1 rectangle, points it at `pe_program.csl`, and
/// advertises the host-visible symbols. `true` marks a host-writable input.
fn emit_layout() -> String {
    let mut c = Csl::new();
    c.comment("Generated by rlx-cerebras. Single-PE matmul layout.");
    c.blank();
    c.line("const memcpy = @import_module(\"<memcpy/get_params>\", .{ .width = 1, .height = 1 });");
    c.blank();
    c.line("layout {");
    c.block(|c| {
        c.line("@set_rectangle(1, 1);");
        c.line(
            "@set_tile_code(0, 0, \"pe_program.csl\", .{ .memcpy_params = memcpy.get_params(0) });",
        );
        c.blank();
        c.line("@export_name(\"X\", [*]f32, true);");
        c.line("@export_name(\"W\", [*]f32, true);");
        c.line("@export_name(\"Y\", [*]f32, false);");
        c.line("@export_name(\"init_and_compute\", fn()void);");
    });
    c.line("}");
    c.into_string()
}

/// `pe_program.csl` — device tensors, the scalar matmul, host launch entry.
fn emit_pe_program(m: usize, k: usize, n: usize) -> String {
    let mut c = Csl::new();
    c.comment("Generated by rlx-cerebras. Y[M,N] = X[M,K] * W[K,N], row-major f32.");
    c.comment("Scalar kernel (single PE) — correctness reference; vectorize + tile next.");
    c.blank();
    c.line("param memcpy_params;");
    c.blank();
    c.line("const sys_mod = @import_module(\"<memcpy/memcpy>\", memcpy_params);");
    c.blank();
    c.line(&format!("const M: i16 = {m};"));
    c.line(&format!("const K: i16 = {k};"));
    c.line(&format!("const N: i16 = {n};"));
    c.blank();
    c.line("var X: [M*K]f32;");
    c.line("var W: [K*N]f32;");
    c.line("var Y = @zeros([M*N]f32);");
    c.blank();
    c.line("var X_ptr: [*]f32 = &X;");
    c.line("var W_ptr: [*]f32 = &W;");
    c.line("const Y_ptr: [*]f32 = &Y;");
    c.blank();
    c.func("matmul", |c| {
        c.line("for (@range(i16, M)) |i| {");
        c.block(|c| {
            c.line("for (@range(i16, N)) |j| {");
            c.block(|c| {
                c.line("var acc: f32 = 0.0;");
                c.line("for (@range(i16, K)) |k| {");
                c.block(|c| {
                    c.line("acc = acc + X[i*K + k] * W[k*N + j];");
                });
                c.line("}");
                c.line("Y[i*N + j] = acc;");
            });
            c.line("}");
        });
        c.line("}");
    });
    c.func("init_and_compute", |c| {
        c.line("matmul();");
        c.line("sys_mod.unblock_cmd_stream();");
    });
    c.comptime(|c| {
        c.line("@export_symbol(X_ptr, \"X\");");
        c.line("@export_symbol(W_ptr, \"W\");");
        c.line("@export_symbol(Y_ptr, \"Y\");");
        c.line("@export_symbol(init_and_compute);");
    });
    c.into_string()
}

/// `run.py` — the `cs_python` host harness: stream `X`/`W` in, launch, read
/// `Y` back, and check against numpy. Validates on the fabric simulator.
fn emit_run_py(m: usize, k: usize, n: usize) -> String {
    format!(
        r#"#!/usr/bin/env cs_python
# Generated by rlx-cerebras. Drives the Cerebras SDK fabric simulator.

import argparse
import numpy as np

from cerebras.sdk.runtime.sdkruntimepybind import SdkRuntime, MemcpyDataType, MemcpyOrder

parser = argparse.ArgumentParser()
parser.add_argument('--name', help="the test compile output dir")
parser.add_argument('--cmaddr', help="IP:port for CS system")
args = parser.parse_args()

M = {m}
K = {k}
N = {n}

rng = np.random.default_rng(0)
X = rng.standard_normal((M, K)).astype(np.float32)
W = rng.standard_normal((K, N)).astype(np.float32)
Y_expected = X @ W

runner = SdkRuntime(args.name, cmaddr=args.cmaddr)
X_symbol = runner.get_id('X')
W_symbol = runner.get_id('W')
Y_symbol = runner.get_id('Y')

runner.load()
runner.run()

runner.memcpy_h2d(X_symbol, X.reshape(-1), 0, 0, 1, 1, M * K, streaming=False,
  order=MemcpyOrder.ROW_MAJOR, data_type=MemcpyDataType.MEMCPY_32BIT, nonblock=False)
runner.memcpy_h2d(W_symbol, W.reshape(-1), 0, 0, 1, 1, K * N, streaming=False,
  order=MemcpyOrder.ROW_MAJOR, data_type=MemcpyDataType.MEMCPY_32BIT, nonblock=False)

runner.launch('init_and_compute', nonblock=False)

Y_result = np.zeros(M * N, dtype=np.float32)
runner.memcpy_d2h(Y_result, Y_symbol, 0, 0, 1, 1, M * N, streaming=False,
  order=MemcpyOrder.ROW_MAJOR, data_type=MemcpyDataType.MEMCPY_32BIT, nonblock=False)

runner.stop()

Y_result = Y_result.reshape(M, N)
np.testing.assert_allclose(Y_result, Y_expected, atol=1e-3, rtol=1e-3)
print("SUCCESS!")
"#
    )
}

/// `commands_<arch>.sh` — compile with `cslc --memcpy`, then run the harness.
/// Fabric dims/offsets match the single-PE tutorials; offsets leave room for
/// the memcpy infrastructure PEs around the 1×1 compute rectangle.
fn emit_commands(arch: &str) -> String {
    format!(
        "#!/usr/bin/env bash\n\
         set -e\n\
         cslc --arch={arch} ./layout.csl --fabric-dims=8,3 \\\n\
         --fabric-offsets=4,1 -o out --memcpy --channels 1\n\
         cs_python run.py --name out\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn artifact<'a>(arts: &'a [Artifact], path: &str) -> &'a str {
        &arts
            .iter()
            .find(|a| a.path == path)
            .expect("artifact present")
            .contents
    }

    #[test]
    fn emits_full_artifact_set() {
        let model = Model::single_matmul("mm", 3, 5, 7);
        let arts = collect_artifacts(&model).unwrap();
        let paths: Vec<&str> = arts.iter().map(|a| a.path.as_str()).collect();
        assert_eq!(
            paths,
            [
                "layout.csl",
                "pe_program.csl",
                "run.py",
                "commands_wse2.sh",
                "commands_wse3.sh"
            ]
        );
    }

    #[test]
    fn pe_program_carries_dims_and_exports() {
        let model = Model::single_matmul("mm", 3, 5, 7);
        let arts = collect_artifacts(&model).unwrap();
        let pe = artifact(&arts, "pe_program.csl");
        assert!(pe.contains("const M: i16 = 3;"));
        assert!(pe.contains("const K: i16 = 5;"));
        assert!(pe.contains("const N: i16 = 7;"));
        assert!(pe.contains("acc = acc + X[i*K + k] * W[k*N + j];"));
        assert!(pe.contains("@export_symbol(Y_ptr, \"Y\");"));
        assert!(pe.contains("sys_mod.unblock_cmd_stream();"));
    }

    #[test]
    fn layout_places_single_pe() {
        let model = Model::single_matmul("mm", 2, 2, 2);
        let arts = collect_artifacts(&model).unwrap();
        let layout = artifact(&arts, "layout.csl");
        assert!(layout.contains("@set_rectangle(1, 1);"));
        assert!(layout.contains("@set_tile_code(0, 0, \"pe_program.csl\""));
        assert!(layout.contains("@export_name(\"X\", [*]f32, true);"));
    }

    #[test]
    fn run_py_uses_dims_and_checks() {
        let model = Model::single_matmul("mm", 4, 6, 8);
        let arts = collect_artifacts(&model).unwrap();
        let run = artifact(&arts, "run.py");
        assert!(run.contains("M = 4"));
        assert!(run.contains("K = 6"));
        assert!(run.contains("N = 8"));
        assert!(run.contains("Y_expected = X @ W"));
        assert!(run.contains("np.testing.assert_allclose"));
    }

    #[test]
    fn rejects_oversized_single_pe() {
        // 512*512 f32 operands blow past one PE's ~48 kB.
        let model = Model::single_matmul("big", 512, 512, 512);
        assert!(collect_artifacts(&model).is_err());
    }

    #[test]
    fn emit_model_writes_files() {
        let dir = tempfile::tempdir().unwrap();
        let model = Model::single_matmul("mm", 2, 3, 4);
        emit_model(&model, dir.path()).unwrap();
        for f in ["layout.csl", "pe_program.csl", "run.py", "commands_wse2.sh"] {
            assert!(dir.path().join(f).exists(), "{f} written");
        }
    }
}
