// SPDX-License-Identifier: MIT OR Apache-2.0
//! Native RLX model `mlp` — generated by `rlx-torch-import` (tensor style).
#![allow(nonstandard_style, unused_imports, clippy::all)]

pub mod graph;
pub mod weights;

pub use weights::{load_weights, LoadedWeights};

/// Compile the model on `device`, binding weights from `dir/weights.safetensors`.
pub fn compile(
    device: rlx_runtime::Device,
    dir: &std::path::Path,
) -> anyhow::Result<rlx_runtime::CompiledGraph> {
    let w = load_weights(dir)?;
    let g = graph::build_graph();
    let mut compiled = rlx_runtime::Session::new(device).compile(g);
    for key in graph::PARAM_KEYS {
        compiled.set_param(key, &w.get(key)?);
    }
    for (key, numel) in graph::ZERO_PARAMS {
        compiled.set_param(key, &vec![0.0f32; *numel]);
    }
    Ok(compiled)
}
