// AUTO-GENERATED by rlx-torch-import — do not edit by hand.
//
// Provenance: this RLX graph was imported from a PyTorch `torch.export`
// graph. Each op below is annotated with its original aten op + shapes so
// the source model can be traced / reconstructed.
//
// Original aten op histogram:
//     17  aten.view.default
//     12  aten.permute.default
//      7  aten.addmm.default
//      2  aten.add.Tensor
//      2  aten.layer_norm.default
//      1  aten.convolution.default
//      1  aten.gelu.default
//      1  aten.mean.dim
//      1  aten.scaled_dot_product_attention.default

use std::collections::HashMap;
use rlx_ir::hir::{HirMut, HirNodeId};
use rlx_ir::op::{Activation, BinaryOp, MaskKind, ReduceOp};
use rlx_ir::{HirGraphExt, HirModule};

use crate::weights::LoadedWeights;

fn rlx_torch_fill(value: f64, dtype: rlx_ir::DType, numel: usize) -> Vec<u8> {
    let one: Vec<u8> = match dtype {
        rlx_ir::DType::F32 => (value as f32).to_le_bytes().to_vec(),
        rlx_ir::DType::F64 => value.to_le_bytes().to_vec(),
        rlx_ir::DType::I64 => (value as i64).to_le_bytes().to_vec(),
        rlx_ir::DType::I32 => (value as i32).to_le_bytes().to_vec(),
        _ => vec![],
    };
    let mut out = Vec::with_capacity(one.len() * numel);
    for _ in 0..numel { out.extend_from_slice(&one); }
    out
}

/// Build the model graph and assemble its parameter map.
pub fn build_graph(
    w: &LoadedWeights,
) -> anyhow::Result<(HirModule, HashMap<String, Vec<f32>>)> {
    let mut hir = HirModule::new("dino");
    let mut b = HirMut::new(&mut hir);
    let mut params: HashMap<String, Vec<f32>> = HashMap::new();

    let t_x = b.input("x", rlx_ir::Shape::new(&[1, 3, 16, 16], rlx_ir::DType::F32));

    let t_p_patch_weight = b.param("patch.weight", rlx_ir::Shape::new(&[32, 3, 4, 4], rlx_ir::DType::F32));
    params.insert("patch.weight".to_string(), w.get("patch.weight")?);
    let t_p_patch_bias = b.param("patch.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
    params.insert("patch.bias".to_string(), w.get("patch.bias")?);
    let t_p_n1_weight = b.param("n1.weight", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
    params.insert("n1.weight".to_string(), w.get("n1.weight")?);
    let t_p_n1_bias = b.param("n1.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
    params.insert("n1.bias".to_string(), w.get("n1.bias")?);
    let t_p_n2_weight = b.param("n2.weight", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
    params.insert("n2.weight".to_string(), w.get("n2.weight")?);
    let t_p_n2_bias = b.param("n2.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
    params.insert("n2.bias".to_string(), w.get("n2.bias")?);
    let t_p_q_weight = b.param("q.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
    params.insert("q.weight".to_string(), w.get("q.weight")?);
    let t_p_q_bias = b.param("q.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
    params.insert("q.bias".to_string(), w.get("q.bias")?);
    let t_p_k_weight = b.param("k.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
    params.insert("k.weight".to_string(), w.get("k.weight")?);
    let t_p_k_bias = b.param("k.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
    params.insert("k.bias".to_string(), w.get("k.bias")?);
    let t_p_v_weight = b.param("v.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
    params.insert("v.weight".to_string(), w.get("v.weight")?);
    let t_p_v_bias = b.param("v.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
    params.insert("v.bias".to_string(), w.get("v.bias")?);
    let t_p_o_weight = b.param("o.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
    params.insert("o.weight".to_string(), w.get("o.weight")?);
    let t_p_o_bias = b.param("o.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
    params.insert("o.bias".to_string(), w.get("o.bias")?);
    let t_p_f1_weight = b.param("f1.weight", rlx_ir::Shape::new(&[64, 32], rlx_ir::DType::F32));
    params.insert("f1.weight".to_string(), w.get("f1.weight")?);
    let t_p_f1_bias = b.param("f1.bias", rlx_ir::Shape::new(&[64], rlx_ir::DType::F32));
    params.insert("f1.bias".to_string(), w.get("f1.bias")?);
    let t_p_f2_weight = b.param("f2.weight", rlx_ir::Shape::new(&[32, 64], rlx_ir::DType::F32));
    params.insert("f2.weight".to_string(), w.get("f2.weight")?);
    let t_p_f2_bias = b.param("f2.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
    params.insert("f2.bias".to_string(), w.get("f2.bias")?);
    let t_p_head_weight = b.param("head.weight", rlx_ir::Shape::new(&[10, 32], rlx_ir::DType::F32));
    params.insert("head.weight".to_string(), w.get("head.weight")?);
    let t_p_head_bias = b.param("head.bias", rlx_ir::Shape::new(&[10], rlx_ir::DType::F32));
    params.insert("head.bias".to_string(), w.get("head.bias")?);

    let t_convolution__conv = b.conv2d(t_x, t_p_patch_weight, [4, 4], [4, 4], [0, 0], 1, rlx_ir::Shape::new(&[1, 32, 4, 4], rlx_ir::DType::F32));
    let t_convolution__bias = b.reshape_(t_p_patch_bias, vec![1i64, 32i64, 1i64, 1i64]);
    // aten.convolution.default  (x[1, 3, 16, 16], p_patch_weight[32, 3, 4, 4], p_patch_bias[32]) -> [1, 32, 4, 4] f32
    let t_convolution = b.add(t_convolution__conv, t_convolution__bias);
    // aten.view.default  (convolution[1, 32, 4, 4]) -> [1, 32, 16] f32
    let t_view = b.reshape_(t_convolution, vec![1i64, 32i64, 16i64]);
    // aten.permute.default  (view[1, 32, 16]) -> [1, 16, 32] f32
    let t_permute = b.transpose_(t_view, vec![0usize, 2usize, 1usize]);
    // aten.layer_norm.default  (permute[1, 16, 32], p_n1_weight[32], p_n1_bias[32]) -> [1, 16, 32] f32
    let t_layer_norm = b.ln(t_permute, t_p_n1_weight, t_p_n1_bias, 0.00001f32);
    // aten.view.default  (layer_norm[1, 16, 32]) -> [16, 32] f32
    let t_view_1 = b.reshape_(t_layer_norm, vec![16i64, 32i64]);
    // aten.permute.default  (p_q_weight[32, 32]) -> [32, 32] f32
    let t_permute_1 = b.transpose_(t_p_q_weight, vec![1usize, 0usize]);
    let t_addmm__mm = b.mm(t_view_1, t_permute_1);
    // aten.addmm.default  (p_q_bias[32], view_1[16, 32], permute_1[32, 32]) -> [16, 32] f32
    let t_addmm = b.add(t_addmm__mm, t_p_q_bias);
    // aten.view.default  (addmm[16, 32]) -> [1, 16, 32] f32
    let t_view_2 = b.reshape_(t_addmm, vec![1i64, 16i64, 32i64]);
    // aten.view.default  (view_2[1, 16, 32]) -> [1, 16, 4, 8] f32
    let t_view_3 = b.reshape_(t_view_2, vec![1i64, 16i64, 4i64, 8i64]);
    // aten.permute.default  (view_3[1, 16, 4, 8]) -> [1, 4, 16, 8] f32
    let t_permute_2 = b.transpose_(t_view_3, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.view.default  (layer_norm[1, 16, 32]) -> [16, 32] f32
    let t_view_4 = b.reshape_(t_layer_norm, vec![16i64, 32i64]);
    // aten.permute.default  (p_k_weight[32, 32]) -> [32, 32] f32
    let t_permute_3 = b.transpose_(t_p_k_weight, vec![1usize, 0usize]);
    let t_addmm_1__mm = b.mm(t_view_4, t_permute_3);
    // aten.addmm.default  (p_k_bias[32], view_4[16, 32], permute_3[32, 32]) -> [16, 32] f32
    let t_addmm_1 = b.add(t_addmm_1__mm, t_p_k_bias);
    // aten.view.default  (addmm_1[16, 32]) -> [1, 16, 32] f32
    let t_view_5 = b.reshape_(t_addmm_1, vec![1i64, 16i64, 32i64]);
    // aten.view.default  (view_5[1, 16, 32]) -> [1, 16, 4, 8] f32
    let t_view_6 = b.reshape_(t_view_5, vec![1i64, 16i64, 4i64, 8i64]);
    // aten.permute.default  (view_6[1, 16, 4, 8]) -> [1, 4, 16, 8] f32
    let t_permute_4 = b.transpose_(t_view_6, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.view.default  (layer_norm[1, 16, 32]) -> [16, 32] f32
    let t_view_7 = b.reshape_(t_layer_norm, vec![16i64, 32i64]);
    // aten.permute.default  (p_v_weight[32, 32]) -> [32, 32] f32
    let t_permute_5 = b.transpose_(t_p_v_weight, vec![1usize, 0usize]);
    let t_addmm_2__mm = b.mm(t_view_7, t_permute_5);
    // aten.addmm.default  (p_v_bias[32], view_7[16, 32], permute_5[32, 32]) -> [16, 32] f32
    let t_addmm_2 = b.add(t_addmm_2__mm, t_p_v_bias);
    // aten.view.default  (addmm_2[16, 32]) -> [1, 16, 32] f32
    let t_view_8 = b.reshape_(t_addmm_2, vec![1i64, 16i64, 32i64]);
    // aten.view.default  (view_8[1, 16, 32]) -> [1, 16, 4, 8] f32
    let t_view_9 = b.reshape_(t_view_8, vec![1i64, 16i64, 4i64, 8i64]);
    // aten.permute.default  (view_9[1, 16, 4, 8]) -> [1, 4, 16, 8] f32
    let t_permute_6 = b.transpose_(t_view_9, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.scaled_dot_product_attention.default  (permute_2[1, 4, 16, 8], permute_4[1, 4, 16, 8], permute_6[1, 4, 16, 8]) -> [1, 4, 16, 8] f32
    let t_scaled_dot_product_attention = b.attention_kind(t_permute_2, t_permute_4, t_permute_6, 4, 8, MaskKind::None, rlx_ir::Shape::new(&[1, 4, 16, 8], rlx_ir::DType::F32));
    // aten.permute.default  (scaled_dot_product_attention[1, 4, 16, 8]) -> [1, 16, 4, 8] f32
    let t_permute_7 = b.transpose_(t_scaled_dot_product_attention, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.view.default  (permute_7[1, 16, 4, 8]) -> [1, 16, 32] f32
    let t_view_10 = b.reshape_(t_permute_7, vec![1i64, 16i64, 32i64]);
    // aten.view.default  (view_10[1, 16, 32]) -> [16, 32] f32
    let t_view_11 = b.reshape_(t_view_10, vec![16i64, 32i64]);
    // aten.permute.default  (p_o_weight[32, 32]) -> [32, 32] f32
    let t_permute_8 = b.transpose_(t_p_o_weight, vec![1usize, 0usize]);
    let t_addmm_3__mm = b.mm(t_view_11, t_permute_8);
    // aten.addmm.default  (p_o_bias[32], view_11[16, 32], permute_8[32, 32]) -> [16, 32] f32
    let t_addmm_3 = b.add(t_addmm_3__mm, t_p_o_bias);
    // aten.view.default  (addmm_3[16, 32]) -> [1, 16, 32] f32
    let t_view_12 = b.reshape_(t_addmm_3, vec![1i64, 16i64, 32i64]);
    // aten.add.Tensor  (permute[1, 16, 32], view_12[1, 16, 32]) -> [1, 16, 32] f32
    let t_add = b.add(t_permute, t_view_12);
    // aten.layer_norm.default  (add[1, 16, 32], p_n2_weight[32], p_n2_bias[32]) -> [1, 16, 32] f32
    let t_layer_norm_1 = b.ln(t_add, t_p_n2_weight, t_p_n2_bias, 0.00001f32);
    // aten.view.default  (layer_norm_1[1, 16, 32]) -> [16, 32] f32
    let t_view_13 = b.reshape_(t_layer_norm_1, vec![16i64, 32i64]);
    // aten.permute.default  (p_f1_weight[64, 32]) -> [32, 64] f32
    let t_permute_9 = b.transpose_(t_p_f1_weight, vec![1usize, 0usize]);
    let t_addmm_4__mm = b.mm(t_view_13, t_permute_9);
    // aten.addmm.default  (p_f1_bias[64], view_13[16, 32], permute_9[32, 64]) -> [16, 64] f32
    let t_addmm_4 = b.add(t_addmm_4__mm, t_p_f1_bias);
    // aten.view.default  (addmm_4[16, 64]) -> [1, 16, 64] f32
    let t_view_14 = b.reshape_(t_addmm_4, vec![1i64, 16i64, 64i64]);
    // aten.gelu.default  (view_14[1, 16, 64]) -> [1, 16, 64] f32
    let s_t_gelu = b.shape(t_view_14).clone();
    let t_gelu = b.activation(Activation::Gelu, t_view_14, s_t_gelu);
    // aten.view.default  (gelu[1, 16, 64]) -> [16, 64] f32
    let t_view_15 = b.reshape_(t_gelu, vec![16i64, 64i64]);
    // aten.permute.default  (p_f2_weight[32, 64]) -> [64, 32] f32
    let t_permute_10 = b.transpose_(t_p_f2_weight, vec![1usize, 0usize]);
    let t_addmm_5__mm = b.mm(t_view_15, t_permute_10);
    // aten.addmm.default  (p_f2_bias[32], view_15[16, 64], permute_10[64, 32]) -> [16, 32] f32
    let t_addmm_5 = b.add(t_addmm_5__mm, t_p_f2_bias);
    // aten.view.default  (addmm_5[16, 32]) -> [1, 16, 32] f32
    let t_view_16 = b.reshape_(t_addmm_5, vec![1i64, 16i64, 32i64]);
    // aten.add.Tensor  (add[1, 16, 32], view_16[1, 16, 32]) -> [1, 16, 32] f32
    let t_add_1 = b.add(t_add, t_view_16);
    // aten.mean.dim  (add_1[1, 16, 32]) -> [1, 32] f32
    let t_mean = b.mean(t_add_1, vec![1usize], false);
    // aten.permute.default  (p_head_weight[10, 32]) -> [32, 10] f32
    let t_permute_11 = b.transpose_(t_p_head_weight, vec![1usize, 0usize]);
    let t_addmm_6__mm = b.mm(t_mean, t_permute_11);
    // aten.addmm.default  (p_head_bias[10], mean[1, 32], permute_11[32, 10]) -> [1, 10] f32
    let t_addmm_6 = b.add(t_addmm_6__mm, t_p_head_bias);

    b.set_outputs(vec![t_addmm_6]);
    Ok((hir, params))
}
