[
    EnvVarEntry {
        name: "RLX_ALLOW_THROTTLE",
        group: "debug",
        summary: "Skip thermal gate for one-off benches (prefer `just throttle`)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_ARCH",
        group: "misc",
        summary: "See call sites for `RLX_ARCH`",
        kind: EnvKind::Bool,
        stability: EnvStability::Internal,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_ARENA_ALIGN",
        group: "cpu",
        summary: "See call sites for `RLX_ARENA_ALIGN`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cpu"),
    },
    EnvVarEntry {
        name: "RLX_ARENA_NO_REUSE",
        group: "cpu",
        summary: "See call sites for `RLX_ARENA_NO_REUSE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cpu"),
    },
    EnvVarEntry {
        name: "RLX_ATTN_DEBUG",
        group: "misc",
        summary: "See call sites for `RLX_ATTN_DEBUG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_BENCHMARK_PICK",
        group: "device",
        summary: "Micro-benchmark N runs to pick the fastest device (needs inputs)",
        kind: EnvKind::U64,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Device,
    },
    EnvVarEntry {
        name: "RLX_BENCH_CSV",
        group: "misc",
        summary: "See call sites for `RLX_BENCH_CSV`",
        kind: EnvKind::Bool,
        stability: EnvStability::Internal,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_BENCH_DISPATCH_ONLY",
        group: "misc",
        summary: "See call sites for `RLX_BENCH_DISPATCH_ONLY`",
        kind: EnvKind::String,
        stability: EnvStability::Internal,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_BENCH_ITERS",
        group: "misc",
        summary: "See call sites for `RLX_BENCH_ITERS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Internal,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_CACHE_PARAM_INVARIANT",
        group: "compile",
        summary: "Hoist param-invariant subgraph into prepare-once graph",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_CHECK",
        group: "debug",
        summary: "See call sites for `RLX_CHECK`",
        kind: EnvKind::String,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_COREML_F16",
        group: "coreml",
        summary: "See call sites for `RLX_COREML_F16`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("coreml"),
    },
    EnvVarEntry {
        name: "RLX_COREML_FLEXIBLE_INPUTS",
        group: "coreml",
        summary: "See call sites for `RLX_COREML_FLEXIBLE_INPUTS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("coreml"),
    },
    EnvVarEntry {
        name: "RLX_COREML_HOST_DEQUANT",
        group: "coreml",
        summary: "Force CoreML hybrid host dequant segments",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("coreml"),
    },
    EnvVarEntry {
        name: "RLX_COREML_NATIVE_FLEX",
        group: "coreml",
        summary: "See call sites for `RLX_COREML_NATIVE_FLEX`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("coreml"),
    },
    EnvVarEntry {
        name: "RLX_COREML_NATIVE_SCAN",
        group: "coreml",
        summary: "See call sites for `RLX_COREML_NATIVE_SCAN`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("coreml"),
    },
    EnvVarEntry {
        name: "RLX_COREML_Q1_MODE",
        group: "coreml",
        summary: "See call sites for `RLX_COREML_Q1_MODE`",
        kind: EnvKind::String,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("coreml"),
    },
    EnvVarEntry {
        name: "RLX_COREML_SEG_REPORT",
        group: "coreml",
        summary: "See call sites for `RLX_COREML_SEG_REPORT`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("coreml"),
    },
    EnvVarEntry {
        name: "RLX_COREML_UNITS",
        group: "coreml",
        summary: "See call sites for `RLX_COREML_UNITS`",
        kind: EnvKind::String,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("coreml"),
    },
    EnvVarEntry {
        name: "RLX_CPU_DUMP_FLAT",
        group: "misc",
        summary: "See call sites for `RLX_CPU_DUMP_FLAT`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_CPU_DUMP_NODES",
        group: "misc",
        summary: "See call sites for `RLX_CPU_DUMP_NODES`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_CPU_DUMP_NODES_LIMIT",
        group: "misc",
        summary: "See call sites for `RLX_CPU_DUMP_NODES_LIMIT`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_CUDA_ARENA_DEBUG",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_ARENA_DEBUG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_ARENA_NO_REUSE",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_ARENA_NO_REUSE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_ARENA_POOL",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_ARENA_POOL`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_ARENA_POOL_CHUNK_BYTES",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_ARENA_POOL_CHUNK_BYTES`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_ARENA_POOL_MAX",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_ARENA_POOL_MAX`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_COMPILE_MODE",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_COMPILE_MODE`",
        kind: EnvKind::String,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_COMPILE_TIMING",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_COMPILE_TIMING`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_CONV_BWD_CUDNN",
        group: "cuda",
        summary: "Allow cuDNN for grouped/degenerate Conv2d backward shapes",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_CONV_BWD_HOST",
        group: "cuda",
        summary: "Force CUDA Conv2d backward through CPU host-fallback (parity/debug)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_CONV_FWD_CUDNN",
        group: "cuda",
        summary: "Force CUDA Conv2d forward through cuDNN (override host/default routing)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_CONV_FWD_HOST",
        group: "cuda",
        summary: "Force CUDA Conv2d forward through CPU host-fallback (bisect)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_CONV_STABLE_BWD",
        group: "cuda",
        summary: "Prefer cuDNN IMPLICIT_GEMM (ALGO_1) for conv backward (default on; set 0 to opt out)",
        kind: EnvKind::BoolOr { default: true },
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_CONV_TF32",
        group: "cuda",
        summary: "Enable TF32 tensor-core math for cuDNN conv (default is FMA)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_DUMP_INTERMEDIATE",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_DUMP_INTERMEDIATE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_DUMP_NODES",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_DUMP_NODES`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_DUMP_NODES_LIMIT",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_DUMP_NODES_LIMIT`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_EXEC_MODE",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_EXEC_MODE`",
        kind: EnvKind::String,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_GDN_HOST",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_GDN_HOST`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_GGUF_FUSED_M1",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_GGUF_FUSED_M1`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_GGUF_HOST",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_GGUF_HOST`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_IM2COL_HOST",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_IM2COL_HOST`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_INDEXING_FULL_ARENA",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_INDEXING_FULL_ARENA`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_LOG_CONV_PATH",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_LOG_CONV_PATH`",
        kind: EnvKind::Path,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_LOG_FALLBACK",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_LOG_FALLBACK`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_MATMUL_PRECISE",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_MATMUL_PRECISE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_NONDET_CONV",
        group: "cuda",
        summary: "Allow non-deterministic cuDNN conv backward algos (atomicAdd; faster, noisy)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_NO_CUBLASLT",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_NO_CUBLASLT`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_NO_CUDNN",
        group: "cuda",
        summary: "Skip cuDNN entirely (im2col / custom kernels only; silence missing-lib warning)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_NO_PACKED_BSHD_ATTN",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_NO_PACKED_BSHD_ATTN`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_NO_TF32",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_NO_TF32`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_NO_ZERO_ARENA",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_NO_ZERO_ARENA`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_PARITY",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_PARITY`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_PATH_TRACE",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_PATH_TRACE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_PINNED_IO",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_PINNED_IO`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_PTX_CACHE",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_PTX_CACHE`",
        kind: EnvKind::Path,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_TRACE_FAB",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_TRACE_FAB`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDA_WMMA",
        group: "cuda",
        summary: "See call sites for `RLX_CUDA_WMMA`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_CUDNN_DIR",
        group: "cuda",
        summary: "Directory containing libcudnn.so* to preload (pip/conda wheel failsafe)",
        kind: EnvKind::Path,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("cuda"),
    },
    EnvVarEntry {
        name: "RLX_DBG_BINF",
        group: "debug",
        summary: "See call sites for `RLX_DBG_BINF`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_DBG_CONV",
        group: "debug",
        summary: "See call sites for `RLX_DBG_CONV`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_DBG_CUSTOM",
        group: "debug",
        summary: "Log host custom-op staging (onnx.* dtype bridge) on GPU backends",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_DBG_SHAPES",
        group: "debug",
        summary: "See call sites for `RLX_DBG_SHAPES`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_DBG_STEP",
        group: "debug",
        summary: "See call sites for `RLX_DBG_STEP`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_DEBUG_NANS",
        group: "debug",
        summary: "Runtime NaN/Inf localizer (1 or abort)",
        kind: EnvKind::Enum(&["", "1", "abort"]),
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_DECODE_BUCKET_PEAK_BYTES",
        group: "misc",
        summary: "See call sites for `RLX_DECODE_BUCKET_PEAK_BYTES`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_DECODE_BUCKET_RESIDENT_BYTES",
        group: "misc",
        summary: "See call sites for `RLX_DECODE_BUCKET_RESIDENT_BYTES`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_DECODE_ONESHOT_PEAK_BYTES",
        group: "misc",
        summary: "See call sites for `RLX_DECODE_ONESHOT_PEAK_BYTES`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_DECOMPOSE_FUSION_REGIONS",
        group: "misc",
        summary: "See call sites for `RLX_DECOMPOSE_FUSION_REGIONS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_DEQUANT_CACHE",
        group: "misc",
        summary: "See call sites for `RLX_DEQUANT_CACHE`",
        kind: EnvKind::Path,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_DEVICE",
        group: "device",
        summary: "Default device hint for resolved runs (cpu, metal, mlx, cuda, gpu, …)",
        kind: EnvKind::String,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Device,
    },
    EnvVarEntry {
        name: "RLX_DEVICES",
        group: "device",
        summary: "Allow-list of devices for DevicePolicy::from_env",
        kind: EnvKind::String,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Device,
    },
    EnvVarEntry {
        name: "RLX_DEVICE_CHAIN",
        group: "device",
        summary: "Fallback order when a preferred device fails (e.g. cuda,gpu,cpu)",
        kind: EnvKind::String,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Device,
    },
    EnvVarEntry {
        name: "RLX_DIRECT_CONV",
        group: "misc",
        summary: "See call sites for `RLX_DIRECT_CONV`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_DISABLE_CONV_BIAS_ACT_FUSION",
        group: "compile",
        summary: "Skip Conv+Bias+Act fusion",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_DISABLE_MPS",
        group: "misc",
        summary: "See call sites for `RLX_DISABLE_MPS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_DISABLE_MPSGRAPH",
        group: "metal",
        summary: "Force Metal thunk path instead of MPSGraph regions",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_DISABLE_MPSGRAPH_EXECUTABLE",
        group: "metal",
        summary: "See call sites for `RLX_DISABLE_MPSGRAPH_EXECUTABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_DISABLE_NOMIC_FUSION",
        group: "misc",
        summary: "See call sites for `RLX_DISABLE_NOMIC_FUSION`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_DISPATCH_REPORT",
        group: "debug",
        summary: "Print legalize/dispatch report during compile (1 = on)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_DUMP_SCHED",
        group: "misc",
        summary: "See call sites for `RLX_DUMP_SCHED`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_ENABLE_FUSE_TRANSFORMER_LAYER",
        group: "misc",
        summary: "See call sites for `RLX_ENABLE_FUSE_TRANSFORMER_LAYER`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_ENV_DEPRECATIONS",
        group: "debug",
        summary: "Emit one-shot messages when deprecated RLX_* aliases are used",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_F32_DUMP",
        group: "misc",
        summary: "See call sites for `RLX_F32_DUMP`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_FAST_CONV",
        group: "cpu",
        summary: "CPU Conv2d im2col+BLAS path (default on; set 0 for scalar nested loops)",
        kind: EnvKind::BoolOr { default: true },
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("cpu"),
    },
    EnvVarEntry {
        name: "RLX_FFT_CPU_PARALLEL",
        group: "fft",
        summary: "See call sites for `RLX_FFT_CPU_PARALLEL`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_FFT_CUFFT",
        group: "fft",
        summary: "See call sites for `RLX_FFT_CUFFT`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_FFT_FAST",
        group: "gpu",
        summary: "Enable native on-chip GPU FFT when compiled (0 disables)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_FFT_FORCE_MIXED",
        group: "fft",
        summary: "See call sites for `RLX_FFT_FORCE_MIXED`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_FFT_FUSE_DEBUG",
        group: "fft",
        summary: "See call sites for `RLX_FFT_FUSE_DEBUG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_FFT_FUSE_REAL",
        group: "fft",
        summary: "See call sites for `RLX_FFT_FUSE_REAL`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_FFT_GEN",
        group: "fft",
        summary: "See call sites for `RLX_FFT_GEN`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_FFT_MULTIROW",
        group: "fft",
        summary: "See call sites for `RLX_FFT_MULTIROW`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_FFT_NATIVE",
        group: "fft",
        summary: "See call sites for `RLX_FFT_NATIVE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_FFT_RADIX",
        group: "fft",
        summary: "See call sites for `RLX_FFT_RADIX`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_FFT_RADIX4",
        group: "fft",
        summary: "See call sites for `RLX_FFT_RADIX4`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_FK_BATCH_SINGLE_KERNEL",
        group: "misc",
        summary: "See call sites for `RLX_FK_BATCH_SINGLE_KERNEL`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_FORCE_DEVICE",
        group: "misc",
        summary: "See call sites for `RLX_FORCE_DEVICE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_FUSED_GPU_CONIC_SCANLINE",
        group: "misc",
        summary: "See call sites for `RLX_FUSED_GPU_CONIC_SCANLINE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_FUSE_ATTN_THRESHOLD",
        group: "compile",
        summary: "See call sites for `RLX_FUSE_ATTN_THRESHOLD`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_FUSE_BATCH_PREPROCESS",
        group: "compile",
        summary: "See call sites for `RLX_FUSE_BATCH_PREPROCESS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_FUSE_REGION_PROLOGUE",
        group: "compile",
        summary: "See call sites for `RLX_FUSE_REGION_PROLOGUE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_FUSION_REPORT",
        group: "compile",
        summary: "Print fusion pass before/after report",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_GGUF_MATMUL_LEGACY",
        group: "misc",
        summary: "See call sites for `RLX_GGUF_MATMUL_LEGACY`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_GGUF_TRACE",
        group: "misc",
        summary: "See call sites for `RLX_GGUF_TRACE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_GPU_HANDLE_HOST_MIRROR",
        group: "misc",
        summary: "See call sites for `RLX_GPU_HANDLE_HOST_MIRROR`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_HIGHER_ORDER_NO_FUSE",
        group: "misc",
        summary: "See call sites for `RLX_HIGHER_ORDER_NO_FUSE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_HYBRID_K",
        group: "misc",
        summary: "See call sites for `RLX_HYBRID_K`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_HYBRID_M",
        group: "misc",
        summary: "See call sites for `RLX_HYBRID_M`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_ICB_TRACE",
        group: "misc",
        summary: "See call sites for `RLX_ICB_TRACE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_IMP_DBG",
        group: "misc",
        summary: "See call sites for `RLX_IMP_DBG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_INDEXING_FULL_ARENA",
        group: "gpu",
        summary: "Force full-arena mirror for indexing host-fallback (bisect; slow on discrete GPUs)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_IQ_TEST_DIR",
        group: "misc",
        summary: "See call sites for `RLX_IQ_TEST_DIR`",
        kind: EnvKind::Path,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_IR_DUMP",
        group: "misc",
        summary: "See call sites for `RLX_IR_DUMP`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_KEEP_ELEMENTWISE_REGIONS",
        group: "misc",
        summary: "See call sites for `RLX_KEEP_ELEMENTWISE_REGIONS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_KERNEL_DISPATCH",
        group: "compile",
        summary: "common|native|force_common|force_native kernel dispatch policy",
        kind: EnvKind::Enum(&["common", "native", "force_common", "force_native"]),
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_KV_CACHE_DBG",
        group: "misc",
        summary: "See call sites for `RLX_KV_CACHE_DBG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_KV_CACHE_MAX_RESIDENT",
        group: "misc",
        summary: "See call sites for `RLX_KV_CACHE_MAX_RESIDENT`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_KV_CACHE_NO_EVICT",
        group: "misc",
        summary: "See call sites for `RLX_KV_CACHE_NO_EVICT`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_LINT_NUMERICS",
        group: "compile",
        summary: "Static provable NaN/Inf lint during compile",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_LM_HEAD_PARALLEL",
        group: "misc",
        summary: "See call sites for `RLX_LM_HEAD_PARALLEL`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_LOG_EPOCH_LOSS",
        group: "misc",
        summary: "See call sites for `RLX_LOG_EPOCH_LOSS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_LSTM_DEBUG",
        group: "misc",
        summary: "See call sites for `RLX_LSTM_DEBUG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_METAL_ATTN_BWD_GPU",
        group: "metal",
        summary: "See call sites for `RLX_METAL_ATTN_BWD_GPU`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_ATTN_TRACE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_ATTN_TRACE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_CMDBUF_TRACE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_CMDBUF_TRACE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_CONCAT_HOST",
        group: "metal",
        summary: "See call sites for `RLX_METAL_CONCAT_HOST`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_CONCAT_MULTI",
        group: "metal",
        summary: "See call sites for `RLX_METAL_CONCAT_MULTI`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_CONV_BWD_IMPLICIT",
        group: "metal",
        summary: "See call sites for `RLX_METAL_CONV_BWD_IMPLICIT`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_DEBUG",
        group: "metal",
        summary: "See call sites for `RLX_METAL_DEBUG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_DEQUANT_GPU_DISABLE",
        group: "metal",
        summary: "Disable Metal GPU GGUF/MLX dequant (host / legacy path)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &["RLX_DISABLE_METAL_DEQUANT_GPU"],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_MLX_DEQUANT_GPU_DISABLE",
        group: "quant",
        summary: "Force host-staged MLX DequantMatMul on all GPU backends",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_METAL_DEQUANT_MATMUL_LEGACY",
        group: "metal",
        summary: "Use pre-fused dequant+matmul path (materializes weights)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_DISABLE_NARROW_ROPE_FUSE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_DISABLE_NARROW_ROPE_FUSE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_DUMP_NODES",
        group: "metal",
        summary: "See call sites for `RLX_METAL_DUMP_NODES`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_DUMP_NODES_LIMIT",
        group: "metal",
        summary: "See call sites for `RLX_METAL_DUMP_NODES_LIMIT`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_EXTERNALIZE_QUANT",
        group: "metal",
        summary: "See call sites for `RLX_METAL_EXTERNALIZE_QUANT`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_EXT_TRACE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_EXT_TRACE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_FA",
        group: "metal",
        summary: "See call sites for `RLX_METAL_FA`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_FFT_HOST_FALLBACK",
        group: "metal",
        summary: "See call sites for `RLX_METAL_FFT_HOST_FALLBACK`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_FORCE_INLINE_PARAMS",
        group: "metal",
        summary: "See call sites for `RLX_METAL_FORCE_INLINE_PARAMS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_FORCE_PIN_OUTPUT_ANCESTORS",
        group: "metal",
        summary: "See call sites for `RLX_METAL_FORCE_PIN_OUTPUT_ANCESTORS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_FORCE_UNPIN_OUTPUT_ANCESTORS",
        group: "metal",
        summary: "See call sites for `RLX_METAL_FORCE_UNPIN_OUTPUT_ANCESTORS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_FUSE_DECODE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_FUSE_DECODE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_FUSE_DECODE_GELU",
        group: "metal",
        summary: "See call sites for `RLX_METAL_FUSE_DECODE_GELU`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_FUSE_DECODE_LOG",
        group: "metal",
        summary: "See call sites for `RLX_METAL_FUSE_DECODE_LOG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_FUSE_DEPTHWISE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_FUSE_DEPTHWISE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_FUSE_GDN_NORM",
        group: "metal",
        summary: "See call sites for `RLX_METAL_FUSE_GDN_NORM`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_FUSE_RESIDUAL_RMS",
        group: "metal",
        summary: "See call sites for `RLX_METAL_FUSE_RESIDUAL_RMS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_GDN_CPU",
        group: "metal",
        summary: "See call sites for `RLX_METAL_GDN_CPU`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_GDN_HOST_FALLBACK",
        group: "metal",
        summary: "See call sites for `RLX_METAL_GDN_HOST_FALLBACK`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_HOST_FALLBACK",
        group: "metal",
        summary: "See call sites for `RLX_METAL_HOST_FALLBACK`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_HOST_SLICE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_HOST_SLICE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_HYBRID_BIG_ARENA",
        group: "metal",
        summary: "See call sites for `RLX_METAL_HYBRID_BIG_ARENA`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_IQ1M_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_IQ1M_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_IQ1S_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_IQ1S_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_IQ2S_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_IQ2S_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_IQ2XS_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_IQ2XS_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_IQ2XXS_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_IQ2XXS_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_IQ3S_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_IQ3S_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_IQ3XXS_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_IQ3XXS_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_IQ4NL_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_IQ4NL_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_LSTM_CPU",
        group: "metal",
        summary: "See call sites for `RLX_METAL_LSTM_CPU`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_LSTM_HOST_FALLBACK",
        group: "metal",
        summary: "See call sites for `RLX_METAL_LSTM_HOST_FALLBACK`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_MPSGRAPH_BIG_ARENA",
        group: "metal",
        summary: "See call sites for `RLX_METAL_MPSGRAPH_BIG_ARENA`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_MPS_PROFILE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_MPS_PROFILE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_MPS_SDPA",
        group: "metal",
        summary: "See call sites for `RLX_METAL_MPS_SDPA`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_NARROW_BATCH",
        group: "metal",
        summary: "See call sites for `RLX_METAL_NARROW_BATCH`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_NO_FUSION",
        group: "metal",
        summary: "See call sites for `RLX_METAL_NO_FUSION`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_NO_SHARE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_NO_SHARE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_ONNX_QMATMUL_GPU",
        group: "metal",
        summary: "See call sites for `RLX_METAL_ONNX_QMATMUL_GPU`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_ONNX_QMATMUL_MIN_FLOPS",
        group: "metal",
        summary: "See call sites for `RLX_METAL_ONNX_QMATMUL_MIN_FLOPS`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_OUTPUT_TRACE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_OUTPUT_TRACE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_PIPELINE_CACHE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_PIPELINE_CACHE`",
        kind: EnvKind::Path,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_PRECISE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_PRECISE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_Q1_0_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_Q1_0_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_Q1_0_SG_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_Q1_0_SG_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_Q1_DUAL_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_Q1_DUAL_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_Q2_0_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_Q2_0_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_Q2_0_SG_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_Q2_0_SG_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_Q2_DUAL_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_Q2_DUAL_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_Q40_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_Q40_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_Q41_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_Q41_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_Q4K_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_Q4K_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_Q4K_GEMM_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_Q4K_GEMM_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_Q4K_SG_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_Q4K_SG_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_Q6K_GEMM_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_Q6K_GEMM_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_Q80_FUSED_DISABLE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_Q80_FUSED_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_RNN_HOST_FALLBACK",
        group: "metal",
        summary: "See call sites for `RLX_METAL_RNN_HOST_FALLBACK`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_SAMPLE_HOST",
        group: "metal",
        summary: "See call sites for `RLX_METAL_SAMPLE_HOST`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_SDPA_DECODE_M1",
        group: "metal",
        summary: "See call sites for `RLX_METAL_SDPA_DECODE_M1`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_SGEMM_MPS",
        group: "metal",
        summary: "See call sites for `RLX_METAL_SGEMM_MPS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_SGEMM_PRECISE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_SGEMM_PRECISE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_SGEMM_VARIANT",
        group: "metal",
        summary: "See call sites for `RLX_METAL_SGEMM_VARIANT`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_SOFTMAX_TRACE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_SOFTMAX_TRACE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_SSM_CPU",
        group: "metal",
        summary: "See call sites for `RLX_METAL_SSM_CPU`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_SSM_HOST_FALLBACK",
        group: "metal",
        summary: "See call sites for `RLX_METAL_SSM_HOST_FALLBACK`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_THUNK_PROFILE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_THUNK_PROFILE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_TRACE",
        group: "metal",
        summary: "See call sites for `RLX_METAL_TRACE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_TRACE_FAB",
        group: "metal",
        summary: "See call sites for `RLX_METAL_TRACE_FAB`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_METAL_UNFUSE_REGIONS",
        group: "metal",
        summary: "See call sites for `RLX_METAL_UNFUSE_REGIONS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_MLX_COMPILE_MAX_NODES",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_COMPILE_MAX_NODES`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_CUDA_ARCH",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_CUDA_ARCH`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_DEBUG_EVAL",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_DEBUG_EVAL`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_DEQUANT_CACHE_BYTES",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_DEQUANT_CACHE_BYTES`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_DEQUANT_CACHE_DISABLE",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_DEQUANT_CACHE_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_DEVICE",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_DEVICE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_FUSE_CAP",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_FUSE_CAP`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_GGUF_HOST_FALLBACK",
        group: "mlx",
        summary: "Force host GGUF dequant on MLX",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_JOBS",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_JOBS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_MODE",
        group: "mlx",
        summary: "eager | lazy | compiled execution mode",
        kind: EnvKind::Enum(&["eager", "lazy", "compiled"]),
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_PARAM_VIEW",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_PARAM_VIEW`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_PROFILE",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_PROFILE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_Q1_HOST",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_Q1_HOST`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_Q1_MV_DISABLE",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_Q1_MV_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_RNN_F16",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_RNN_F16`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_SDPA_REFERENCE",
        group: "mlx",
        summary: "Use reference SDPA composition for bisects",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MLX_WARN_LAZY",
        group: "mlx",
        summary: "See call sites for `RLX_MLX_WARN_LAZY`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("mlx"),
    },
    EnvVarEntry {
        name: "RLX_MNIST_DIR",
        group: "misc",
        summary: "See call sites for `RLX_MNIST_DIR`",
        kind: EnvKind::Path,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_MPSGRAPH_FORCE",
        group: "metal",
        summary: "See call sites for `RLX_MPSGRAPH_FORCE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_MPSGRAPH_MIN_FLOPS",
        group: "metal",
        summary: "See call sites for `RLX_MPSGRAPH_MIN_FLOPS`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_MPSGRAPH_PARAM_CONST",
        group: "metal",
        summary: "See call sites for `RLX_MPSGRAPH_PARAM_CONST`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_MPSGRAPH_PARAM_CONST_CAP",
        group: "metal",
        summary: "See call sites for `RLX_MPSGRAPH_PARAM_CONST_CAP`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_MPSGRAPH_TRACE",
        group: "metal",
        summary: "See call sites for `RLX_MPSGRAPH_TRACE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_MPSG_TRACE",
        group: "misc",
        summary: "See call sites for `RLX_MPSG_TRACE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_MPS_ALIGN_DEBUG",
        group: "metal",
        summary: "See call sites for `RLX_MPS_ALIGN_DEBUG`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_MPS_FP16",
        group: "metal",
        summary: "See call sites for `RLX_MPS_FP16`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_MPS_THRESHOLD_FLOP",
        group: "metal",
        summary: "See call sites for `RLX_MPS_THRESHOLD_FLOP`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },
    EnvVarEntry {
        name: "RLX_NATIVE_FK_REGIONS",
        group: "misc",
        summary: "See call sites for `RLX_NATIVE_FK_REGIONS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_NEMO_TEST_FILE",
        group: "misc",
        summary: "See call sites for `RLX_NEMO_TEST_FILE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_NO_FK_FUSION",
        group: "misc",
        summary: "See call sites for `RLX_NO_FK_FUSION`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_NO_IO_PEAKS_OUTPUT",
        group: "compile",
        summary: "Disable compile-time IO-gated peaks-only fusion",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Compile,
    },
    EnvVarEntry {
        name: "RLX_NO_NATIVE_FK_REGIONS",
        group: "misc",
        summary: "See call sites for `RLX_NO_NATIVE_FK_REGIONS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_NO_SHARED_INPUT_MATMUL",
        group: "misc",
        summary: "See call sites for `RLX_NO_SHARED_INPUT_MATMUL`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_NO_SHUFFLE",
        group: "misc",
        summary: "See call sites for `RLX_NO_SHUFFLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Internal,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_ONEAPI_BUILD_KERNELS",
        group: "oneapi",
        summary: "See call sites for `RLX_ONEAPI_BUILD_KERNELS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("oneapi"),
    },
    EnvVarEntry {
        name: "RLX_ONEAPI_LOADER",
        group: "oneapi",
        summary: "See call sites for `RLX_ONEAPI_LOADER`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("oneapi"),
    },
    EnvVarEntry {
        name: "RLX_ONEAPI_OCLOC",
        group: "oneapi",
        summary: "See call sites for `RLX_ONEAPI_OCLOC`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("oneapi"),
    },
    EnvVarEntry {
        name: "RLX_ONEAPI_OCLOC_DEVICE",
        group: "oneapi",
        summary: "See call sites for `RLX_ONEAPI_OCLOC_DEVICE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("oneapi"),
    },
    EnvVarEntry {
        name: "RLX_ONNX_BUNDLE",
        group: "onnx",
        summary: "See call sites for `RLX_ONNX_BUNDLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_ONNX_SEQUENCE_LENGTH",
        group: "onnx",
        summary: "See call sites for `RLX_ONNX_SEQUENCE_LENGTH`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_ONNX_TAP",
        group: "onnx",
        summary: "See call sites for `RLX_ONNX_TAP`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_ONNX_TEST_MODEL",
        group: "onnx",
        summary: "See call sites for `RLX_ONNX_TEST_MODEL`",
        kind: EnvKind::String,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_ORT_CUDA_GRAPH",
        group: "misc",
        summary: "See call sites for `RLX_ORT_CUDA_GRAPH`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_PARITY_DEVICE",
        group: "misc",
        summary: "See call sites for `RLX_PARITY_DEVICE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_PAR_THRESHOLD",
        group: "cpu",
        summary: "See call sites for `RLX_PAR_THRESHOLD`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cpu"),
    },
    EnvVarEntry {
        name: "RLX_PHASE_TIMING",
        group: "misc",
        summary: "See call sites for `RLX_PHASE_TIMING`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_PROBE_DYNAMIC",
        group: "misc",
        summary: "See call sites for `RLX_PROBE_DYNAMIC`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_PROBE_FEATURE_DIM",
        group: "misc",
        summary: "See call sites for `RLX_PROBE_FEATURE_DIM`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_PROFILE_COMPILE",
        group: "misc",
        summary: "See call sites for `RLX_PROFILE_COMPILE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_PROFILE_THUNKS",
        group: "misc",
        summary: "See call sites for `RLX_PROFILE_THUNKS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_QNN_BACKEND_LIB",
        group: "qnn",
        summary: "See call sites for `RLX_QNN_BACKEND_LIB`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("qnn"),
    },
    EnvVarEntry {
        name: "RLX_RIG_RUNTIME",
        group: "misc",
        summary: "See call sites for `RLX_RIG_RUNTIME`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_ROCM_HSACO_CACHE",
        group: "rocm",
        summary: "See call sites for `RLX_ROCM_HSACO_CACHE`",
        kind: EnvKind::Path,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("rocm"),
    },
    EnvVarEntry {
        name: "RLX_ROCM_IM2COL_HOST",
        group: "rocm",
        summary: "See call sites for `RLX_ROCM_IM2COL_HOST`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("rocm"),
    },
    EnvVarEntry {
        name: "RLX_ROCM_LOG_FALLBACK",
        group: "rocm",
        summary: "See call sites for `RLX_ROCM_LOG_FALLBACK`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("rocm"),
    },
    EnvVarEntry {
        name: "RLX_ROCM_MFMA",
        group: "rocm",
        summary: "See call sites for `RLX_ROCM_MFMA`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("rocm"),
    },
    EnvVarEntry {
        name: "RLX_ROCM_NO_PACKED_BSHD_ATTN",
        group: "rocm",
        summary: "See call sites for `RLX_ROCM_NO_PACKED_BSHD_ATTN`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("rocm"),
    },
    EnvVarEntry {
        name: "RLX_ROCM_PINNED_IO",
        group: "rocm",
        summary: "Use pinned host I/O for ROCm graph exec (default on in graph mode)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("rocm"),
    },
    EnvVarEntry {
        name: "RLX_ROPE_DEBUG",
        group: "misc",
        summary: "See call sites for `RLX_ROPE_DEBUG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_SDPA_THRESHOLD",
        group: "cpu",
        summary: "See call sites for `RLX_SDPA_THRESHOLD`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cpu"),
    },
    EnvVarEntry {
        name: "RLX_SOFT_MEMORY_BUDGET_BYTES",
        group: "misc",
        summary: "See call sites for `RLX_SOFT_MEMORY_BUDGET_BYTES`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_SOFT_MEMORY_FRACTION",
        group: "misc",
        summary: "See call sites for `RLX_SOFT_MEMORY_FRACTION`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_SPD_JACOBI_SWEEPS",
        group: "misc",
        summary: "See call sites for `RLX_SPD_JACOBI_SWEEPS`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_SPD_UNROLL",
        group: "misc",
        summary: "See call sites for `RLX_SPD_UNROLL`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_TPU_HLO_DUMP",
        group: "tpu",
        summary: "See call sites for `RLX_TPU_HLO_DUMP`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("tpu"),
    },
    EnvVarEntry {
        name: "RLX_TRACE_PERFETTO",
        group: "misc",
        summary: "See call sites for `RLX_TRACE_PERFETTO`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_TRACE_THUNK",
        group: "misc",
        summary: "See call sites for `RLX_TRACE_THUNK`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_UMAP_CUDA_FUSED_KNN",
        group: "misc",
        summary: "See call sites for `RLX_UMAP_CUDA_FUSED_KNN`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_USE_ICB",
        group: "misc",
        summary: "See call sites for `RLX_USE_ICB`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_VMATH_ACCURATE",
        group: "cpu",
        summary: "CPU vmath exp/tanh/log/sqrt: use Accelerate/libm accurate path (default 0 = SIMD *_fast)",
        kind: EnvKind::BoolOr { default: false },
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("cpu"),
    },
    EnvVarEntry {
        name: "RLX_VERBOSE",
        group: "debug",
        summary: "Extra runtime logging",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_VULKAN_ARENA_DEBUG",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_ARENA_DEBUG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_VULKAN_CHECK_BCAST",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_CHECK_BCAST`",
        kind: EnvKind::String,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_VULKAN_CHECK_CAST",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_CHECK_CAST`",
        kind: EnvKind::String,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_VULKAN_DEBUG",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_DEBUG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_VULKAN_DUMP_OPS",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_DUMP_OPS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_VULKAN_FULLBARRIER",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_FULLBARRIER`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_VULKAN_HOST_CONV",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_HOST_CONV`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_VULKAN_HOST_OPS",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_HOST_OPS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_VULKAN_MATMUL",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_MATMUL`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_VULKAN_NOBARRIER",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_NOBARRIER`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_VULKAN_NOCACHE",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_NOCACHE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_VULKAN_SCAN_ALL",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_SCAN_ALL`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_VULKAN_SHARD_LOG",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_SHARD_LOG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_VULKAN_VALIDATION",
        group: "vulkan",
        summary: "See call sites for `RLX_VULKAN_VALIDATION`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("vulkan"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_ACTIVE_TRACE",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_ACTIVE_TRACE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_CONCAT_HOST",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_CONCAT_HOST`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_CONV_IM2COL",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_CONV_IM2COL`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_COOP_F16_VK_DISABLE",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_COOP_F16_VK_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_COOP_F16_VK_ENABLE",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_COOP_F16_VK_ENABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_COOP_F16_VK_FORCE_WIDE",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_COOP_F16_VK_FORCE_WIDE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_COOP_F16_VK_LARGE_N",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_COOP_F16_VK_LARGE_N`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_COOP_F16_VK_LOAD_T",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_COOP_F16_VK_LOAD_T`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_COOP_F16_VK_NO_AUTO_WIDE",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_COOP_F16_VK_NO_AUTO_WIDE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_COOP_F16_VK_NO_F32ACC",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_COOP_F16_VK_NO_F32ACC`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_COOP_F16_VK_OSC_THRESH",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_COOP_F16_VK_OSC_THRESH`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_DEBUG",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_DEBUG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_DEBUG_ATTN_ALIAS",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_DEBUG_ATTN_ALIAS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_DEBUG_ATTN_MASK",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_DEBUG_ATTN_MASK`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_DEBUG_OP_HIST",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_DEBUG_OP_HIST`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_DUMP_FLAT",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_DUMP_FLAT`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_DUMP_IDS",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_DUMP_IDS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_DUMP_INPUTS",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_DUMP_INPUTS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_DUMP_NODES",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_DUMP_NODES`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_DUMP_NODES_LIMIT",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_DUMP_NODES_LIMIT`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_DUMP_TAIL",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_DUMP_TAIL`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_F16_WEIGHTS",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_F16_WEIGHTS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_FORCE_COOP_F32",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_FORCE_COOP_F32`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_FORCE_INPUT_UPLOAD",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_FORCE_INPUT_UPLOAD`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_GDN_HOST",
        group: "wgpu",
        summary: "Force GatedDeltaNet host fallback on wgpu (skip WGSL)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_HOST_BUFFER_COPY",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_HOST_BUFFER_COPY`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_IM2COL_MIN_COUT",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_IM2COL_MIN_COUT`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_IM2COL_MIN_K",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_IM2COL_MIN_K`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_IM2COL_MIN_SPATIAL",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_IM2COL_MIN_SPATIAL`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_LARGE_BUFFERS",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_LARGE_BUFFERS`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_MATMUL_F32_ONLY",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_MATMUL_F32_ONLY`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_NAN_TRACE",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_NAN_TRACE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_NO_COOP_F16_VK",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_NO_COOP_F16_VK`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_NO_COOP_F32",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_NO_COOP_F32`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_NO_F16_MIRROR",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_NO_F16_MIRROR`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_NO_F16_SHADOW",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_NO_F16_SHADOW`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_NO_PACKED_BSHD_ATTN",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_NO_PACKED_BSHD_ATTN`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_NO_TILED_CONV",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_NO_TILED_CONV`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_PRINT_LIMITS",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_PRINT_LIMITS`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_Q1_0_GEMM_DISABLE",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_Q1_0_GEMM_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_SCHEDULE",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_SCHEDULE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_SHARD_LOG",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_SHARD_LOG`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_SHARE_WEIGHTS",
        group: "wgpu",
        summary: "Reuse GPU weight buffers across compiles with matching named layouts (default on; set 0 to disable)",
        kind: EnvKind::Bool,
        stability: EnvStability::Public,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WGPU_TILED_MIN_SPATIAL",
        group: "wgpu",
        summary: "See call sites for `RLX_WGPU_TILED_MIN_SPATIAL`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("wgpu"),
    },
    EnvVarEntry {
        name: "RLX_WINOGRAD",
        group: "misc",
        summary: "See call sites for `RLX_WINOGRAD`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Tooling,
    },
    EnvVarEntry {
        name: "RLX_WORKERS",
        group: "cpu",
        summary: "See call sites for `RLX_WORKERS`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Backend("cpu"),
    },
    EnvVarEntry {
        name: "RLX_DISABLE_METAL_DEQUANT_GPU",
        group: "metal",
        summary: "Deprecated alias of `RLX_METAL_DEQUANT_GPU_DISABLE`",
        kind: EnvKind::Bool,
        stability: EnvStability::Deprecated { replace_with: "RLX_METAL_DEQUANT_GPU_DISABLE" },
        aliases: &[],
        layer: EnvLayer::Backend("metal"),
    },

    EnvVarEntry {
        name: "RLX_DEBUG_TRIP",
        group: "debug",
        summary: "See call sites for `RLX_DEBUG_TRIP`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_QMATMUL_GPU_MIN_FLOPS",
        group: "gpu",
        summary: "See call sites for `RLX_QMATMUL_GPU_MIN_FLOPS`",
        kind: EnvKind::U64,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_QMATMUL_INGRAPH",
        group: "gpu",
        summary: "See call sites for `RLX_QMATMUL_INGRAPH`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
    EnvVarEntry {
        name: "RLX_TIMING",
        group: "profile",
        summary: "See call sites for `RLX_TIMING`",
        kind: EnvKind::Bool,
        stability: EnvStability::Bisect,
        aliases: &[],
        layer: EnvLayer::Runtime,
    },
]
