// AUTO-GENERATED by rlx-torch-import.
// SPDX-License-Identifier: MIT OR Apache-2.0
use std::collections::HashMap;
use std::path::Path;

/// All model tensors, decoded to f32.
pub struct LoadedWeights {
    map: HashMap<String, Vec<f32>>,
}

impl LoadedWeights {
    pub fn get(&self, name: &str) -> anyhow::Result<Vec<f32>> {
        self.map
            .get(name)
            .cloned()
            .ok_or_else(|| anyhow::anyhow!("weight {name:?} missing"))
    }
}

/// Load `weights.safetensors` from `dir`, decoding every tensor to f32.
pub fn load_weights(dir: &Path) -> anyhow::Result<LoadedWeights> {
    let bytes = std::fs::read(dir.join("weights.safetensors"))?;
    let mut map = HashMap::new();
    if !bytes.is_empty() {
        let st = safetensors::SafeTensors::deserialize(&bytes)?;
        for name in st.names() {
            let v = st.tensor(name)?;
            let raw = v.data();
            let data: Vec<f32> = match v.dtype() {
                safetensors::Dtype::F32 => raw
                    .chunks_exact(4)
                    .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
                    .collect(),
                safetensors::Dtype::F16 => raw
                    .chunks_exact(2)
                    .map(|c| half::f16::from_le_bytes([c[0], c[1]]).to_f32())
                    .collect(),
                safetensors::Dtype::BF16 => raw
                    .chunks_exact(2)
                    .map(|c| half::bf16::from_le_bytes([c[0], c[1]]).to_f32())
                    .collect(),
                safetensors::Dtype::F64 => raw
                    .chunks_exact(8)
                    .map(|c| f64::from_le_bytes(c.try_into().unwrap()) as f32)
                    .collect(),
                other => anyhow::bail!("unsupported weight dtype {other:?}"),
            };
            map.insert(name.to_string(), data);
        }
    }
    Ok(LoadedWeights { map })
}
