// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Generators for `rlx-cortexm/src/model_weights.rs` and
//! `rlx-cortexm/tests/data/test_set.bin`. The output formats match
//! exactly what `tools/train_mnist.py` produces, so the firmware and
//! the existing parity tests don't need to change.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use crate::Args;
use crate::mnist::{Dataset, PIXELS};
use crate::quant::QuantizedModel;

pub fn write_model_weights(model: &QuantizedModel, path: &Path) -> Result<(), String> {
    // Emit a binary blob next to the .rs shim. The .rs imports the
    // .bin via `include_bytes!`; firmware kernels read fixed-position
    // tensor slices from it. See `model_weights.bin` at the same path.
    let bin_path = path.with_file_name("model_weights.bin");
    let blob = crate::blob::encode(model);
    if let Some(parent) = bin_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("creating {}: {e}", parent.display()))?;
    }
    fs::write(&bin_path, &blob).map_err(|e| format!("writing {}: {e}", bin_path.display()))?;
    eprintln!("wrote {} ({} bytes)", bin_path.display(), blob.len());

    // Now the .rs shim — pure offset arithmetic, no comma-soup.
    let mut s = String::new();
    s.push_str("// Auto-generated by rlx-cortexm-trainer.\n");
    s.push_str("// Weights live in the sibling `model_weights.bin` (RLXM v1 format,\n");
    s.push_str("// see trainer/src/blob.rs). This file is just the Rust-visible\n");
    s.push_str("// surface: per-tensor static slice references and per-channel mults.\n");
    s.push_str(&format!(
        "// fp32 test accuracy at training: {:.4}\n",
        model.fp32_test_accuracy
    ));
    s.push_str("#![allow(clippy::approx_constant)]\n\n");

    let layout = crate::blob::Layout::for_model(model);

    // Wrap include_bytes! in an `align(4)` struct so the f32/i32 slice
    // casts below land on naturally-aligned addresses. Without this the
    // BLOB is byte-aligned and `*const f32` reads UB on ARMv7E-M.
    s.push_str(&format!(
        "#[repr(C, align(4))]\n\
         struct AlignedBlob([u8; {len}]);\n\
         const ALIGNED: AlignedBlob = AlignedBlob(*include_bytes!(\"model_weights.bin\"));\n\
         const BLOB: &[u8] = &ALIGNED.0;\n\n",
        len = layout.total_len,
    ));

    s.push_str("// Each slice into BLOB is at an offset chosen by the encoder so the\n");
    s.push_str("// byte boundary is element-aligned (f32 → i32 → i8 region order).\n\n");

    // Weights are exposed as &[i8] regardless of weight_bits — the
    // kernel reads them via `read_weight(w, logical_idx, WEIGHT_BITS)`
    // which translates logical idx → byte + lane. So the slice length
    // is `byte_len` (the storage length), not the logical n_elems.
    push_packed_slice(&mut s, "CONV1_W", layout.conv1_w);
    push_typed_slice(&mut s, "CONV1_B", "i32", layout.conv1_b);
    push_packed_slice(&mut s, "CONV2_W", layout.conv2_w);
    push_typed_slice(&mut s, "CONV2_B", "i32", layout.conv2_b);
    push_packed_slice(&mut s, "FC_W", layout.fc_w);
    push_typed_slice(&mut s, "FC_B", "i32", layout.fc_b);
    push_typed_slice(&mut s, "CONV1_MULT", "f32", layout.conv1_mult);
    push_typed_slice(&mut s, "CONV2_MULT", "f32", layout.conv2_mult);
    push_typed_slice(&mut s, "FC_MULT", "f32", layout.fc_mult);
    s.push('\n');

    // Activation scales as scalar consts — useful for host tooling
    // (compare_weights.py reads X_SCALE; mnist_client doesn't need any
    // of these).
    push_const(&mut s, "X_SCALE", model.x_scale);
    push_const(&mut s, "C1_SCALE", model.c1_scale);
    push_const(&mut s, "P1_SCALE", model.p1_scale);
    push_const(&mut s, "C2_SCALE", model.c2_scale);
    push_const(&mut s, "P2_SCALE", model.p2_scale);
    push_const(&mut s, "FC_OUT_SCALE", model.fc_out_scale);
    s.push('\n');

    s.push_str(&format!(
        "/// Bits per logical weight (8, 4, or 2). Kernel reads each\n\
         /// weight via `read_weight(w, idx, WEIGHT_BITS)` which unpacks\n\
         /// the byte at the right lane.\n\
         pub const WEIGHT_BITS: u8 = {};\n\n",
        model.weight_bits,
    ));

    s.push_str("// One MNIST test image (i8, symmetric) for the e2e test.\n");
    s.push_str(&format!(
        "pub const TEST_LABEL: u8 = {};\n",
        model.test_label
    ));
    push_typed_slice(&mut s, "TEST_IMAGE", "i8", layout.test_image);
    s.push('\n');

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("creating {}: {e}", parent.display()))?;
    }
    fs::write(path, &s).map_err(|e| format!("writing {}: {e}", path.display()))?;
    eprintln!("wrote {} ({} bytes)", path.display(), s.len());
    Ok(())
}

/// Slice cast for typed (non-packed) regions — f32 / i32 / single-byte
/// i8. Length is the element count; offset is element-aligned.
fn push_typed_slice(s: &mut String, name: &str, ty: &str, sl: crate::blob::SliceLoc) {
    // SAFETY: BLOB is aligned to 4 (via AlignedBlob). The encoder lays
    // out the f32 + i32 regions first at 4-aligned offsets, then i8
    // (no alignment requirement). `byte_len == n_elems * elem_size`
    // for these types so reading n_elems is correct.
    s.push_str(&format!(
        "pub static {name}: &[{ty}] = unsafe {{ \
            core::slice::from_raw_parts(BLOB.as_ptr().add({off}) as *const {ty}, {n}) \
        }};\n",
        off = sl.byte_off,
        n = sl.n_elems,
    ));
}

/// Slice cast for a packed-weight region. Exposed as `&[i8]` whose
/// length is the **storage** byte count (`byte_len`), not the logical
/// element count — the kernel walks logical indices through
/// `read_weight(w, idx, WEIGHT_BITS)` which translates to byte+lane.
fn push_packed_slice(s: &mut String, name: &str, sl: crate::blob::SliceLoc) {
    s.push_str(&format!(
        "pub static {name}: &[i8] = unsafe {{ \
            core::slice::from_raw_parts(BLOB.as_ptr().add({off}) as *const i8, {n}) \
        }};\n",
        off = sl.byte_off,
        n = sl.byte_len,
    ));
}

pub fn write_test_set(dataset: &Dataset, args: &Args) -> Result<(), String> {
    if args.val_set_size == 0 {
        return Ok(());
    }
    let n = args.val_set_size.min(dataset.test.len());

    // Path layout matches what `tests/mnist_validate.rs` reads. The
    // canonical case is `--out rlx-cortexm/src/model_weights.rs` →
    // `rlx-cortexm/tests/data/test_set.bin`. We derive the val_dir as
    // `<grandparent of --out>/tests/data` so the same mapping works
    // for any `<crate>/src/model_weights.rs` style layout, and skip
    // gracefully (with a clear info line) when it doesn't.
    let val_dir = match args.out_path.parent().and_then(|p| p.parent()) {
        Some(dir) => dir.join("tests").join("data"),
        None => {
            eprintln!(
                "info: skipping test_set.bin emission — \
                --out {:?} doesn't have a sensible <crate>/src/ parent",
                args.out_path
            );
            return Ok(());
        }
    };
    if let Err(e) = fs::create_dir_all(&val_dir) {
        eprintln!(
            "info: skipping test_set.bin emission — \
            cannot create {}: {e}",
            val_dir.display()
        );
        return Ok(());
    }
    let val_path: PathBuf = val_dir.join("test_set.bin");

    // Reuse x_scale from the model — but emit needs to read it from
    // the freshly-generated file. Simpler: recompute x_scale here from
    // the calibration sweep we already ran. For the test_set.bin we
    // just need to quantize each image with the same x_scale that
    // model_weights.rs uses. Pull it from the file we just wrote.
    let x_scale = read_x_scale(&args.out_path)?;

    let mut f =
        fs::File::create(&val_path).map_err(|e| format!("creating {}: {e}", val_path.display()))?;
    for i in 0..n {
        let img = dataset.test.image(i);
        for &px in img {
            let q = ((px / x_scale).round() as i32).clamp(-127, 127) as i8;
            f.write_all(&[q as u8]).map_err(|e| format!("write: {e}"))?;
        }
        let label = dataset.test.labels[i] as u8;
        f.write_all(&[label]).map_err(|e| format!("write: {e}"))?;
    }
    let bytes = n * (PIXELS + 1);
    eprintln!("wrote {} ({} images, {bytes} bytes)", val_path.display(), n);
    Ok(())
}

fn read_x_scale(model_weights_path: &Path) -> Result<f32, String> {
    let s = fs::read_to_string(model_weights_path)
        .map_err(|e| format!("re-reading {}: {e}", model_weights_path.display()))?;
    // Look for `pub const X_SCALE: f32 = <number>;`.
    let line = s
        .lines()
        .find(|l| l.contains("X_SCALE"))
        .ok_or_else(|| "X_SCALE not found in emitted file".to_string())?;
    let eq = line.find('=').ok_or("no = in X_SCALE line")?;
    let semi = line.find(';').ok_or("no ; in X_SCALE line")?;
    let num = line[eq + 1..semi].trim();
    num.parse::<f32>()
        .map_err(|e| format!("parsing X_SCALE='{num}': {e}"))
}

// ─────────────────────── formatting helpers ──────────────────────

fn push_const(s: &mut String, name: &str, value: f32) {
    s.push_str(&format!("pub const {name}: f32 = {:.9e};\n", value));
}

fn push_arr_i8(s: &mut String, name: &str, arr: &[i8]) {
    s.push_str(&format!("pub static {name}: [i8; {}] = [", arr.len()));
    for (i, v) in arr.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push_str(&v.to_string());
    }
    s.push_str("];\n");
}

fn push_arr_i32(s: &mut String, name: &str, arr: &[i32]) {
    s.push_str(&format!("pub static {name}: [i32; {}] = [", arr.len()));
    for (i, v) in arr.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push_str(&v.to_string());
    }
    s.push_str("];\n");
}
