// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! RLX Google TPU backend — drives `libtpu.so`'s PJRT plugin.
//!
//! ## Architecture
//!
//!   xla/       — prost-generated types compiled from
//!                `proto/xla/{xla_data,service/hlo,service/metrics}.proto`
//!   libtpu.rs  — dlopen + PJRT_Api struct + per-call args structs
//!   device.rs  — process-global PJRT client (Plugin_Initialize +
//!                Client_Create)
//!   hlo.rs     — high-level builder API on top of prost types
//!   lower.rs   — `rlx_ir::Graph` → HLO instruction emission
//!   unfuse.rs  — composite ops decomposed before lowering
//!   backend.rs — `TpuExecutable`: compile, set_param, run

#![allow(clippy::too_many_arguments)]

// Generated by build.rs — vendored xla protos compiled via prost.
// prost-build collapses `xla.service` into `xla` (no nested module);
// every type is reachable as `xla::HloModuleProto` etc.
//
// The doc comments are auto-generated from the .proto files and contain
// `<float>` / `<double>` / `Vec<bool>`-shaped strings that rustdoc
// parses as unclosed HTML tags or unresolved intra-doc links. None of
// that signal is actionable in our code; suppress at the module level.
#[allow(rustdoc::broken_intra_doc_links, rustdoc::invalid_html_tags)]
pub mod xla {
    include!(concat!(env!("OUT_DIR"), "/xla.rs"));
}

pub mod backend;
pub mod device;
pub mod hlo;
pub mod libtpu;
pub mod lower;
pub mod unfuse;

pub use backend::TpuExecutable;

/// True iff a PJRT plugin is loaded *and* Plugin_Initialize +
/// Client_Create succeeded. False on Mac, headless CI, and any host
/// without libtpu (or LIBTPU_PATH pointing at a working plugin).
pub fn is_available() -> bool {
    device::tpu_context().is_some()
}
