// AUTO-GENERATED by rlx-torch-import (flow style) — do not edit by hand.
#![allow(nonstandard_style, unused_imports, unused_mut, unused_variables, dead_code, clippy::all)]

use rlx_flow::{ModelFlow, FlowStage};
use rlx_flow::blocks::CustomStage;
use rlx_ir::HirGraphExt;
use rlx_ir::op::{Activation, MaskKind};

fn rlx_torch_fill(value: f64, dtype: rlx_ir::DType, numel: usize) -> Vec<u8> {
    let one: Vec<u8> = match dtype {
        rlx_ir::DType::F32 => (value as f32).to_le_bytes().to_vec(),
        rlx_ir::DType::F64 => value.to_le_bytes().to_vec(),
        rlx_ir::DType::I64 => (value as i64).to_le_bytes().to_vec(),
        rlx_ir::DType::I32 => (value as i32).to_le_bytes().to_vec(),
        _ => vec![],
    };
    let mut out = Vec::with_capacity(one.len() * numel);
    for _ in 0..numel { out.extend_from_slice(&one); }
    out
}

/// Build a `ModelFlow`; params are pulled from the `WeightSource` at build time.
pub fn build_flow() -> ModelFlow {
    ModelFlow::new("cnn")
        .input("x", rlx_ir::Shape::new(&[2, 3, 16, 16], rlx_ir::DType::F32))
        .stage(FlowStage::Custom(CustomStage::new(|emit, _input| {
            let t_x = emit.flow_input("x")?.hir_id();
            let t_p_c1_weight = emit.load_param("c1.weight", false)?;
            let t_p_c1_bias = emit.load_param("c1.bias", false)?;
            let t_p_b1_weight = emit.load_param("b1.weight", false)?;
            let t_p_b1_bias = emit.load_param("b1.bias", false)?;
            let t_p_c2_weight = emit.load_param("c2.weight", false)?;
            let t_p_c2_bias = emit.load_param("c2.bias", false)?;
            let t_p_b2_weight = emit.load_param("b2.weight", false)?;
            let t_p_b2_bias = emit.load_param("b2.bias", false)?;
            let t_p_head_weight = emit.load_param("head.weight", false)?;
            let t_p_head_bias = emit.load_param("head.bias", false)?;
            let t_b_b1_running_mean = emit.load_param("b1.running_mean", false)?;
            let t_b_b1_running_var = emit.load_param("b1.running_var", false)?;
            let t_b_b1_num_batches_tracked = emit.load_param("b1.num_batches_tracked", false)?;
            let t_b_b2_running_mean = emit.load_param("b2.running_mean", false)?;
            let t_b_b2_running_var = emit.load_param("b2.running_var", false)?;
            let t_b_b2_num_batches_tracked = emit.load_param("b2.num_batches_tracked", false)?;
            let mut b = rlx_ir::hir::HirMut::new(emit.hir());
    let t_convolution__conv = b.conv2d(t_x, t_p_c1_weight, [3, 3], [1, 1], [1, 1], 1, rlx_ir::Shape::new(&[2, 8, 16, 16], rlx_ir::DType::F32));
    let t_convolution__bias = b.reshape_(t_p_c1_bias, vec![1i64, 8i64, 1i64, 1i64]);
    // aten.convolution.default  (x[2, 3, 16, 16], p_c1_weight[8, 3, 3, 3], p_c1_bias[8]) -> [2, 8, 16, 16] f32
    let t_convolution = b.add(t_convolution__conv, t_convolution__bias);
    let bytes_t__native_batch_norm_legit_no_training__scalar = rlx_torch_fill(0.000009999999747378752f64, rlx_ir::DType::F32, 1);
    let t__native_batch_norm_legit_no_training__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t__native_batch_norm_legit_no_training__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    let t__native_batch_norm_legit_no_training__vpe = b.add(t_b_b1_running_var, t__native_batch_norm_legit_no_training__scalar);
    let s_t__native_batch_norm_legit_no_training__inv = b.shape(t__native_batch_norm_legit_no_training__vpe).clone();
    let t__native_batch_norm_legit_no_training__inv = b.activation(Activation::Rsqrt, t__native_batch_norm_legit_no_training__vpe, s_t__native_batch_norm_legit_no_training__inv);
    let t__native_batch_norm_legit_no_training__scale = b.mul(t_p_b1_weight, t__native_batch_norm_legit_no_training__inv);
    let t__native_batch_norm_legit_no_training__ms = b.mul(t_b_b1_running_mean, t__native_batch_norm_legit_no_training__scale);
    let t__native_batch_norm_legit_no_training__shift = b.sub(t_p_b1_bias, t__native_batch_norm_legit_no_training__ms);
    let t__native_batch_norm_legit_no_training__scr = b.reshape_(t__native_batch_norm_legit_no_training__scale, vec![1i64, 8i64, 1i64, 1i64]);
    let t__native_batch_norm_legit_no_training__shr = b.reshape_(t__native_batch_norm_legit_no_training__shift, vec![1i64, 8i64, 1i64, 1i64]);
    let t__native_batch_norm_legit_no_training__xs = b.mul(t_convolution, t__native_batch_norm_legit_no_training__scr);
    // aten._native_batch_norm_legit_no_training.default  (convolution[2, 8, 16, 16], p_b1_weight[8], p_b1_bias[8], b_b1_running_mean[8], b_b1_running_var[8]) -> [2, 8, 16, 16] f32
    let t__native_batch_norm_legit_no_training = b.add(t__native_batch_norm_legit_no_training__xs, t__native_batch_norm_legit_no_training__shr);
    // aten.relu.default  (getitem[2, 8, 16, 16]) -> [2, 8, 16, 16] f32
    let s_t_relu = b.shape(t__native_batch_norm_legit_no_training).clone();
    let t_relu = b.activation(Activation::Relu, t__native_batch_norm_legit_no_training, s_t_relu);
    // aten.max_pool2d_with_indices.default  (relu[2, 8, 16, 16]) -> [2, 8, 8, 8] f32
    let t_max_pool2d_with_indices = b.add_node(rlx_ir::Op::Pool { kind: rlx_ir::op::ReduceOp::Max, kernel_size: vec![2usize, 2usize], stride: vec![2usize, 2usize], padding: vec![0usize, 0usize] }, vec![t_relu], rlx_ir::Shape::new(&[2, 8, 8, 8], rlx_ir::DType::F32));
    let t_convolution_1__conv = b.conv2d(t_max_pool2d_with_indices, t_p_c2_weight, [3, 3], [1, 1], [1, 1], 1, rlx_ir::Shape::new(&[2, 16, 8, 8], rlx_ir::DType::F32));
    let t_convolution_1__bias = b.reshape_(t_p_c2_bias, vec![1i64, 16i64, 1i64, 1i64]);
    // aten.convolution.default  (getitem_3[2, 8, 8, 8], p_c2_weight[16, 8, 3, 3], p_c2_bias[16]) -> [2, 16, 8, 8] f32
    let t_convolution_1 = b.add(t_convolution_1__conv, t_convolution_1__bias);
    let bytes_t__native_batch_norm_legit_no_training_1__scalar = rlx_torch_fill(0.000009999999747378752f64, rlx_ir::DType::F32, 1);
    let t__native_batch_norm_legit_no_training_1__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t__native_batch_norm_legit_no_training_1__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    let t__native_batch_norm_legit_no_training_1__vpe = b.add(t_b_b2_running_var, t__native_batch_norm_legit_no_training_1__scalar);
    let s_t__native_batch_norm_legit_no_training_1__inv = b.shape(t__native_batch_norm_legit_no_training_1__vpe).clone();
    let t__native_batch_norm_legit_no_training_1__inv = b.activation(Activation::Rsqrt, t__native_batch_norm_legit_no_training_1__vpe, s_t__native_batch_norm_legit_no_training_1__inv);
    let t__native_batch_norm_legit_no_training_1__scale = b.mul(t_p_b2_weight, t__native_batch_norm_legit_no_training_1__inv);
    let t__native_batch_norm_legit_no_training_1__ms = b.mul(t_b_b2_running_mean, t__native_batch_norm_legit_no_training_1__scale);
    let t__native_batch_norm_legit_no_training_1__shift = b.sub(t_p_b2_bias, t__native_batch_norm_legit_no_training_1__ms);
    let t__native_batch_norm_legit_no_training_1__scr = b.reshape_(t__native_batch_norm_legit_no_training_1__scale, vec![1i64, 16i64, 1i64, 1i64]);
    let t__native_batch_norm_legit_no_training_1__shr = b.reshape_(t__native_batch_norm_legit_no_training_1__shift, vec![1i64, 16i64, 1i64, 1i64]);
    let t__native_batch_norm_legit_no_training_1__xs = b.mul(t_convolution_1, t__native_batch_norm_legit_no_training_1__scr);
    // aten._native_batch_norm_legit_no_training.default  (convolution_1[2, 16, 8, 8], p_b2_weight[16], p_b2_bias[16], b_b2_running_mean[16], b_b2_running_var[16]) -> [2, 16, 8, 8] f32
    let t__native_batch_norm_legit_no_training_1 = b.add(t__native_batch_norm_legit_no_training_1__xs, t__native_batch_norm_legit_no_training_1__shr);
    // aten.relu.default  (getitem_5[2, 16, 8, 8]) -> [2, 16, 8, 8] f32
    let s_t_relu_1 = b.shape(t__native_batch_norm_legit_no_training_1).clone();
    let t_relu_1 = b.activation(Activation::Relu, t__native_batch_norm_legit_no_training_1, s_t_relu_1);
    // aten.mean.dim  (relu_1[2, 16, 8, 8]) -> [2, 16, 1, 1] f32
    let t_mean = b.mean(t_relu_1, vec![3usize, 2usize], true);
    // aten.view.default  (mean[2, 16, 1, 1]) -> [2, 16] f32
    let t_view = b.reshape_(t_mean, vec![2i64, 16i64]);
    // aten.permute.default  (p_head_weight[10, 16]) -> [16, 10] f32
    let t_permute = b.transpose_(t_p_head_weight, vec![1usize, 0usize]);
    let t_addmm__mm = b.mm(t_view, t_permute);
    // aten.addmm.default  (p_head_bias[10], view[2, 16], permute[16, 10]) -> [2, 10] f32
    let t_addmm = b.add(t_addmm__mm, t_p_head_bias);
            let out_shape = b.shape(t_addmm).clone();
            drop(b);
            Ok(Some(emit.wrap(t_addmm, out_shape)))
        })))
        .output("output")
}
