// AUTO-GENERATED by rlx-torch-import (flow style) — do not edit by hand.
// SPDX-License-Identifier: MIT OR Apache-2.0
#![allow(nonstandard_style, unused_imports, unused_mut, unused_variables, dead_code, clippy::all)]

use rlx_flow::{ModelFlow, FlowStage};
use rlx_flow::blocks::CustomStage;
use rlx_ir::HirGraphExt;
use rlx_ir::op::{Activation, MaskKind};

fn rlx_torch_fill(value: f64, dtype: rlx_ir::DType, numel: usize) -> Vec<u8> {
    let one: Vec<u8> = match dtype {
        rlx_ir::DType::F32 => (value as f32).to_le_bytes().to_vec(),
        rlx_ir::DType::F64 => value.to_le_bytes().to_vec(),
        rlx_ir::DType::I64 => (value as i64).to_le_bytes().to_vec(),
        rlx_ir::DType::I32 => (value as i32).to_le_bytes().to_vec(),
        _ => vec![],
    };
    let mut out = Vec::with_capacity(one.len() * numel);
    for _ in 0..numel { out.extend_from_slice(&one); }
    out
}

/// Build a `ModelFlow`; params are pulled from the `WeightSource` at build time.
pub fn build_flow() -> ModelFlow {
    ModelFlow::new("encoder_decoder")
        .input("src", rlx_ir::Shape::new(&[1, 5, 32], rlx_ir::DType::F32))
        .input("tgt", rlx_ir::Shape::new(&[1, 3, 32], rlx_ir::DType::F32))
        .stage(FlowStage::Custom(CustomStage::new(|emit, _input| {
            let t_src = emit.flow_input("src")?.hir_id();
            let t_tgt = emit.flow_input("tgt")?.hir_id();
            let t_p_enc_p_q_weight = emit.load_param("enc.p.q.weight", false)?;
            let t_p_enc_p_k_weight = emit.load_param("enc.p.k.weight", false)?;
            let t_p_enc_p_v_weight = emit.load_param("enc.p.v.weight", false)?;
            let t_p_enc_p_o_weight = emit.load_param("enc.p.o.weight", false)?;
            let t_p_dec_self_p_q_weight = emit.load_param("dec_self.p.q.weight", false)?;
            let t_p_dec_self_p_k_weight = emit.load_param("dec_self.p.k.weight", false)?;
            let t_p_dec_self_p_v_weight = emit.load_param("dec_self.p.v.weight", false)?;
            let t_p_dec_self_p_o_weight = emit.load_param("dec_self.p.o.weight", false)?;
            let t_p_dec_cross_p_q_weight = emit.load_param("dec_cross.p.q.weight", false)?;
            let t_p_dec_cross_p_k_weight = emit.load_param("dec_cross.p.k.weight", false)?;
            let t_p_dec_cross_p_v_weight = emit.load_param("dec_cross.p.v.weight", false)?;
            let t_p_dec_cross_p_o_weight = emit.load_param("dec_cross.p.o.weight", false)?;
            let t_p_n_0_weight = emit.load_param("n.0.weight", false)?;
            let t_p_n_0_bias = emit.load_param("n.0.bias", false)?;
            let t_p_n_1_weight = emit.load_param("n.1.weight", false)?;
            let t_p_n_1_bias = emit.load_param("n.1.bias", false)?;
            let t_p_n_2_weight = emit.load_param("n.2.weight", false)?;
            let t_p_n_2_bias = emit.load_param("n.2.bias", false)?;
            let mut b = rlx_ir::hir::HirMut::new(emit.hir());
    // aten.layer_norm.default  (src[1, 5, 32], p_n_0_weight[32], p_n_0_bias[32]) -> [1, 5, 32] f32
    let t_layer_norm = b.ln(t_src, t_p_n_0_weight, t_p_n_0_bias, 0.00001f32);
    // aten.layer_norm.default  (src[1, 5, 32], p_n_0_weight[32], p_n_0_bias[32]) -> [1, 5, 32] f32
    let t_layer_norm_1 = b.ln(t_src, t_p_n_0_weight, t_p_n_0_bias, 0.00001f32);
    // aten.permute.default  (p_enc_p_q_weight[32, 32]) -> [32, 32] f32
    let t_permute = b.transpose_(t_p_enc_p_q_weight, vec![1usize, 0usize]);
    // aten.view.default  (layer_norm[1, 5, 32]) -> [5, 32] f32
    let t_view = b.reshape_(t_layer_norm, vec![5i64, 32i64]);
    // aten.mm.default  (view[5, 32], permute[32, 32]) -> [5, 32] f32
    let t_mm = b.mm(t_view, t_permute);
    // aten.view.default  (mm[5, 32]) -> [1, 5, 32] f32
    let t_view_1 = b.reshape_(t_mm, vec![1i64, 5i64, 32i64]);
    // aten.view.default  (view_1[1, 5, 32]) -> [1, 5, 4, 8] f32
    let t_view_2 = b.reshape_(t_view_1, vec![1i64, 5i64, 4i64, 8i64]);
    // aten.permute.default  (view_2[1, 5, 4, 8]) -> [1, 4, 5, 8] f32
    let t_permute_1 = b.transpose_(t_view_2, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.permute.default  (p_enc_p_k_weight[32, 32]) -> [32, 32] f32
    let t_permute_2 = b.transpose_(t_p_enc_p_k_weight, vec![1usize, 0usize]);
    // aten.view.default  (layer_norm_1[1, 5, 32]) -> [5, 32] f32
    let t_view_3 = b.reshape_(t_layer_norm_1, vec![5i64, 32i64]);
    // aten.mm.default  (view_3[5, 32], permute_2[32, 32]) -> [5, 32] f32
    let t_mm_1 = b.mm(t_view_3, t_permute_2);
    // aten.view.default  (mm_1[5, 32]) -> [1, 5, 32] f32
    let t_view_4 = b.reshape_(t_mm_1, vec![1i64, 5i64, 32i64]);
    // aten.view.default  (view_4[1, 5, 32]) -> [1, 5, 4, 8] f32
    let t_view_5 = b.reshape_(t_view_4, vec![1i64, 5i64, 4i64, 8i64]);
    // aten.permute.default  (view_5[1, 5, 4, 8]) -> [1, 4, 5, 8] f32
    let t_permute_3 = b.transpose_(t_view_5, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.permute.default  (p_enc_p_v_weight[32, 32]) -> [32, 32] f32
    let t_permute_4 = b.transpose_(t_p_enc_p_v_weight, vec![1usize, 0usize]);
    // aten.view.default  (layer_norm_1[1, 5, 32]) -> [5, 32] f32
    let t_view_6 = b.reshape_(t_layer_norm_1, vec![5i64, 32i64]);
    // aten.mm.default  (view_6[5, 32], permute_4[32, 32]) -> [5, 32] f32
    let t_mm_2 = b.mm(t_view_6, t_permute_4);
    // aten.view.default  (mm_2[5, 32]) -> [1, 5, 32] f32
    let t_view_7 = b.reshape_(t_mm_2, vec![1i64, 5i64, 32i64]);
    // aten.view.default  (view_7[1, 5, 32]) -> [1, 5, 4, 8] f32
    let t_view_8 = b.reshape_(t_view_7, vec![1i64, 5i64, 4i64, 8i64]);
    // aten.permute.default  (view_8[1, 5, 4, 8]) -> [1, 4, 5, 8] f32
    let t_permute_5 = b.transpose_(t_view_8, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.scaled_dot_product_attention.default  (permute_1[1, 4, 5, 8], permute_3[1, 4, 5, 8], permute_5[1, 4, 5, 8]) -> [1, 4, 5, 8] f32
    let t_scaled_dot_product_attention = b.attention_kind(t_permute_1, t_permute_3, t_permute_5, 4, 8, MaskKind::None, rlx_ir::Shape::new(&[1, 4, 5, 8], rlx_ir::DType::F32));
    // aten.permute.default  (scaled_dot_product_attention[1, 4, 5, 8]) -> [1, 5, 4, 8] f32
    let t_permute_6 = b.transpose_(t_scaled_dot_product_attention, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.view.default  (permute_6[1, 5, 4, 8]) -> [1, 5, 32] f32
    let t_view_9 = b.reshape_(t_permute_6, vec![1i64, 5i64, 32i64]);
    // aten.permute.default  (p_enc_p_o_weight[32, 32]) -> [32, 32] f32
    let t_permute_7 = b.transpose_(t_p_enc_p_o_weight, vec![1usize, 0usize]);
    // aten.view.default  (view_9[1, 5, 32]) -> [5, 32] f32
    let t_view_10 = b.reshape_(t_view_9, vec![5i64, 32i64]);
    // aten.mm.default  (view_10[5, 32], permute_7[32, 32]) -> [5, 32] f32
    let t_mm_3 = b.mm(t_view_10, t_permute_7);
    // aten.view.default  (mm_3[5, 32]) -> [1, 5, 32] f32
    let t_view_11 = b.reshape_(t_mm_3, vec![1i64, 5i64, 32i64]);
    // aten.add.Tensor  (src[1, 5, 32], view_11[1, 5, 32]) -> [1, 5, 32] f32
    let t_add = b.add(t_src, t_view_11);
    // aten.layer_norm.default  (tgt[1, 3, 32], p_n_1_weight[32], p_n_1_bias[32]) -> [1, 3, 32] f32
    let t_layer_norm_2 = b.ln(t_tgt, t_p_n_1_weight, t_p_n_1_bias, 0.00001f32);
    // aten.layer_norm.default  (tgt[1, 3, 32], p_n_1_weight[32], p_n_1_bias[32]) -> [1, 3, 32] f32
    let t_layer_norm_3 = b.ln(t_tgt, t_p_n_1_weight, t_p_n_1_bias, 0.00001f32);
    // aten.permute.default  (p_dec_self_p_q_weight[32, 32]) -> [32, 32] f32
    let t_permute_8 = b.transpose_(t_p_dec_self_p_q_weight, vec![1usize, 0usize]);
    // aten.view.default  (layer_norm_2[1, 3, 32]) -> [3, 32] f32
    let t_view_12 = b.reshape_(t_layer_norm_2, vec![3i64, 32i64]);
    // aten.mm.default  (view_12[3, 32], permute_8[32, 32]) -> [3, 32] f32
    let t_mm_4 = b.mm(t_view_12, t_permute_8);
    // aten.view.default  (mm_4[3, 32]) -> [1, 3, 32] f32
    let t_view_13 = b.reshape_(t_mm_4, vec![1i64, 3i64, 32i64]);
    // aten.view.default  (view_13[1, 3, 32]) -> [1, 3, 4, 8] f32
    let t_view_14 = b.reshape_(t_view_13, vec![1i64, 3i64, 4i64, 8i64]);
    // aten.permute.default  (view_14[1, 3, 4, 8]) -> [1, 4, 3, 8] f32
    let t_permute_9 = b.transpose_(t_view_14, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.permute.default  (p_dec_self_p_k_weight[32, 32]) -> [32, 32] f32
    let t_permute_10 = b.transpose_(t_p_dec_self_p_k_weight, vec![1usize, 0usize]);
    // aten.view.default  (layer_norm_3[1, 3, 32]) -> [3, 32] f32
    let t_view_15 = b.reshape_(t_layer_norm_3, vec![3i64, 32i64]);
    // aten.mm.default  (view_15[3, 32], permute_10[32, 32]) -> [3, 32] f32
    let t_mm_5 = b.mm(t_view_15, t_permute_10);
    // aten.view.default  (mm_5[3, 32]) -> [1, 3, 32] f32
    let t_view_16 = b.reshape_(t_mm_5, vec![1i64, 3i64, 32i64]);
    // aten.view.default  (view_16[1, 3, 32]) -> [1, 3, 4, 8] f32
    let t_view_17 = b.reshape_(t_view_16, vec![1i64, 3i64, 4i64, 8i64]);
    // aten.permute.default  (view_17[1, 3, 4, 8]) -> [1, 4, 3, 8] f32
    let t_permute_11 = b.transpose_(t_view_17, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.permute.default  (p_dec_self_p_v_weight[32, 32]) -> [32, 32] f32
    let t_permute_12 = b.transpose_(t_p_dec_self_p_v_weight, vec![1usize, 0usize]);
    // aten.view.default  (layer_norm_3[1, 3, 32]) -> [3, 32] f32
    let t_view_18 = b.reshape_(t_layer_norm_3, vec![3i64, 32i64]);
    // aten.mm.default  (view_18[3, 32], permute_12[32, 32]) -> [3, 32] f32
    let t_mm_6 = b.mm(t_view_18, t_permute_12);
    // aten.view.default  (mm_6[3, 32]) -> [1, 3, 32] f32
    let t_view_19 = b.reshape_(t_mm_6, vec![1i64, 3i64, 32i64]);
    // aten.view.default  (view_19[1, 3, 32]) -> [1, 3, 4, 8] f32
    let t_view_20 = b.reshape_(t_view_19, vec![1i64, 3i64, 4i64, 8i64]);
    // aten.permute.default  (view_20[1, 3, 4, 8]) -> [1, 4, 3, 8] f32
    let t_permute_13 = b.transpose_(t_view_20, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.scaled_dot_product_attention.default  (permute_9[1, 4, 3, 8], permute_11[1, 4, 3, 8], permute_13[1, 4, 3, 8]) -> [1, 4, 3, 8] f32
    let t_scaled_dot_product_attention_1 = b.attention_kind(t_permute_9, t_permute_11, t_permute_13, 4, 8, MaskKind::None, rlx_ir::Shape::new(&[1, 4, 3, 8], rlx_ir::DType::F32));
    // aten.permute.default  (scaled_dot_product_attention_1[1, 4, 3, 8]) -> [1, 3, 4, 8] f32
    let t_permute_14 = b.transpose_(t_scaled_dot_product_attention_1, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.view.default  (permute_14[1, 3, 4, 8]) -> [1, 3, 32] f32
    let t_view_21 = b.reshape_(t_permute_14, vec![1i64, 3i64, 32i64]);
    // aten.permute.default  (p_dec_self_p_o_weight[32, 32]) -> [32, 32] f32
    let t_permute_15 = b.transpose_(t_p_dec_self_p_o_weight, vec![1usize, 0usize]);
    // aten.view.default  (view_21[1, 3, 32]) -> [3, 32] f32
    let t_view_22 = b.reshape_(t_view_21, vec![3i64, 32i64]);
    // aten.mm.default  (view_22[3, 32], permute_15[32, 32]) -> [3, 32] f32
    let t_mm_7 = b.mm(t_view_22, t_permute_15);
    // aten.view.default  (mm_7[3, 32]) -> [1, 3, 32] f32
    let t_view_23 = b.reshape_(t_mm_7, vec![1i64, 3i64, 32i64]);
    // aten.add.Tensor  (tgt[1, 3, 32], view_23[1, 3, 32]) -> [1, 3, 32] f32
    let t_add_1 = b.add(t_tgt, t_view_23);
    // aten.layer_norm.default  (add_1[1, 3, 32], p_n_2_weight[32], p_n_2_bias[32]) -> [1, 3, 32] f32
    let t_layer_norm_4 = b.ln(t_add_1, t_p_n_2_weight, t_p_n_2_bias, 0.00001f32);
    // aten.permute.default  (p_dec_cross_p_q_weight[32, 32]) -> [32, 32] f32
    let t_permute_16 = b.transpose_(t_p_dec_cross_p_q_weight, vec![1usize, 0usize]);
    // aten.view.default  (layer_norm_4[1, 3, 32]) -> [3, 32] f32
    let t_view_24 = b.reshape_(t_layer_norm_4, vec![3i64, 32i64]);
    // aten.mm.default  (view_24[3, 32], permute_16[32, 32]) -> [3, 32] f32
    let t_mm_8 = b.mm(t_view_24, t_permute_16);
    // aten.view.default  (mm_8[3, 32]) -> [1, 3, 32] f32
    let t_view_25 = b.reshape_(t_mm_8, vec![1i64, 3i64, 32i64]);
    // aten.view.default  (view_25[1, 3, 32]) -> [1, 3, 4, 8] f32
    let t_view_26 = b.reshape_(t_view_25, vec![1i64, 3i64, 4i64, 8i64]);
    // aten.permute.default  (view_26[1, 3, 4, 8]) -> [1, 4, 3, 8] f32
    let t_permute_17 = b.transpose_(t_view_26, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.permute.default  (p_dec_cross_p_k_weight[32, 32]) -> [32, 32] f32
    let t_permute_18 = b.transpose_(t_p_dec_cross_p_k_weight, vec![1usize, 0usize]);
    // aten.view.default  (add[1, 5, 32]) -> [5, 32] f32
    let t_view_27 = b.reshape_(t_add, vec![5i64, 32i64]);
    // aten.mm.default  (view_27[5, 32], permute_18[32, 32]) -> [5, 32] f32
    let t_mm_9 = b.mm(t_view_27, t_permute_18);
    // aten.view.default  (mm_9[5, 32]) -> [1, 5, 32] f32
    let t_view_28 = b.reshape_(t_mm_9, vec![1i64, 5i64, 32i64]);
    // aten.view.default  (view_28[1, 5, 32]) -> [1, 5, 4, 8] f32
    let t_view_29 = b.reshape_(t_view_28, vec![1i64, 5i64, 4i64, 8i64]);
    // aten.permute.default  (view_29[1, 5, 4, 8]) -> [1, 4, 5, 8] f32
    let t_permute_19 = b.transpose_(t_view_29, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.permute.default  (p_dec_cross_p_v_weight[32, 32]) -> [32, 32] f32
    let t_permute_20 = b.transpose_(t_p_dec_cross_p_v_weight, vec![1usize, 0usize]);
    // aten.view.default  (add[1, 5, 32]) -> [5, 32] f32
    let t_view_30 = b.reshape_(t_add, vec![5i64, 32i64]);
    // aten.mm.default  (view_30[5, 32], permute_20[32, 32]) -> [5, 32] f32
    let t_mm_10 = b.mm(t_view_30, t_permute_20);
    // aten.view.default  (mm_10[5, 32]) -> [1, 5, 32] f32
    let t_view_31 = b.reshape_(t_mm_10, vec![1i64, 5i64, 32i64]);
    // aten.view.default  (view_31[1, 5, 32]) -> [1, 5, 4, 8] f32
    let t_view_32 = b.reshape_(t_view_31, vec![1i64, 5i64, 4i64, 8i64]);
    // aten.permute.default  (view_32[1, 5, 4, 8]) -> [1, 4, 5, 8] f32
    let t_permute_21 = b.transpose_(t_view_32, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.scaled_dot_product_attention.default  (permute_17[1, 4, 3, 8], permute_19[1, 4, 5, 8], permute_21[1, 4, 5, 8]) -> [1, 4, 3, 8] f32
    let t_scaled_dot_product_attention_2 = b.attention_kind(t_permute_17, t_permute_19, t_permute_21, 4, 8, MaskKind::None, rlx_ir::Shape::new(&[1, 4, 3, 8], rlx_ir::DType::F32));
    // aten.permute.default  (scaled_dot_product_attention_2[1, 4, 3, 8]) -> [1, 3, 4, 8] f32
    let t_permute_22 = b.transpose_(t_scaled_dot_product_attention_2, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.view.default  (permute_22[1, 3, 4, 8]) -> [1, 3, 32] f32
    let t_view_33 = b.reshape_(t_permute_22, vec![1i64, 3i64, 32i64]);
    // aten.permute.default  (p_dec_cross_p_o_weight[32, 32]) -> [32, 32] f32
    let t_permute_23 = b.transpose_(t_p_dec_cross_p_o_weight, vec![1usize, 0usize]);
    // aten.view.default  (view_33[1, 3, 32]) -> [3, 32] f32
    let t_view_34 = b.reshape_(t_view_33, vec![3i64, 32i64]);
    // aten.mm.default  (view_34[3, 32], permute_23[32, 32]) -> [3, 32] f32
    let t_mm_11 = b.mm(t_view_34, t_permute_23);
    // aten.view.default  (mm_11[3, 32]) -> [1, 3, 32] f32
    let t_view_35 = b.reshape_(t_mm_11, vec![1i64, 3i64, 32i64]);
    // aten.add.Tensor  (add_1[1, 3, 32], view_35[1, 3, 32]) -> [1, 3, 32] f32
    let t_add_2 = b.add(t_add_1, t_view_35);
            let out_shape = b.shape(t_add_2).clone();
            drop(b);
            Ok(Some(emit.wrap(t_add_2, out_shape)))
        })))
        .output("output")
}
