// AUTO-GENERATED by rlx-torch-import (flow style) — do not edit by hand.
// SPDX-License-Identifier: MIT OR Apache-2.0
#![allow(nonstandard_style, unused_imports, unused_mut, unused_variables, dead_code, clippy::all)]

use rlx_flow::{ModelFlow, FlowStage};
use rlx_flow::blocks::CustomStage;
use rlx_ir::HirGraphExt;
use rlx_ir::op::{Activation, MaskKind};

fn rlx_torch_fill(value: f64, dtype: rlx_ir::DType, numel: usize) -> Vec<u8> {
    let one: Vec<u8> = match dtype {
        rlx_ir::DType::F32 => (value as f32).to_le_bytes().to_vec(),
        rlx_ir::DType::F64 => value.to_le_bytes().to_vec(),
        rlx_ir::DType::I64 => (value as i64).to_le_bytes().to_vec(),
        rlx_ir::DType::I32 => (value as i32).to_le_bytes().to_vec(),
        _ => vec![],
    };
    let mut out = Vec::with_capacity(one.len() * numel);
    for _ in 0..numel { out.extend_from_slice(&one); }
    out
}

/// Build a `ModelFlow`; params are pulled from the `WeightSource` at build time.
pub fn build_flow() -> ModelFlow {
    ModelFlow::new("llama")
        .input("ids", rlx_ir::Shape::new(&[1, 8], rlx_ir::DType::I64))
        .stage(FlowStage::Custom(CustomStage::new(|emit, _input| {
            let t_ids = emit.flow_input("ids")?.hir_id();
            let t_p_m_model_embed_tokens_weight = emit.load_param("m.model.embed_tokens.weight", false)?;
            let t_p_m_model_layers_0_self_attn_q_proj_weight = emit.load_param("m.model.layers.0.self_attn.q_proj.weight", false)?;
            let t_p_m_model_layers_0_self_attn_k_proj_weight = emit.load_param("m.model.layers.0.self_attn.k_proj.weight", false)?;
            let t_p_m_model_layers_0_self_attn_v_proj_weight = emit.load_param("m.model.layers.0.self_attn.v_proj.weight", false)?;
            let t_p_m_model_layers_0_self_attn_o_proj_weight = emit.load_param("m.model.layers.0.self_attn.o_proj.weight", false)?;
            let t_p_m_model_layers_0_mlp_gate_proj_weight = emit.load_param("m.model.layers.0.mlp.gate_proj.weight", false)?;
            let t_p_m_model_layers_0_mlp_up_proj_weight = emit.load_param("m.model.layers.0.mlp.up_proj.weight", false)?;
            let t_p_m_model_layers_0_mlp_down_proj_weight = emit.load_param("m.model.layers.0.mlp.down_proj.weight", false)?;
            let t_p_m_model_layers_0_input_layernorm_weight = emit.load_param("m.model.layers.0.input_layernorm.weight", false)?;
            let t_p_m_model_layers_0_post_attention_layernorm_weight = emit.load_param("m.model.layers.0.post_attention_layernorm.weight", false)?;
            let t_p_m_model_layers_1_self_attn_q_proj_weight = emit.load_param("m.model.layers.1.self_attn.q_proj.weight", false)?;
            let t_p_m_model_layers_1_self_attn_k_proj_weight = emit.load_param("m.model.layers.1.self_attn.k_proj.weight", false)?;
            let t_p_m_model_layers_1_self_attn_v_proj_weight = emit.load_param("m.model.layers.1.self_attn.v_proj.weight", false)?;
            let t_p_m_model_layers_1_self_attn_o_proj_weight = emit.load_param("m.model.layers.1.self_attn.o_proj.weight", false)?;
            let t_p_m_model_layers_1_mlp_gate_proj_weight = emit.load_param("m.model.layers.1.mlp.gate_proj.weight", false)?;
            let t_p_m_model_layers_1_mlp_up_proj_weight = emit.load_param("m.model.layers.1.mlp.up_proj.weight", false)?;
            let t_p_m_model_layers_1_mlp_down_proj_weight = emit.load_param("m.model.layers.1.mlp.down_proj.weight", false)?;
            let t_p_m_model_layers_1_input_layernorm_weight = emit.load_param("m.model.layers.1.input_layernorm.weight", false)?;
            let t_p_m_model_layers_1_post_attention_layernorm_weight = emit.load_param("m.model.layers.1.post_attention_layernorm.weight", false)?;
            let t_p_m_model_norm_weight = emit.load_param("m.model.norm.weight", false)?;
            let t_p_m_lm_head_weight = emit.load_param("m.lm_head.weight", false)?;
            let t_c_m_model_layers_0_self_attn_lifted_tensor_0 = emit.load_param("m.model.layers.0.self_attn.lifted_tensor_0", false)?;
            let t_c_m_model_layers_0_self_attn_lifted_tensor_1 = emit.load_param("m.model.layers.0.self_attn.lifted_tensor_1", false)?;
            let t_c_m_model_layers_1_self_attn_lifted_tensor_2 = emit.load_param("m.model.layers.1.self_attn.lifted_tensor_2", false)?;
            let t_c_m_model_layers_1_self_attn_lifted_tensor_3 = emit.load_param("m.model.layers.1.self_attn.lifted_tensor_3", false)?;
            let t_b_m_model_rotary_emb_inv_freq = emit.load_param("m.model.rotary_emb.inv_freq", false)?;
            let t_b_m_model_rotary_emb_original_inv_freq = emit.load_param("m.model.rotary_emb.original_inv_freq", false)?;
            let mut b = rlx_ir::hir::HirMut::new(emit.hir());
    // aten.embedding.default  (p_m_model_embed_tokens_weight[64, 32], ids[1, 8]) -> [1, 8, 32] f32
    let t_embedding = b.gather_(t_p_m_model_embed_tokens_weight, t_ids, 0);
    // aten.arange.start_step  () -> [8] i64
    let mut bytes_t_arange: Vec<u8> = Vec::new();
    for i in 0..8usize { let v = 0f64 + (i as f64) * 1f64; bytes_t_arange.extend_from_slice(&(v as i64).to_le_bytes()); }
    let t_arange = b.add_node(rlx_ir::Op::Constant { data: bytes_t_arange }, vec![], rlx_ir::Shape::new(&[8], rlx_ir::DType::I64));
    let bytes_t_add__scalar = rlx_torch_fill(0f64, rlx_ir::DType::I64, 1);
    let t_add__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_add__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::I64));
    // aten.add.Tensor  (arange[8]) -> [8] i64
    let t_add = b.add(t_arange, t_add__scalar);
    // aten.unsqueeze.default  (add[8]) -> [1, 8] i64
    let t_unsqueeze = b.reshape_(t_add, vec![1i64, 8i64]);
    // aten.arange.start_step  () -> [8] i64
    let mut bytes_t_arange_3: Vec<u8> = Vec::new();
    for i in 0..8usize { let v = 0f64 + (i as f64) * 1f64; bytes_t_arange_3.extend_from_slice(&(v as i64).to_le_bytes()); }
    let t_arange_3 = b.add_node(rlx_ir::Op::Constant { data: bytes_t_arange_3 }, vec![], rlx_ir::Shape::new(&[8], rlx_ir::DType::I64));
    let bytes_t_add_1__scalar = rlx_torch_fill(0f64, rlx_ir::DType::I64, 1);
    let t_add_1__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_add_1__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::I64));
    // aten.add.Tensor  (arange_3[8]) -> [8] i64
    let t_add_1 = b.add(t_arange_3, t_add_1__scalar);
    // aten.arange.start_step  () -> [8] i64
    let mut bytes_t_arange_4: Vec<u8> = Vec::new();
    for i in 0..8usize { let v = 0f64 + (i as f64) * 1f64; bytes_t_arange_4.extend_from_slice(&(v as i64).to_le_bytes()); }
    let t_arange_4 = b.add_node(rlx_ir::Op::Constant { data: bytes_t_arange_4 }, vec![], rlx_ir::Shape::new(&[8], rlx_ir::DType::I64));
    let bytes_t_add_2__scalar = rlx_torch_fill(0f64, rlx_ir::DType::I64, 1);
    let t_add_2__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_add_2__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::I64));
    // aten.add.Tensor  (arange_4[8]) -> [8] i64
    let t_add_2 = b.add(t_arange_4, t_add_2__scalar);
    // aten.unsqueeze.default  (add_1[8]) -> [1, 8] i64
    let t_unsqueeze_7 = b.reshape_(t_add_1, vec![1i64, 8i64]);
    // aten.unsqueeze.default  (unsqueeze_7[1, 8]) -> [1, 1, 8] i64
    let t_unsqueeze_8 = b.reshape_(t_unsqueeze_7, vec![1i64, 1i64, 8i64]);
    // aten.unsqueeze.default  (unsqueeze_8[1, 1, 8]) -> [1, 1, 8, 1] i64
    let t_unsqueeze_9 = b.reshape_(t_unsqueeze_8, vec![1i64, 1i64, 8i64, 1i64]);
    // aten.unsqueeze.default  (add_2[8]) -> [1, 8] i64
    let t_unsqueeze_10 = b.reshape_(t_add_2, vec![1i64, 8i64]);
    // aten.unsqueeze.default  (unsqueeze_10[1, 8]) -> [1, 1, 8] i64
    let t_unsqueeze_11 = b.reshape_(t_unsqueeze_10, vec![1i64, 1i64, 8i64]);
    // aten.unsqueeze.default  (unsqueeze_11[1, 1, 8]) -> [1, 1, 1, 8] i64
    let t_unsqueeze_12 = b.reshape_(t_unsqueeze_11, vec![1i64, 1i64, 1i64, 8i64]);
    let t_unsqueeze_12__bca = b.add_node(rlx_ir::Op::Expand { target_shape: vec![1i64, 1i64, 8i64, 8i64] }, vec![t_unsqueeze_12], rlx_ir::Shape::new(&[1, 1, 8, 8], rlx_ir::DType::I64));
    let t_unsqueeze_9__bcb = b.add_node(rlx_ir::Op::Expand { target_shape: vec![1i64, 1i64, 8i64, 8i64] }, vec![t_unsqueeze_9], rlx_ir::Shape::new(&[1, 1, 8, 8], rlx_ir::DType::I64));
    // aten.le.Tensor  (unsqueeze_12[1, 1, 1, 8], unsqueeze_9[1, 1, 8, 1]) -> [1, 1, 8, 8] bool
    let t_le = b.add_node(rlx_ir::Op::Compare(rlx_ir::op::CmpOp::Le), vec![t_unsqueeze_12__bca, t_unsqueeze_9__bcb], rlx_ir::Shape::new(&[1, 1, 8, 8], rlx_ir::DType::Bool));
    // aten.expand.default  (le[1, 1, 8, 8]) -> [1, 1, 8, 8] bool
    let t_expand = b.add_node(rlx_ir::Op::Expand { target_shape: vec![1i64, 1i64, 8i64, 8i64] }, vec![t_le], rlx_ir::Shape::new(&[1, 1, 8, 8], rlx_ir::DType::Bool));
    // aten.unsqueeze.default  (b_m_model_rotary_emb_inv_freq[4]) -> [1, 4] f32
    let t_unsqueeze_13 = b.reshape_(t_b_m_model_rotary_emb_inv_freq, vec![1i64, 4i64]);
    // aten.unsqueeze.default  (unsqueeze_13[1, 4]) -> [1, 4, 1] f32
    let t_unsqueeze_14 = b.reshape_(t_unsqueeze_13, vec![1i64, 4i64, 1i64]);
    // aten.expand.default  (unsqueeze_14[1, 4, 1]) -> [1, 4, 1] f32
    let t_expand_1 = b.add_node(rlx_ir::Op::Expand { target_shape: vec![1i64, 4i64, 1i64] }, vec![t_unsqueeze_14], rlx_ir::Shape::new(&[1, 4, 1], rlx_ir::DType::F32));
    // aten.unsqueeze.default  (unsqueeze[1, 8]) -> [1, 1, 8] i64
    let t_unsqueeze_15 = b.reshape_(t_unsqueeze, vec![1i64, 1i64, 8i64]);
    // aten._to_copy.default  (unsqueeze_15[1, 1, 8]) -> [1, 1, 8] f32
    let t__to_copy = b.cast(t_unsqueeze_15, rlx_ir::DType::F32);
    // aten.expand.default  (expand_1[1, 4, 1]) -> [1, 4, 1] f32
    let t_expand_2 = b.add_node(rlx_ir::Op::Expand { target_shape: vec![1i64, 4i64, 1i64] }, vec![t_expand_1], rlx_ir::Shape::new(&[1, 4, 1], rlx_ir::DType::F32));
    // aten.view.default  (expand_2[1, 4, 1]) -> [1, 4, 1] f32
    let t_view = b.reshape_(t_expand_2, vec![1i64, 4i64, 1i64]);
    // aten.expand.default  (_to_copy[1, 1, 8]) -> [1, 1, 8] f32
    let t_expand_3 = b.add_node(rlx_ir::Op::Expand { target_shape: vec![1i64, 1i64, 8i64] }, vec![t__to_copy], rlx_ir::Shape::new(&[1, 1, 8], rlx_ir::DType::F32));
    // aten.view.default  (expand_3[1, 1, 8]) -> [1, 1, 8] f32
    let t_view_1 = b.reshape_(t_expand_3, vec![1i64, 1i64, 8i64]);
    // aten.bmm.default  (view[1, 4, 1], view_1[1, 1, 8]) -> [1, 4, 8] f32
    let t_bmm = b.mm(t_view, t_view_1);
    // aten.view.default  (bmm[1, 4, 8]) -> [1, 4, 8] f32
    let t_view_2 = b.reshape_(t_bmm, vec![1i64, 4i64, 8i64]);
    // aten.permute.default  (view_2[1, 4, 8]) -> [1, 8, 4] f32
    let t_permute = b.transpose_(t_view_2, vec![0usize, 2usize, 1usize]);
    // aten.cat.default  () -> [1, 8, 8] f32
    let t_cat = b.concat_(vec![t_permute, t_permute], 2);
    // aten.cos.default  (cat[1, 8, 8]) -> [1, 8, 8] f32
    let s_t_cos = b.shape(t_cat).clone();
    let t_cos = b.activation(Activation::Gelu, t_cat, s_t_cos);
    let bytes_t_mul__scalar = rlx_torch_fill(1f64, rlx_ir::DType::F32, 1);
    let t_mul__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_mul__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    // aten.mul.Tensor  (cos[1, 8, 8]) -> [1, 8, 8] f32
    let t_mul = b.mul(t_cos, t_mul__scalar);
    // aten.sin.default  (cat[1, 8, 8]) -> [1, 8, 8] f32
    let s_t_sin = b.shape(t_cat).clone();
    let t_sin = b.activation(Activation::Gelu, t_cat, s_t_sin);
    let bytes_t_mul_1__scalar = rlx_torch_fill(1f64, rlx_ir::DType::F32, 1);
    let t_mul_1__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_mul_1__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    // aten.mul.Tensor  (sin[1, 8, 8]) -> [1, 8, 8] f32
    let t_mul_1 = b.mul(t_sin, t_mul_1__scalar);
    let bytes_t_pow_1__scalar = rlx_torch_fill(2f64, rlx_ir::DType::F32, 1);
    let t_pow_1__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_pow_1__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    // aten.pow.Tensor_Scalar  (embedding[1, 8, 32]) -> [1, 8, 32] f32
    let t_pow_1 = b.add_node(rlx_ir::Op::Binary(rlx_ir::op::BinaryOp::Pow), vec![t_embedding, t_pow_1__scalar], rlx_ir::Shape::new(&[1, 8, 32], rlx_ir::DType::F32));
    // aten.mean.dim  (pow_1[1, 8, 32]) -> [1, 8, 1] f32
    let t_mean = b.mean(t_pow_1, vec![2usize], true);
    let bytes_t_add_3__scalar = rlx_torch_fill(0.000001f64, rlx_ir::DType::F32, 1);
    let t_add_3__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_add_3__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    // aten.add.Tensor  (mean[1, 8, 1]) -> [1, 8, 1] f32
    let t_add_3 = b.add(t_mean, t_add_3__scalar);
    // aten.rsqrt.default  (add_3[1, 8, 1]) -> [1, 8, 1] f32
    let s_t_rsqrt = b.shape(t_add_3).clone();
    let t_rsqrt = b.activation(Activation::Rsqrt, t_add_3, s_t_rsqrt);
    // aten.mul.Tensor  (embedding[1, 8, 32], rsqrt[1, 8, 1]) -> [1, 8, 32] f32
    let t_mul_2 = b.mul(t_embedding, t_rsqrt);
    // aten.mul.Tensor  (p_m_model_layers_0_input_layernorm_weight[32], mul_2[1, 8, 32]) -> [1, 8, 32] f32
    let t_mul_3 = b.mul(t_p_m_model_layers_0_input_layernorm_weight, t_mul_2);
    // aten.permute.default  (p_m_model_layers_0_self_attn_q_proj_weight[32, 32]) -> [32, 32] f32
    let t_permute_1 = b.transpose_(t_p_m_model_layers_0_self_attn_q_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (mul_3[1, 8, 32]) -> [8, 32] f32
    let t_view_3 = b.reshape_(t_mul_3, vec![8i64, 32i64]);
    // aten.mm.default  (view_3[8, 32], permute_1[32, 32]) -> [8, 32] f32
    let t_mm = b.mm(t_view_3, t_permute_1);
    // aten.view.default  (mm[8, 32]) -> [1, 8, 32] f32
    let t_view_4 = b.reshape_(t_mm, vec![1i64, 8i64, 32i64]);
    // aten.view.default  (view_4[1, 8, 32]) -> [1, 8, 4, 8] f32
    let t_view_5 = b.reshape_(t_view_4, vec![1i64, 8i64, 4i64, 8i64]);
    // aten.permute.default  (view_5[1, 8, 4, 8]) -> [1, 4, 8, 8] f32
    let t_permute_2 = b.transpose_(t_view_5, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.permute.default  (p_m_model_layers_0_self_attn_k_proj_weight[16, 32]) -> [32, 16] f32
    let t_permute_3 = b.transpose_(t_p_m_model_layers_0_self_attn_k_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (mul_3[1, 8, 32]) -> [8, 32] f32
    let t_view_6 = b.reshape_(t_mul_3, vec![8i64, 32i64]);
    // aten.mm.default  (view_6[8, 32], permute_3[32, 16]) -> [8, 16] f32
    let t_mm_1 = b.mm(t_view_6, t_permute_3);
    // aten.view.default  (mm_1[8, 16]) -> [1, 8, 16] f32
    let t_view_7 = b.reshape_(t_mm_1, vec![1i64, 8i64, 16i64]);
    // aten.view.default  (view_7[1, 8, 16]) -> [1, 8, 2, 8] f32
    let t_view_8 = b.reshape_(t_view_7, vec![1i64, 8i64, 2i64, 8i64]);
    // aten.permute.default  (view_8[1, 8, 2, 8]) -> [1, 2, 8, 8] f32
    let t_permute_4 = b.transpose_(t_view_8, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.permute.default  (p_m_model_layers_0_self_attn_v_proj_weight[16, 32]) -> [32, 16] f32
    let t_permute_5 = b.transpose_(t_p_m_model_layers_0_self_attn_v_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (mul_3[1, 8, 32]) -> [8, 32] f32
    let t_view_9 = b.reshape_(t_mul_3, vec![8i64, 32i64]);
    // aten.mm.default  (view_9[8, 32], permute_5[32, 16]) -> [8, 16] f32
    let t_mm_2 = b.mm(t_view_9, t_permute_5);
    // aten.view.default  (mm_2[8, 16]) -> [1, 8, 16] f32
    let t_view_10 = b.reshape_(t_mm_2, vec![1i64, 8i64, 16i64]);
    // aten.view.default  (view_10[1, 8, 16]) -> [1, 8, 2, 8] f32
    let t_view_11 = b.reshape_(t_view_10, vec![1i64, 8i64, 2i64, 8i64]);
    // aten.permute.default  (view_11[1, 8, 2, 8]) -> [1, 2, 8, 8] f32
    let t_permute_6 = b.transpose_(t_view_11, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.unsqueeze.default  (mul[1, 8, 8]) -> [1, 1, 8, 8] f32
    let t_unsqueeze_16 = b.reshape_(t_mul, vec![1i64, 1i64, 8i64, 8i64]);
    // aten.unsqueeze.default  (mul_1[1, 8, 8]) -> [1, 1, 8, 8] f32
    let t_unsqueeze_17 = b.reshape_(t_mul_1, vec![1i64, 1i64, 8i64, 8i64]);
    // aten.mul.Tensor  (permute_2[1, 4, 8, 8], unsqueeze_16[1, 1, 8, 8]) -> [1, 4, 8, 8] f32
    let t_mul_4 = b.mul(t_permute_2, t_unsqueeze_16);
    // aten.slice.Tensor  (permute_2[1, 4, 8, 8]) -> [1, 4, 8, 4] f32
    let t_slice_1 = b.narrow_(t_permute_2, 3, 0, 4);
    // aten.slice.Tensor  (permute_2[1, 4, 8, 8]) -> [1, 4, 8, 4] f32
    let t_slice_2 = b.narrow_(t_permute_2, 3, 4, 4);
    // aten.neg.default  (slice_2[1, 4, 8, 4]) -> [1, 4, 8, 4] f32
    let s_t_neg = b.shape(t_slice_2).clone();
    let t_neg = b.activation(Activation::Neg, t_slice_2, s_t_neg);
    // aten.cat.default  () -> [1, 4, 8, 8] f32
    let t_cat_1 = b.concat_(vec![t_neg, t_slice_1], 3);
    // aten.mul.Tensor  (cat_1[1, 4, 8, 8], unsqueeze_17[1, 1, 8, 8]) -> [1, 4, 8, 8] f32
    let t_mul_5 = b.mul(t_cat_1, t_unsqueeze_17);
    // aten.add.Tensor  (mul_4[1, 4, 8, 8], mul_5[1, 4, 8, 8]) -> [1, 4, 8, 8] f32
    let t_add_4 = b.add(t_mul_4, t_mul_5);
    // aten.mul.Tensor  (permute_4[1, 2, 8, 8], unsqueeze_16[1, 1, 8, 8]) -> [1, 2, 8, 8] f32
    let t_mul_6 = b.mul(t_permute_4, t_unsqueeze_16);
    // aten.slice.Tensor  (permute_4[1, 2, 8, 8]) -> [1, 2, 8, 4] f32
    let t_slice_3 = b.narrow_(t_permute_4, 3, 0, 4);
    // aten.slice.Tensor  (permute_4[1, 2, 8, 8]) -> [1, 2, 8, 4] f32
    let t_slice_4 = b.narrow_(t_permute_4, 3, 4, 4);
    // aten.neg.default  (slice_4[1, 2, 8, 4]) -> [1, 2, 8, 4] f32
    let s_t_neg_1 = b.shape(t_slice_4).clone();
    let t_neg_1 = b.activation(Activation::Neg, t_slice_4, s_t_neg_1);
    // aten.cat.default  () -> [1, 2, 8, 8] f32
    let t_cat_2 = b.concat_(vec![t_neg_1, t_slice_3], 3);
    // aten.mul.Tensor  (cat_2[1, 2, 8, 8], unsqueeze_17[1, 1, 8, 8]) -> [1, 2, 8, 8] f32
    let t_mul_7 = b.mul(t_cat_2, t_unsqueeze_17);
    // aten.add.Tensor  (mul_6[1, 2, 8, 8], mul_7[1, 2, 8, 8]) -> [1, 2, 8, 8] f32
    let t_add_5 = b.add(t_mul_6, t_mul_7);
    // aten.unsqueeze.default  (cat_3[1, 2, 8, 8]) -> [1, 2, 1, 8, 8] f32
    let t_unsqueeze_18 = b.reshape_(t_add_5, vec![1i64, 2i64, 1i64, 8i64, 8i64]);
    // aten.expand.default  (unsqueeze_18[1, 2, 1, 8, 8]) -> [1, 2, 2, 8, 8] f32
    let t_expand_4 = b.add_node(rlx_ir::Op::Expand { target_shape: vec![1i64, 2i64, 2i64, 8i64, 8i64] }, vec![t_unsqueeze_18], rlx_ir::Shape::new(&[1, 2, 2, 8, 8], rlx_ir::DType::F32));
    // aten.view.default  (clone_2[1, 2, 2, 8, 8]) -> [1, 4, 8, 8] f32
    let t_view_12 = b.reshape_(t_expand_4, vec![1i64, 4i64, 8i64, 8i64]);
    // aten.unsqueeze.default  (cat_4[1, 2, 8, 8]) -> [1, 2, 1, 8, 8] f32
    let t_unsqueeze_19 = b.reshape_(t_permute_6, vec![1i64, 2i64, 1i64, 8i64, 8i64]);
    // aten.expand.default  (unsqueeze_19[1, 2, 1, 8, 8]) -> [1, 2, 2, 8, 8] f32
    let t_expand_5 = b.add_node(rlx_ir::Op::Expand { target_shape: vec![1i64, 2i64, 2i64, 8i64, 8i64] }, vec![t_unsqueeze_19], rlx_ir::Shape::new(&[1, 2, 2, 8, 8], rlx_ir::DType::F32));
    // aten.view.default  (clone_3[1, 2, 2, 8, 8]) -> [1, 4, 8, 8] f32
    let t_view_13 = b.reshape_(t_expand_5, vec![1i64, 4i64, 8i64, 8i64]);
    let t_scaled_dot_product_attention__maskf = b.cast(t_expand, rlx_ir::DType::F32);
    let bytes_t_scaled_dot_product_attention_one__scalar = rlx_torch_fill(1f64, rlx_ir::DType::F32, 1);
    let t_scaled_dot_product_attention_one__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_scaled_dot_product_attention_one__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    let t_scaled_dot_product_attention__msub = b.add_node(rlx_ir::Op::Binary(rlx_ir::op::BinaryOp::Sub), vec![t_scaled_dot_product_attention__maskf, t_scaled_dot_product_attention_one__scalar], rlx_ir::Shape::new(&[1, 1, 8, 8], rlx_ir::DType::F32));
    let bytes_t_scaled_dot_product_attention_big__scalar = rlx_torch_fill(1000000000000000000000000000000f64, rlx_ir::DType::F32, 1);
    let t_scaled_dot_product_attention_big__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_scaled_dot_product_attention_big__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    let t_scaled_dot_product_attention__addmask = b.add_node(rlx_ir::Op::Binary(rlx_ir::op::BinaryOp::Mul), vec![t_scaled_dot_product_attention__msub, t_scaled_dot_product_attention_big__scalar], rlx_ir::Shape::new(&[1, 1, 8, 8], rlx_ir::DType::F32));
    let t_scaled_dot_product_attention__biasx = b.add_node(rlx_ir::Op::Expand { target_shape: vec![1i64, 4i64, 8i64, 8i64] }, vec![t_scaled_dot_product_attention__addmask], rlx_ir::Shape::new(&[1, 4, 8, 8], rlx_ir::DType::F32));
    // aten.scaled_dot_product_attention.default  (add_4[1, 4, 8, 8], view_12[1, 4, 8, 8], view_13[1, 4, 8, 8], expand[1, 1, 8, 8]) -> [1, 4, 8, 8] f32
    let t_scaled_dot_product_attention = b.attention_bias(t_add_4, t_view_12, t_view_13, t_scaled_dot_product_attention__biasx, 4, 8, rlx_ir::Shape::new(&[1, 4, 8, 8], rlx_ir::DType::F32));
    // aten.permute.default  (scaled_dot_product_attention[1, 4, 8, 8]) -> [1, 8, 4, 8] f32
    let t_permute_7 = b.transpose_(t_scaled_dot_product_attention, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.view.default  (permute_7[1, 8, 4, 8]) -> [1, 8, 32] f32
    let t_view_14 = b.reshape_(t_permute_7, vec![1i64, 8i64, 32i64]);
    // aten.permute.default  (p_m_model_layers_0_self_attn_o_proj_weight[32, 32]) -> [32, 32] f32
    let t_permute_8 = b.transpose_(t_p_m_model_layers_0_self_attn_o_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (view_14[1, 8, 32]) -> [8, 32] f32
    let t_view_15 = b.reshape_(t_view_14, vec![8i64, 32i64]);
    // aten.mm.default  (view_15[8, 32], permute_8[32, 32]) -> [8, 32] f32
    let t_mm_3 = b.mm(t_view_15, t_permute_8);
    // aten.view.default  (mm_3[8, 32]) -> [1, 8, 32] f32
    let t_view_16 = b.reshape_(t_mm_3, vec![1i64, 8i64, 32i64]);
    // aten.add.Tensor  (embedding[1, 8, 32], view_16[1, 8, 32]) -> [1, 8, 32] f32
    let t_add_6 = b.add(t_embedding, t_view_16);
    let bytes_t_pow_2__scalar = rlx_torch_fill(2f64, rlx_ir::DType::F32, 1);
    let t_pow_2__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_pow_2__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    // aten.pow.Tensor_Scalar  (add_6[1, 8, 32]) -> [1, 8, 32] f32
    let t_pow_2 = b.add_node(rlx_ir::Op::Binary(rlx_ir::op::BinaryOp::Pow), vec![t_add_6, t_pow_2__scalar], rlx_ir::Shape::new(&[1, 8, 32], rlx_ir::DType::F32));
    // aten.mean.dim  (pow_2[1, 8, 32]) -> [1, 8, 1] f32
    let t_mean_1 = b.mean(t_pow_2, vec![2usize], true);
    let bytes_t_add_7__scalar = rlx_torch_fill(0.000001f64, rlx_ir::DType::F32, 1);
    let t_add_7__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_add_7__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    // aten.add.Tensor  (mean_1[1, 8, 1]) -> [1, 8, 1] f32
    let t_add_7 = b.add(t_mean_1, t_add_7__scalar);
    // aten.rsqrt.default  (add_7[1, 8, 1]) -> [1, 8, 1] f32
    let s_t_rsqrt_1 = b.shape(t_add_7).clone();
    let t_rsqrt_1 = b.activation(Activation::Rsqrt, t_add_7, s_t_rsqrt_1);
    // aten.mul.Tensor  (add_6[1, 8, 32], rsqrt_1[1, 8, 1]) -> [1, 8, 32] f32
    let t_mul_8 = b.mul(t_add_6, t_rsqrt_1);
    // aten.mul.Tensor  (p_m_model_layers_0_post_attention_layernorm_weight[32], mul_8[1, 8, 32]) -> [1, 8, 32] f32
    let t_mul_9 = b.mul(t_p_m_model_layers_0_post_attention_layernorm_weight, t_mul_8);
    // aten.permute.default  (p_m_model_layers_0_mlp_gate_proj_weight[64, 32]) -> [32, 64] f32
    let t_permute_9 = b.transpose_(t_p_m_model_layers_0_mlp_gate_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (mul_9[1, 8, 32]) -> [8, 32] f32
    let t_view_17 = b.reshape_(t_mul_9, vec![8i64, 32i64]);
    // aten.mm.default  (view_17[8, 32], permute_9[32, 64]) -> [8, 64] f32
    let t_mm_4 = b.mm(t_view_17, t_permute_9);
    // aten.view.default  (mm_4[8, 64]) -> [1, 8, 64] f32
    let t_view_18 = b.reshape_(t_mm_4, vec![1i64, 8i64, 64i64]);
    // aten.silu.default  (view_18[1, 8, 64]) -> [1, 8, 64] f32
    let s_t_silu = b.shape(t_view_18).clone();
    let t_silu = b.activation(Activation::Silu, t_view_18, s_t_silu);
    // aten.permute.default  (p_m_model_layers_0_mlp_up_proj_weight[64, 32]) -> [32, 64] f32
    let t_permute_10 = b.transpose_(t_p_m_model_layers_0_mlp_up_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (mul_9[1, 8, 32]) -> [8, 32] f32
    let t_view_19 = b.reshape_(t_mul_9, vec![8i64, 32i64]);
    // aten.mm.default  (view_19[8, 32], permute_10[32, 64]) -> [8, 64] f32
    let t_mm_5 = b.mm(t_view_19, t_permute_10);
    // aten.view.default  (mm_5[8, 64]) -> [1, 8, 64] f32
    let t_view_20 = b.reshape_(t_mm_5, vec![1i64, 8i64, 64i64]);
    // aten.mul.Tensor  (silu[1, 8, 64], view_20[1, 8, 64]) -> [1, 8, 64] f32
    let t_mul_10 = b.mul(t_silu, t_view_20);
    // aten.permute.default  (p_m_model_layers_0_mlp_down_proj_weight[32, 64]) -> [64, 32] f32
    let t_permute_11 = b.transpose_(t_p_m_model_layers_0_mlp_down_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (mul_10[1, 8, 64]) -> [8, 64] f32
    let t_view_21 = b.reshape_(t_mul_10, vec![8i64, 64i64]);
    // aten.mm.default  (view_21[8, 64], permute_11[64, 32]) -> [8, 32] f32
    let t_mm_6 = b.mm(t_view_21, t_permute_11);
    // aten.view.default  (mm_6[8, 32]) -> [1, 8, 32] f32
    let t_view_22 = b.reshape_(t_mm_6, vec![1i64, 8i64, 32i64]);
    // aten.add.Tensor  (add_6[1, 8, 32], view_22[1, 8, 32]) -> [1, 8, 32] f32
    let t_add_8 = b.add(t_add_6, t_view_22);
    let bytes_t_pow_3__scalar = rlx_torch_fill(2f64, rlx_ir::DType::F32, 1);
    let t_pow_3__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_pow_3__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    // aten.pow.Tensor_Scalar  (add_8[1, 8, 32]) -> [1, 8, 32] f32
    let t_pow_3 = b.add_node(rlx_ir::Op::Binary(rlx_ir::op::BinaryOp::Pow), vec![t_add_8, t_pow_3__scalar], rlx_ir::Shape::new(&[1, 8, 32], rlx_ir::DType::F32));
    // aten.mean.dim  (pow_3[1, 8, 32]) -> [1, 8, 1] f32
    let t_mean_2 = b.mean(t_pow_3, vec![2usize], true);
    let bytes_t_add_9__scalar = rlx_torch_fill(0.000001f64, rlx_ir::DType::F32, 1);
    let t_add_9__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_add_9__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    // aten.add.Tensor  (mean_2[1, 8, 1]) -> [1, 8, 1] f32
    let t_add_9 = b.add(t_mean_2, t_add_9__scalar);
    // aten.rsqrt.default  (add_9[1, 8, 1]) -> [1, 8, 1] f32
    let s_t_rsqrt_2 = b.shape(t_add_9).clone();
    let t_rsqrt_2 = b.activation(Activation::Rsqrt, t_add_9, s_t_rsqrt_2);
    // aten.mul.Tensor  (add_8[1, 8, 32], rsqrt_2[1, 8, 1]) -> [1, 8, 32] f32
    let t_mul_11 = b.mul(t_add_8, t_rsqrt_2);
    // aten.mul.Tensor  (p_m_model_layers_1_input_layernorm_weight[32], mul_11[1, 8, 32]) -> [1, 8, 32] f32
    let t_mul_12 = b.mul(t_p_m_model_layers_1_input_layernorm_weight, t_mul_11);
    // aten.permute.default  (p_m_model_layers_1_self_attn_q_proj_weight[32, 32]) -> [32, 32] f32
    let t_permute_12 = b.transpose_(t_p_m_model_layers_1_self_attn_q_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (mul_12[1, 8, 32]) -> [8, 32] f32
    let t_view_23 = b.reshape_(t_mul_12, vec![8i64, 32i64]);
    // aten.mm.default  (view_23[8, 32], permute_12[32, 32]) -> [8, 32] f32
    let t_mm_7 = b.mm(t_view_23, t_permute_12);
    // aten.view.default  (mm_7[8, 32]) -> [1, 8, 32] f32
    let t_view_24 = b.reshape_(t_mm_7, vec![1i64, 8i64, 32i64]);
    // aten.view.default  (view_24[1, 8, 32]) -> [1, 8, 4, 8] f32
    let t_view_25 = b.reshape_(t_view_24, vec![1i64, 8i64, 4i64, 8i64]);
    // aten.permute.default  (view_25[1, 8, 4, 8]) -> [1, 4, 8, 8] f32
    let t_permute_13 = b.transpose_(t_view_25, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.permute.default  (p_m_model_layers_1_self_attn_k_proj_weight[16, 32]) -> [32, 16] f32
    let t_permute_14 = b.transpose_(t_p_m_model_layers_1_self_attn_k_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (mul_12[1, 8, 32]) -> [8, 32] f32
    let t_view_26 = b.reshape_(t_mul_12, vec![8i64, 32i64]);
    // aten.mm.default  (view_26[8, 32], permute_14[32, 16]) -> [8, 16] f32
    let t_mm_8 = b.mm(t_view_26, t_permute_14);
    // aten.view.default  (mm_8[8, 16]) -> [1, 8, 16] f32
    let t_view_27 = b.reshape_(t_mm_8, vec![1i64, 8i64, 16i64]);
    // aten.view.default  (view_27[1, 8, 16]) -> [1, 8, 2, 8] f32
    let t_view_28 = b.reshape_(t_view_27, vec![1i64, 8i64, 2i64, 8i64]);
    // aten.permute.default  (view_28[1, 8, 2, 8]) -> [1, 2, 8, 8] f32
    let t_permute_15 = b.transpose_(t_view_28, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.permute.default  (p_m_model_layers_1_self_attn_v_proj_weight[16, 32]) -> [32, 16] f32
    let t_permute_16 = b.transpose_(t_p_m_model_layers_1_self_attn_v_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (mul_12[1, 8, 32]) -> [8, 32] f32
    let t_view_29 = b.reshape_(t_mul_12, vec![8i64, 32i64]);
    // aten.mm.default  (view_29[8, 32], permute_16[32, 16]) -> [8, 16] f32
    let t_mm_9 = b.mm(t_view_29, t_permute_16);
    // aten.view.default  (mm_9[8, 16]) -> [1, 8, 16] f32
    let t_view_30 = b.reshape_(t_mm_9, vec![1i64, 8i64, 16i64]);
    // aten.view.default  (view_30[1, 8, 16]) -> [1, 8, 2, 8] f32
    let t_view_31 = b.reshape_(t_view_30, vec![1i64, 8i64, 2i64, 8i64]);
    // aten.permute.default  (view_31[1, 8, 2, 8]) -> [1, 2, 8, 8] f32
    let t_permute_17 = b.transpose_(t_view_31, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.unsqueeze.default  (mul[1, 8, 8]) -> [1, 1, 8, 8] f32
    let t_unsqueeze_20 = b.reshape_(t_mul, vec![1i64, 1i64, 8i64, 8i64]);
    // aten.unsqueeze.default  (mul_1[1, 8, 8]) -> [1, 1, 8, 8] f32
    let t_unsqueeze_21 = b.reshape_(t_mul_1, vec![1i64, 1i64, 8i64, 8i64]);
    // aten.mul.Tensor  (permute_13[1, 4, 8, 8], unsqueeze_20[1, 1, 8, 8]) -> [1, 4, 8, 8] f32
    let t_mul_13 = b.mul(t_permute_13, t_unsqueeze_20);
    // aten.slice.Tensor  (permute_13[1, 4, 8, 8]) -> [1, 4, 8, 4] f32
    let t_slice_5 = b.narrow_(t_permute_13, 3, 0, 4);
    // aten.slice.Tensor  (permute_13[1, 4, 8, 8]) -> [1, 4, 8, 4] f32
    let t_slice_6 = b.narrow_(t_permute_13, 3, 4, 4);
    // aten.neg.default  (slice_6[1, 4, 8, 4]) -> [1, 4, 8, 4] f32
    let s_t_neg_2 = b.shape(t_slice_6).clone();
    let t_neg_2 = b.activation(Activation::Neg, t_slice_6, s_t_neg_2);
    // aten.cat.default  () -> [1, 4, 8, 8] f32
    let t_cat_5 = b.concat_(vec![t_neg_2, t_slice_5], 3);
    // aten.mul.Tensor  (cat_5[1, 4, 8, 8], unsqueeze_21[1, 1, 8, 8]) -> [1, 4, 8, 8] f32
    let t_mul_14 = b.mul(t_cat_5, t_unsqueeze_21);
    // aten.add.Tensor  (mul_13[1, 4, 8, 8], mul_14[1, 4, 8, 8]) -> [1, 4, 8, 8] f32
    let t_add_10 = b.add(t_mul_13, t_mul_14);
    // aten.mul.Tensor  (permute_15[1, 2, 8, 8], unsqueeze_20[1, 1, 8, 8]) -> [1, 2, 8, 8] f32
    let t_mul_15 = b.mul(t_permute_15, t_unsqueeze_20);
    // aten.slice.Tensor  (permute_15[1, 2, 8, 8]) -> [1, 2, 8, 4] f32
    let t_slice_7 = b.narrow_(t_permute_15, 3, 0, 4);
    // aten.slice.Tensor  (permute_15[1, 2, 8, 8]) -> [1, 2, 8, 4] f32
    let t_slice_8 = b.narrow_(t_permute_15, 3, 4, 4);
    // aten.neg.default  (slice_8[1, 2, 8, 4]) -> [1, 2, 8, 4] f32
    let s_t_neg_3 = b.shape(t_slice_8).clone();
    let t_neg_3 = b.activation(Activation::Neg, t_slice_8, s_t_neg_3);
    // aten.cat.default  () -> [1, 2, 8, 8] f32
    let t_cat_6 = b.concat_(vec![t_neg_3, t_slice_7], 3);
    // aten.mul.Tensor  (cat_6[1, 2, 8, 8], unsqueeze_21[1, 1, 8, 8]) -> [1, 2, 8, 8] f32
    let t_mul_16 = b.mul(t_cat_6, t_unsqueeze_21);
    // aten.add.Tensor  (mul_15[1, 2, 8, 8], mul_16[1, 2, 8, 8]) -> [1, 2, 8, 8] f32
    let t_add_11 = b.add(t_mul_15, t_mul_16);
    // aten.unsqueeze.default  (cat_7[1, 2, 8, 8]) -> [1, 2, 1, 8, 8] f32
    let t_unsqueeze_22 = b.reshape_(t_add_11, vec![1i64, 2i64, 1i64, 8i64, 8i64]);
    // aten.expand.default  (unsqueeze_22[1, 2, 1, 8, 8]) -> [1, 2, 2, 8, 8] f32
    let t_expand_6 = b.add_node(rlx_ir::Op::Expand { target_shape: vec![1i64, 2i64, 2i64, 8i64, 8i64] }, vec![t_unsqueeze_22], rlx_ir::Shape::new(&[1, 2, 2, 8, 8], rlx_ir::DType::F32));
    // aten.view.default  (clone_6[1, 2, 2, 8, 8]) -> [1, 4, 8, 8] f32
    let t_view_32 = b.reshape_(t_expand_6, vec![1i64, 4i64, 8i64, 8i64]);
    // aten.unsqueeze.default  (cat_8[1, 2, 8, 8]) -> [1, 2, 1, 8, 8] f32
    let t_unsqueeze_23 = b.reshape_(t_permute_17, vec![1i64, 2i64, 1i64, 8i64, 8i64]);
    // aten.expand.default  (unsqueeze_23[1, 2, 1, 8, 8]) -> [1, 2, 2, 8, 8] f32
    let t_expand_7 = b.add_node(rlx_ir::Op::Expand { target_shape: vec![1i64, 2i64, 2i64, 8i64, 8i64] }, vec![t_unsqueeze_23], rlx_ir::Shape::new(&[1, 2, 2, 8, 8], rlx_ir::DType::F32));
    // aten.view.default  (clone_7[1, 2, 2, 8, 8]) -> [1, 4, 8, 8] f32
    let t_view_33 = b.reshape_(t_expand_7, vec![1i64, 4i64, 8i64, 8i64]);
    let t_scaled_dot_product_attention_1__maskf = b.cast(t_expand, rlx_ir::DType::F32);
    let bytes_t_scaled_dot_product_attention_1_one__scalar = rlx_torch_fill(1f64, rlx_ir::DType::F32, 1);
    let t_scaled_dot_product_attention_1_one__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_scaled_dot_product_attention_1_one__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    let t_scaled_dot_product_attention_1__msub = b.add_node(rlx_ir::Op::Binary(rlx_ir::op::BinaryOp::Sub), vec![t_scaled_dot_product_attention_1__maskf, t_scaled_dot_product_attention_1_one__scalar], rlx_ir::Shape::new(&[1, 1, 8, 8], rlx_ir::DType::F32));
    let bytes_t_scaled_dot_product_attention_1_big__scalar = rlx_torch_fill(1000000000000000000000000000000f64, rlx_ir::DType::F32, 1);
    let t_scaled_dot_product_attention_1_big__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_scaled_dot_product_attention_1_big__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    let t_scaled_dot_product_attention_1__addmask = b.add_node(rlx_ir::Op::Binary(rlx_ir::op::BinaryOp::Mul), vec![t_scaled_dot_product_attention_1__msub, t_scaled_dot_product_attention_1_big__scalar], rlx_ir::Shape::new(&[1, 1, 8, 8], rlx_ir::DType::F32));
    let t_scaled_dot_product_attention_1__biasx = b.add_node(rlx_ir::Op::Expand { target_shape: vec![1i64, 4i64, 8i64, 8i64] }, vec![t_scaled_dot_product_attention_1__addmask], rlx_ir::Shape::new(&[1, 4, 8, 8], rlx_ir::DType::F32));
    // aten.scaled_dot_product_attention.default  (add_10[1, 4, 8, 8], view_32[1, 4, 8, 8], view_33[1, 4, 8, 8], expand[1, 1, 8, 8]) -> [1, 4, 8, 8] f32
    let t_scaled_dot_product_attention_1 = b.attention_bias(t_add_10, t_view_32, t_view_33, t_scaled_dot_product_attention_1__biasx, 4, 8, rlx_ir::Shape::new(&[1, 4, 8, 8], rlx_ir::DType::F32));
    // aten.permute.default  (scaled_dot_product_attention_1[1, 4, 8, 8]) -> [1, 8, 4, 8] f32
    let t_permute_18 = b.transpose_(t_scaled_dot_product_attention_1, vec![0usize, 2usize, 1usize, 3usize]);
    // aten.view.default  (permute_18[1, 8, 4, 8]) -> [1, 8, 32] f32
    let t_view_34 = b.reshape_(t_permute_18, vec![1i64, 8i64, 32i64]);
    // aten.permute.default  (p_m_model_layers_1_self_attn_o_proj_weight[32, 32]) -> [32, 32] f32
    let t_permute_19 = b.transpose_(t_p_m_model_layers_1_self_attn_o_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (view_34[1, 8, 32]) -> [8, 32] f32
    let t_view_35 = b.reshape_(t_view_34, vec![8i64, 32i64]);
    // aten.mm.default  (view_35[8, 32], permute_19[32, 32]) -> [8, 32] f32
    let t_mm_10 = b.mm(t_view_35, t_permute_19);
    // aten.view.default  (mm_10[8, 32]) -> [1, 8, 32] f32
    let t_view_36 = b.reshape_(t_mm_10, vec![1i64, 8i64, 32i64]);
    // aten.add.Tensor  (add_8[1, 8, 32], view_36[1, 8, 32]) -> [1, 8, 32] f32
    let t_add_12 = b.add(t_add_8, t_view_36);
    let bytes_t_pow_4__scalar = rlx_torch_fill(2f64, rlx_ir::DType::F32, 1);
    let t_pow_4__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_pow_4__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    // aten.pow.Tensor_Scalar  (add_12[1, 8, 32]) -> [1, 8, 32] f32
    let t_pow_4 = b.add_node(rlx_ir::Op::Binary(rlx_ir::op::BinaryOp::Pow), vec![t_add_12, t_pow_4__scalar], rlx_ir::Shape::new(&[1, 8, 32], rlx_ir::DType::F32));
    // aten.mean.dim  (pow_4[1, 8, 32]) -> [1, 8, 1] f32
    let t_mean_3 = b.mean(t_pow_4, vec![2usize], true);
    let bytes_t_add_13__scalar = rlx_torch_fill(0.000001f64, rlx_ir::DType::F32, 1);
    let t_add_13__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_add_13__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    // aten.add.Tensor  (mean_3[1, 8, 1]) -> [1, 8, 1] f32
    let t_add_13 = b.add(t_mean_3, t_add_13__scalar);
    // aten.rsqrt.default  (add_13[1, 8, 1]) -> [1, 8, 1] f32
    let s_t_rsqrt_3 = b.shape(t_add_13).clone();
    let t_rsqrt_3 = b.activation(Activation::Rsqrt, t_add_13, s_t_rsqrt_3);
    // aten.mul.Tensor  (add_12[1, 8, 32], rsqrt_3[1, 8, 1]) -> [1, 8, 32] f32
    let t_mul_17 = b.mul(t_add_12, t_rsqrt_3);
    // aten.mul.Tensor  (p_m_model_layers_1_post_attention_layernorm_weight[32], mul_17[1, 8, 32]) -> [1, 8, 32] f32
    let t_mul_18 = b.mul(t_p_m_model_layers_1_post_attention_layernorm_weight, t_mul_17);
    // aten.permute.default  (p_m_model_layers_1_mlp_gate_proj_weight[64, 32]) -> [32, 64] f32
    let t_permute_20 = b.transpose_(t_p_m_model_layers_1_mlp_gate_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (mul_18[1, 8, 32]) -> [8, 32] f32
    let t_view_37 = b.reshape_(t_mul_18, vec![8i64, 32i64]);
    // aten.mm.default  (view_37[8, 32], permute_20[32, 64]) -> [8, 64] f32
    let t_mm_11 = b.mm(t_view_37, t_permute_20);
    // aten.view.default  (mm_11[8, 64]) -> [1, 8, 64] f32
    let t_view_38 = b.reshape_(t_mm_11, vec![1i64, 8i64, 64i64]);
    // aten.silu.default  (view_38[1, 8, 64]) -> [1, 8, 64] f32
    let s_t_silu_1 = b.shape(t_view_38).clone();
    let t_silu_1 = b.activation(Activation::Silu, t_view_38, s_t_silu_1);
    // aten.permute.default  (p_m_model_layers_1_mlp_up_proj_weight[64, 32]) -> [32, 64] f32
    let t_permute_21 = b.transpose_(t_p_m_model_layers_1_mlp_up_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (mul_18[1, 8, 32]) -> [8, 32] f32
    let t_view_39 = b.reshape_(t_mul_18, vec![8i64, 32i64]);
    // aten.mm.default  (view_39[8, 32], permute_21[32, 64]) -> [8, 64] f32
    let t_mm_12 = b.mm(t_view_39, t_permute_21);
    // aten.view.default  (mm_12[8, 64]) -> [1, 8, 64] f32
    let t_view_40 = b.reshape_(t_mm_12, vec![1i64, 8i64, 64i64]);
    // aten.mul.Tensor  (silu_1[1, 8, 64], view_40[1, 8, 64]) -> [1, 8, 64] f32
    let t_mul_19 = b.mul(t_silu_1, t_view_40);
    // aten.permute.default  (p_m_model_layers_1_mlp_down_proj_weight[32, 64]) -> [64, 32] f32
    let t_permute_22 = b.transpose_(t_p_m_model_layers_1_mlp_down_proj_weight, vec![1usize, 0usize]);
    // aten.view.default  (mul_19[1, 8, 64]) -> [8, 64] f32
    let t_view_41 = b.reshape_(t_mul_19, vec![8i64, 64i64]);
    // aten.mm.default  (view_41[8, 64], permute_22[64, 32]) -> [8, 32] f32
    let t_mm_13 = b.mm(t_view_41, t_permute_22);
    // aten.view.default  (mm_13[8, 32]) -> [1, 8, 32] f32
    let t_view_42 = b.reshape_(t_mm_13, vec![1i64, 8i64, 32i64]);
    // aten.add.Tensor  (add_12[1, 8, 32], view_42[1, 8, 32]) -> [1, 8, 32] f32
    let t_add_14 = b.add(t_add_12, t_view_42);
    let bytes_t_pow_5__scalar = rlx_torch_fill(2f64, rlx_ir::DType::F32, 1);
    let t_pow_5__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_pow_5__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    // aten.pow.Tensor_Scalar  (add_14[1, 8, 32]) -> [1, 8, 32] f32
    let t_pow_5 = b.add_node(rlx_ir::Op::Binary(rlx_ir::op::BinaryOp::Pow), vec![t_add_14, t_pow_5__scalar], rlx_ir::Shape::new(&[1, 8, 32], rlx_ir::DType::F32));
    // aten.mean.dim  (pow_5[1, 8, 32]) -> [1, 8, 1] f32
    let t_mean_4 = b.mean(t_pow_5, vec![2usize], true);
    let bytes_t_add_15__scalar = rlx_torch_fill(0.000001f64, rlx_ir::DType::F32, 1);
    let t_add_15__scalar = b.add_node(rlx_ir::Op::Constant { data: bytes_t_add_15__scalar }, vec![], rlx_ir::Shape::new(&[1], rlx_ir::DType::F32));
    // aten.add.Tensor  (mean_4[1, 8, 1]) -> [1, 8, 1] f32
    let t_add_15 = b.add(t_mean_4, t_add_15__scalar);
    // aten.rsqrt.default  (add_15[1, 8, 1]) -> [1, 8, 1] f32
    let s_t_rsqrt_4 = b.shape(t_add_15).clone();
    let t_rsqrt_4 = b.activation(Activation::Rsqrt, t_add_15, s_t_rsqrt_4);
    // aten.mul.Tensor  (add_14[1, 8, 32], rsqrt_4[1, 8, 1]) -> [1, 8, 32] f32
    let t_mul_20 = b.mul(t_add_14, t_rsqrt_4);
    // aten.mul.Tensor  (p_m_model_norm_weight[32], mul_20[1, 8, 32]) -> [1, 8, 32] f32
    let t_mul_21 = b.mul(t_p_m_model_norm_weight, t_mul_20);
    // aten.permute.default  (p_m_lm_head_weight[64, 32]) -> [32, 64] f32
    let t_permute_23 = b.transpose_(t_p_m_lm_head_weight, vec![1usize, 0usize]);
    // aten.view.default  (alias[1, 8, 32]) -> [8, 32] f32
    let t_view_43 = b.reshape_(t_mul_21, vec![8i64, 32i64]);
    // aten.mm.default  (view_43[8, 32], permute_23[32, 64]) -> [8, 64] f32
    let t_mm_14 = b.mm(t_view_43, t_permute_23);
    // aten.view.default  (mm_14[8, 64]) -> [1, 8, 64] f32
    let t_view_44 = b.reshape_(t_mm_14, vec![1i64, 8i64, 64i64]);
            let out_shape = b.shape(t_view_44).clone();
            drop(b);
            Ok(Some(emit.wrap(t_view_44, out_shape)))
        })))
        .output("output")
}
