"""Type stubs for the native pyrlx extension module.

Mirrors the runtime API in `python/pyrlx/__init__.py` so editors,
mypy, and pyright can give type-checked autocomplete.
"""

from __future__ import annotations

from typing import Literal, Mapping, Sequence

import numpy as np
import numpy.typing as npt

__version__: str

# ── Devices ─────────────────────────────────────────────────────────

DeviceName = Literal[
    "cpu", "metal", "mlx", "ane",
    "cuda", "rocm",
    "gpu", "vulkan", "opengl", "directx", "webgpu",
]

PrecisionName = Literal["f32", "f16", "bf16", "float32", "float16", "bfloat16"]

DTypeName = Literal[
    "f32", "f16", "bf16", "f64",
    "i8", "u8", "i16", "i32", "u32", "i64",
    "bool",
]

ActivationName = Literal[
    "gelu", "gelu_approx", "silu", "relu", "sigmoid",
    "tanh", "exp", "log", "sqrt", "rsqrt", "neg", "abs",
]

BinaryOpName  = Literal["add", "sub", "mul", "div", "max", "min", "pow",
                        "+", "-", "*", "/"]
CompareName   = Literal["eq", "ne", "lt", "le", "gt", "ge",
                        "==", "!=", "<", "<=", ">", ">="]
ReduceName    = Literal["sum", "mean", "max", "min", "prod"]
MaskKindName  = Literal["none", "causal"] | str  # also "sliding:<N>"


def available_devices() -> list[str]: ...
def is_available(name: str) -> bool: ...

NodeId = int


class Graph:
    """A symbolic graph being built. Consumed by `Session.compile`.

    Each builder method returns the integer node id of the new node.
    Most ops infer their output shape; the ones that don't (compare,
    reduce, sample, lora, ...) take the output shape explicitly.
    """

    def __init__(self, name: str) -> None: ...

    # I/O
    def input(self, name: str, shape: Sequence[int], dtype: DTypeName) -> NodeId: ...
    def param(self, name: str, shape: Sequence[int], dtype: DTypeName) -> NodeId: ...
    def set_outputs(self, outputs: Sequence[NodeId]) -> None: ...
    def shape_of(self, id: NodeId) -> tuple[list[int], str]: ...

    # Linear algebra
    def matmul(self, lhs: NodeId, rhs: NodeId) -> NodeId: ...
    def matmul_with_shape(
        self, lhs: NodeId, rhs: NodeId,
        out_shape: Sequence[int], dtype: DTypeName,
    ) -> NodeId: ...
    def lora_matmul(
        self, x: NodeId, w: NodeId, a: NodeId, b: NodeId, scale: float,
        out_shape: Sequence[int], dtype: DTypeName,
    ) -> NodeId: ...
    def fused_matmul_bias_act(
        self, input: NodeId, weight: NodeId, bias: NodeId,
        out_shape: Sequence[int], dtype: DTypeName,
        activation: ActivationName | None = ...,
    ) -> NodeId: ...

    # Element-wise
    def binary(self, op: BinaryOpName, lhs: NodeId, rhs: NodeId) -> NodeId: ...
    def add(self, a: NodeId, b: NodeId) -> NodeId: ...
    def sub(self, a: NodeId, b: NodeId) -> NodeId: ...
    def mul(self, a: NodeId, b: NodeId) -> NodeId: ...
    def div(self, a: NodeId, b: NodeId) -> NodeId: ...
    def activation(self, kind: ActivationName, input: NodeId) -> NodeId: ...
    def gelu(self, x: NodeId) -> NodeId: ...
    def silu(self, x: NodeId) -> NodeId: ...
    def relu(self, x: NodeId) -> NodeId: ...
    def exp(self, x: NodeId)  -> NodeId: ...
    def sqrt(self, x: NodeId) -> NodeId: ...
    def neg(self, x: NodeId)  -> NodeId: ...
    def tanh(self, x: NodeId) -> NodeId: ...

    # Comparison + select
    def compare(self, op: CompareName, lhs: NodeId, rhs: NodeId) -> NodeId: ...
    def eq_(self, a: NodeId, b: NodeId) -> NodeId: ...
    def lt_(self, a: NodeId, b: NodeId) -> NodeId: ...
    def where_(self, cond: NodeId, a: NodeId, b: NodeId) -> NodeId: ...

    # Reduction
    def reduce(self, input: NodeId, op: ReduceName,
               axes: Sequence[int], keep_dim: bool = ...) -> NodeId: ...
    def sum(self, x: NodeId, axes: Sequence[int], keep_dim: bool) -> NodeId: ...
    def mean(self, x: NodeId, axes: Sequence[int], keep_dim: bool) -> NodeId: ...
    def softmax(self, input: NodeId, axis: int = -1) -> NodeId: ...
    def cumsum(self, input: NodeId, axis: int, exclusive: bool = ...) -> NodeId: ...
    def sample(
        self, logits: NodeId, top_k: int, top_p: float,
        temperature: float, seed: int,
        output_shape: Sequence[int], dtype: DTypeName = ...,
    ) -> NodeId: ...

    # Shape ops
    def reshape(self, x: NodeId, new_shape: Sequence[int]) -> NodeId: ...
    def transpose(self, x: NodeId, perm: Sequence[int]) -> NodeId: ...
    def narrow(self, x: NodeId, axis: int, start: int, length: int) -> NodeId: ...
    def concat(self, inputs: Sequence[NodeId], axis: int) -> NodeId: ...
    def gather(self, table: NodeId, indices: NodeId, axis: int) -> NodeId: ...
    def cast(self, x: NodeId, to: DTypeName) -> NodeId: ...

    # Normalization
    def layer_norm(
        self, input: NodeId, gamma: NodeId, beta: NodeId,
        axis: int = -1, eps: float = 1e-5,
    ) -> NodeId: ...
    def rms_norm(
        self, input: NodeId, gamma: NodeId, beta: NodeId,
        eps: float = 1e-5,
    ) -> NodeId: ...

    # Attention
    def attention(
        self, q: NodeId, k: NodeId, v: NodeId, mask: NodeId,
        num_heads: int, head_dim: int,
    ) -> NodeId: ...
    def attention_kind(
        self, q: NodeId, k: NodeId, v: NodeId,
        num_heads: int, head_dim: int, mask_kind: str,
    ) -> NodeId: ...

    # RoPE
    def rope(self, x: NodeId, cos: NodeId, sin: NodeId, head_dim: int) -> NodeId: ...

    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...


class Session:
    def __init__(self, device: str = "cpu", precision: str = "f32") -> None: ...
    @property
    def device(self) -> str: ...
    @property
    def precision(self) -> str: ...
    def compile(self, graph: Graph) -> CompiledGraph: ...
    def __repr__(self) -> str: ...


class CompiledGraph:
    @property
    def device(self) -> str: ...
    def set_param(self, name: str, data: npt.NDArray[np.float32]) -> None: ...
    def run(self, inputs: Mapping[str, npt.NDArray[np.float32]]
            ) -> list[npt.NDArray[np.float32]]: ...
    def run_flat(self, inputs: Mapping[str, npt.NDArray[np.float32]]
                 ) -> list[npt.NDArray[np.float32]]: ...
    def __repr__(self) -> str: ...


class Embed:
    @staticmethod
    def from_dir(
        path: str, device: str = "cpu", precision: str = "f32",
        batch: int = 1, seq: int = 1,
    ) -> Embed: ...
    @staticmethod
    def from_pretrained(
        repo_id: str, device: str = "cpu", precision: str = "f32",
        batch: int = 1, seq: int = 1,
    ) -> Embed: ...
    @property
    def dim(self) -> int: ...
    @property
    def arch(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def batch_seq(self) -> tuple[int, int]: ...
    def forward(
        self, inputs: Mapping[str, npt.NDArray[np.float32]],
        batch: int, seq: int,
    ) -> list[npt.NDArray[np.float32]]: ...
    def __repr__(self) -> str: ...
