// AUTO-GENERATED by rlx-torch-import — do not edit by hand.
//
// Provenance: this RLX graph was imported from a PyTorch `torch.export`
// graph. Each op below is annotated with its original aten op + shapes so
// the source model can be traced / reconstructed.
//
// Original aten op histogram:
//      2  aten.linear.default
//      1  aten.gelu.default
//      1  aten.layer_norm.default

use std::collections::HashMap;
use rlx_ir::hir::{HirMut, HirNodeId};
use rlx_ir::op::{Activation, BinaryOp, MaskKind, ReduceOp};
use rlx_ir::{HirGraphExt, HirModule};

use crate::weights::LoadedWeights;

fn rlx_torch_fill(value: f64, dtype: rlx_ir::DType, numel: usize) -> Vec<u8> {
    let one: Vec<u8> = match dtype {
        rlx_ir::DType::F32 => (value as f32).to_le_bytes().to_vec(),
        rlx_ir::DType::F64 => value.to_le_bytes().to_vec(),
        rlx_ir::DType::I64 => (value as i64).to_le_bytes().to_vec(),
        rlx_ir::DType::I32 => (value as i32).to_le_bytes().to_vec(),
        _ => vec![],
    };
    let mut out = Vec::with_capacity(one.len() * numel);
    for _ in 0..numel { out.extend_from_slice(&one); }
    out
}

/// Build the model graph and assemble its parameter map.
pub fn build_graph(
    w: &LoadedWeights,
) -> anyhow::Result<(HirModule, HashMap<String, Vec<f32>>)> {
    let mut hir = HirModule::new("mlp");
    let mut b = HirMut::new(&mut hir);
    let mut params: HashMap<String, Vec<f32>> = HashMap::new();

    let t_x = b.input("x", rlx_ir::Shape::new(&[2, 4, 16], rlx_ir::DType::F32));

    let t_p_ln_weight = b.param("ln.weight", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
    params.insert("ln.weight".to_string(), w.get("ln.weight")?);
    let t_p_ln_bias = b.param("ln.bias", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
    params.insert("ln.bias".to_string(), w.get("ln.bias")?);
    let t_p_fc1_weight = b.param("fc1.weight", rlx_ir::Shape::new(&[32, 16], rlx_ir::DType::F32));
    params.insert("fc1.weight".to_string(), w.get("fc1.weight")?);
    let t_p_fc1_bias = b.param("fc1.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
    params.insert("fc1.bias".to_string(), w.get("fc1.bias")?);
    let t_p_fc2_weight = b.param("fc2.weight", rlx_ir::Shape::new(&[16, 32], rlx_ir::DType::F32));
    params.insert("fc2.weight".to_string(), w.get("fc2.weight")?);
    let t_p_fc2_bias = b.param("fc2.bias", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
    params.insert("fc2.bias".to_string(), w.get("fc2.bias")?);

    // aten.layer_norm.default  (x[2, 4, 16], p_ln_weight[16], p_ln_bias[16]) -> [2, 4, 16] f32
    let t_layer_norm = b.ln(t_x, t_p_ln_weight, t_p_ln_bias, 0.00001f32);
    let t_linear__wt = b.transpose_(t_p_fc1_weight, vec![1usize, 0usize]);
    let t_linear__mm = b.mm(t_layer_norm, t_linear__wt);
    // aten.linear.default  (layer_norm[2, 4, 16], p_fc1_weight[32, 16], p_fc1_bias[32]) -> [2, 4, 32] f32
    let t_linear = b.add(t_linear__mm, t_p_fc1_bias);
    // aten.gelu.default  (linear[2, 4, 32]) -> [2, 4, 32] f32
    let s_t_gelu = b.shape(t_linear).clone();
    let t_gelu = b.activation(Activation::Gelu, t_linear, s_t_gelu);
    let t_linear_1__wt = b.transpose_(t_p_fc2_weight, vec![1usize, 0usize]);
    let t_linear_1__mm = b.mm(t_gelu, t_linear_1__wt);
    // aten.linear.default  (gelu[2, 4, 32], p_fc2_weight[16, 32], p_fc2_bias[16]) -> [2, 4, 16] f32
    let t_linear_1 = b.add(t_linear_1__mm, t_p_fc2_bias);

    b.set_outputs(vec![t_linear_1]);
    Ok((hir, params))
}
