// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
// SPDX-License-Identifier: MIT OR Apache-2.0

//! **Compare op manifest** — one definition per [`CmpOp`], many backends. The
//! last of the standalone elementwise families (after the crate-root unary
//! activations and [`crate::binary`]) to be single-sourced. The `compare` kernel
//! historically re-spelled the same 6-way switch by hand in WGSL, CUDA C, MSL
//! and GLSL; here it is one op set and per-language emitters.
//!
//! Every backend uses the same output convention — a **f32 mask** (`1.0`/`0.0`),
//! since rlx stores `Bool` as an f32 lane in the uniform arena — so a single
//! `rlx_compare_apply(op, a, b) -> f32` serves them all. The only per-language
//! difference is how the boolean is turned into the mask: WGSL's `select`, the
//! C-family's `?:` ternary.

use crate::Lang;
use rlx_ir::op::CmpOp;

/// Evaluate `op(a, b)` as a `1.0`/`0.0` mask — the oracle the kernels target.
pub fn eval_compare(op: CmpOp, a: f32, b: f32) -> f32 {
    let r = match op {
        CmpOp::Eq => a == b,
        CmpOp::Ne => a != b,
        CmpOp::Lt => a < b,
        CmpOp::Le => a <= b,
        CmpOp::Gt => a > b,
        CmpOp::Ge => a >= b,
    };
    if r { 1.0 } else { 0.0 }
}

/// The comparison operator token (identical across all target languages).
fn cmp_sym(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Eq => "==",
        CmpOp::Ne => "!=",
        CmpOp::Lt => "<",
        CmpOp::Le => "<=",
        CmpOp::Gt => ">",
        CmpOp::Ge => ">=",
    }
}

/// The `1.0`/`0.0` mask expression for `op` in `lang`.
pub fn emit_compare(op: CmpOp, lang: Lang) -> String {
    let cond = format!("a {} b", cmp_sym(op));
    match lang {
        // WGSL has no ternary — `select(false_val, true_val, cond)`.
        Lang::Wgsl => format!("select(0.0, 1.0, {cond})"),
        Lang::Glsl => format!("({cond}) ? 1.0 : 0.0"),
        Lang::Cuda | Lang::Msl | Lang::OpenCl => format!("({cond}) ? 1.0f : 0.0f"),
    }
}

/// Shared body of the `*_compare_module` emitters: a `switch (op)` over every
/// [`CmpOp`] in opcode order, each `case` returning the `1.0`/`0.0` mask.
fn compare_switch(lang: Lang, signature: &str, default_close: &str) -> String {
    let mut s = String::from(
        "// @generated by rlxsl::compare — do not edit by hand.\n\
         // Compare-op math is defined once in rlxsl::compare::emit_compare.\n",
    );
    s.push_str(signature);
    for op in CmpOp::ALL {
        let id = op.opcode();
        s.push_str(&format!(
            "        case {id}u: {{ return {}; }} // {op:?}\n",
            emit_compare(op, lang)
        ));
    }
    s.push_str(default_close);
    s
}

/// WGSL `rlx_compare_apply(op, a, b)` — single source for wgpu's `compare` kernel.
pub fn wgsl_compare_module() -> String {
    compare_switch(
        Lang::Wgsl,
        "fn rlx_compare_apply(op: u32, a: f32, b: f32) -> f32 {\n    switch op {\n",
        "        default: { return 0.0; }\n    }\n}\n",
    )
}

/// CUDA `__device__` compare dispatch generated from the manifest.
pub fn cuda_compare_module() -> String {
    compare_switch(
        Lang::Cuda,
        "__device__ __forceinline__ float rlx_compare_apply(unsigned int op, float a, float b) {\n    switch (op) {\n",
        "        default: return 0.0f;\n    }\n}\n",
    )
}

/// MSL compare dispatch generated from the manifest.
pub fn msl_compare_module() -> String {
    compare_switch(
        Lang::Msl,
        "inline float rlx_compare_apply(uint op, float a, float b) {\n    switch (op) {\n",
        "        default: return 0.0f;\n    }\n}\n",
    )
}

/// GLSL (native Vulkan) compare dispatch generated from the manifest.
pub fn glsl_compare_module() -> String {
    compare_switch(
        Lang::Glsl,
        "float rlx_compare_apply(uint op, float a, float b) {\n    switch (op) {\n",
        "        default: return 0.0;\n    }\n}\n",
    )
}

/// OpenCL-C compare dispatch generated from the manifest.
pub fn opencl_compare_module() -> String {
    compare_switch(
        Lang::OpenCl,
        "inline float rlx_compare_apply(uint op, float a, float b) {\n    switch (op) {\n",
        "        default: return 0.0f;\n    }\n}\n",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn eval_matches_reference() {
        let vals = [-2.0f32, -1.0, -0.0, 0.0, 1.0, 2.0, f32::NAN];
        for &op in &CmpOp::ALL {
            for &a in &vals {
                for &b in &vals {
                    let got = eval_compare(op, a, b);
                    let want = {
                        let r = match op {
                            CmpOp::Eq => a == b,
                            CmpOp::Ne => a != b,
                            CmpOp::Lt => a < b,
                            CmpOp::Le => a <= b,
                            CmpOp::Gt => a > b,
                            CmpOp::Ge => a >= b,
                        };
                        if r { 1.0 } else { 0.0 }
                    };
                    assert_eq!(got, want, "{op:?}({a},{b})");
                }
            }
        }
    }

    #[test]
    fn every_language_emits_all_ops() {
        for lang in [Lang::Wgsl, Lang::Cuda, Lang::Msl, Lang::Glsl, Lang::OpenCl] {
            let m = match lang {
                Lang::Wgsl => wgsl_compare_module(),
                Lang::Cuda => cuda_compare_module(),
                Lang::Msl => msl_compare_module(),
                Lang::Glsl => glsl_compare_module(),
                Lang::OpenCl => opencl_compare_module(),
            };
            assert_eq!(m.matches("case ").count(), CmpOp::ALL.len(), "{lang:?}");
            assert!(m.contains("rlx_compare_apply") && m.contains("default"));
        }
        assert!(wgsl_compare_module().contains("select(0.0, 1.0, a == b)"));
        assert!(cuda_compare_module().contains("(a != b) ? 1.0f : 0.0f"));
    }
}
