// AUTO-GENERATED by rlx-torch-import — do not edit by hand.
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Provenance: this RLX graph was imported from a PyTorch `torch.export`
// graph. Each op below is annotated with its original aten op + shapes so
// the source model can be traced / reconstructed.
//
// Original aten op histogram:
//      4  aten.view.default
//      2  aten.addmm.default
//      2  aten.permute.default
//      1  aten.gelu.default
//      1  aten.layer_norm.default

use std::collections::HashMap;
use rlx_ir::hir::{HirMut, HirNodeId};
use rlx_ir::op::{Activation, BinaryOp, MaskKind, ReduceOp};
use rlx_ir::{HirGraphExt, HirModule};

use crate::weights::LoadedWeights;

fn rlx_torch_fill(value: f64, dtype: rlx_ir::DType, numel: usize) -> Vec<u8> {
    let one: Vec<u8> = match dtype {
        rlx_ir::DType::F32 => (value as f32).to_le_bytes().to_vec(),
        rlx_ir::DType::F64 => value.to_le_bytes().to_vec(),
        rlx_ir::DType::I64 => (value as i64).to_le_bytes().to_vec(),
        rlx_ir::DType::I32 => (value as i32).to_le_bytes().to_vec(),
        _ => vec![],
    };
    let mut out = Vec::with_capacity(one.len() * numel);
    for _ in 0..numel { out.extend_from_slice(&one); }
    out
}

/// Build the model graph and assemble its parameter map.
pub fn build_graph(
    w: &LoadedWeights,
) -> anyhow::Result<(HirModule, HashMap<String, Vec<f32>>)> {
    let mut hir = HirModule::new("mlp");
    let mut b = HirMut::new(&mut hir);
    let mut params: HashMap<String, Vec<f32>> = HashMap::new();

    let t_x = b.input("x", rlx_ir::Shape::new(&[2, 4, 16], rlx_ir::DType::F32));

    let t_p_ln_weight = b.param("ln.weight", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
    params.insert("ln.weight".to_string(), w.get("ln.weight")?);
    let t_p_ln_bias = b.param("ln.bias", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
    params.insert("ln.bias".to_string(), w.get("ln.bias")?);
    let t_p_fc1_weight = b.param("fc1.weight", rlx_ir::Shape::new(&[32, 16], rlx_ir::DType::F32));
    params.insert("fc1.weight".to_string(), w.get("fc1.weight")?);
    let t_p_fc1_bias = b.param("fc1.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
    params.insert("fc1.bias".to_string(), w.get("fc1.bias")?);
    let t_p_fc2_weight = b.param("fc2.weight", rlx_ir::Shape::new(&[16, 32], rlx_ir::DType::F32));
    params.insert("fc2.weight".to_string(), w.get("fc2.weight")?);
    let t_p_fc2_bias = b.param("fc2.bias", rlx_ir::Shape::new(&[16], rlx_ir::DType::F32));
    params.insert("fc2.bias".to_string(), w.get("fc2.bias")?);

    // aten.layer_norm.default  (x[2, 4, 16], p_ln_weight[16], p_ln_bias[16]) -> [2, 4, 16] f32
    let t_layer_norm = b.ln(t_x, t_p_ln_weight, t_p_ln_bias, 0.00001f32);
    // aten.view.default  (layer_norm[2, 4, 16]) -> [8, 16] f32
    let t_view = b.reshape_(t_layer_norm, vec![8i64, 16i64]);
    // aten.permute.default  (p_fc1_weight[32, 16]) -> [16, 32] f32
    let t_permute = b.transpose_(t_p_fc1_weight, vec![1usize, 0usize]);
    let t_addmm__mm = b.mm(t_view, t_permute);
    // aten.addmm.default  (p_fc1_bias[32], view[8, 16], permute[16, 32]) -> [8, 32] f32
    let t_addmm = b.add(t_addmm__mm, t_p_fc1_bias);
    // aten.view.default  (addmm[8, 32]) -> [2, 4, 32] f32
    let t_view_1 = b.reshape_(t_addmm, vec![2i64, 4i64, 32i64]);
    // aten.gelu.default  (view_1[2, 4, 32]) -> [2, 4, 32] f32
    let s_t_gelu = b.shape(t_view_1).clone();
    let t_gelu = b.activation(Activation::Gelu, t_view_1, s_t_gelu);
    // aten.view.default  (gelu[2, 4, 32]) -> [8, 32] f32
    let t_view_2 = b.reshape_(t_gelu, vec![8i64, 32i64]);
    // aten.permute.default  (p_fc2_weight[16, 32]) -> [32, 16] f32
    let t_permute_1 = b.transpose_(t_p_fc2_weight, vec![1usize, 0usize]);
    let t_addmm_1__mm = b.mm(t_view_2, t_permute_1);
    // aten.addmm.default  (p_fc2_bias[16], view_2[8, 32], permute_1[32, 16]) -> [8, 16] f32
    let t_addmm_1 = b.add(t_addmm_1__mm, t_p_fc2_bias);
    // aten.view.default  (addmm_1[8, 16]) -> [2, 4, 16] f32
    let t_view_3 = b.reshape_(t_addmm_1, vec![2i64, 4i64, 16i64]);

    b.set_outputs(vec![t_view_3]);
    Ok((hir, params))
}
