#!/usr/bin/env bash
set -euo pipefail
# Generated by rlx-fpga — do not hand-edit.
cd "$(dirname "$0")"

# Target-agnostic: Yosys generic synth to a JSON netlist.
# Soft ports only — wrap `top` with a board shell for pin mapping.
yosys -p 'read_verilog -sv top.sv layers/*.sv primitives/*.sv; hierarchy -top top; synth -top top; write_json out.json'
echo "wrote out.json (generic). Bind pins in a board wrapper before P&R."
