// ───────────────────────────────────────────────────
// top — tinyconv_mnist (auto-generated by rlx-fpga)
// ───────────────────────────────────────────────────
// Pipeline:
//   L00  Conv2d    out_len=5408
//   L01  ReLU      out_len=5408
//   L02  MaxPool   out_len=1352
//   L03  Conv2d    out_len=1936
//   L04  ReLU      out_len=1936
//   L05  MaxPool   out_len=400
//   L06  Dense     out_len=10
//   L07  Argmax    out_len=1

module top (
    input  logic                       clk,
    input  logic                       rst,
    input  logic                       start,
    output logic                       done,
    input  logic [9:0]              in_addr,
    input  logic                       in_we,
    input  logic signed [7:0]          in_din,
    output logic signed [7:0]          pred
);
    // ─── activation BRAMs ───
    logic [9:0] a0_addr;
    logic        a0_we;
    logic signed [7:0] a0_din;
    logic signed [7:0] a0_dout;
    block_ram #(.WIDTH(8), .DEPTH(784)) u_a0 (
        .clk(clk), .we(a0_we), .addr(a0_addr),
        .din(a0_din), .dout(a0_dout)
    );
    logic [12:0] a1_addr;
    logic        a1_we;
    logic signed [7:0] a1_din;
    logic signed [7:0] a1_dout;
    block_ram #(.WIDTH(8), .DEPTH(5408)) u_a1 (
        .clk(clk), .we(a1_we), .addr(a1_addr),
        .din(a1_din), .dout(a1_dout)
    );
    logic [12:0] a2_addr;
    logic        a2_we;
    logic signed [7:0] a2_din;
    logic signed [7:0] a2_dout;
    block_ram #(.WIDTH(8), .DEPTH(5408)) u_a2 (
        .clk(clk), .we(a2_we), .addr(a2_addr),
        .din(a2_din), .dout(a2_dout)
    );
    logic [10:0] a3_addr;
    logic        a3_we;
    logic signed [7:0] a3_din;
    logic signed [7:0] a3_dout;
    block_ram #(.WIDTH(8), .DEPTH(1352)) u_a3 (
        .clk(clk), .we(a3_we), .addr(a3_addr),
        .din(a3_din), .dout(a3_dout)
    );
    logic [10:0] a4_addr;
    logic        a4_we;
    logic signed [7:0] a4_din;
    logic signed [7:0] a4_dout;
    block_ram #(.WIDTH(8), .DEPTH(1936)) u_a4 (
        .clk(clk), .we(a4_we), .addr(a4_addr),
        .din(a4_din), .dout(a4_dout)
    );
    logic [10:0] a5_addr;
    logic        a5_we;
    logic signed [7:0] a5_din;
    logic signed [7:0] a5_dout;
    block_ram #(.WIDTH(8), .DEPTH(1936)) u_a5 (
        .clk(clk), .we(a5_we), .addr(a5_addr),
        .din(a5_din), .dout(a5_dout)
    );
    logic [8:0] a6_addr;
    logic        a6_we;
    logic signed [7:0] a6_din;
    logic signed [7:0] a6_dout;
    block_ram #(.WIDTH(8), .DEPTH(400)) u_a6 (
        .clk(clk), .we(a6_we), .addr(a6_addr),
        .din(a6_din), .dout(a6_dout)
    );
    logic [3:0] a7_addr;
    logic        a7_we;
    logic signed [7:0] a7_din;
    logic signed [7:0] a7_dout;
    block_ram #(.WIDTH(8), .DEPTH(10)) u_a7 (
        .clk(clk), .we(a7_we), .addr(a7_addr),
        .din(a7_din), .dout(a7_dout)
    );
    logic [0:0] a8_addr;
    logic        a8_we;
    logic signed [7:0] a8_din;
    logic signed [7:0] a8_dout;
    block_ram #(.WIDTH(8), .DEPTH(1)) u_a8 (
        .clk(clk), .we(a8_we), .addr(a8_addr),
        .din(a8_din), .dout(a8_dout)
    );

    // ─── per-layer kernel instances ───
    // Each kernel reads from a{i} and writes to a{i+1}.
    logic l0_start, l0_done;
    logic [9:0] l0_x_addr;
    logic [12:0] l0_y_addr;
    logic        l0_y_we;
    logic signed [7:0] l0_y_din;
    conv1_kernel u_conv1 (
        .clk(clk), .rst(rst),
        .start(l0_start), .done(l0_done),
        .x_addr(l0_x_addr), .x_dout(a0_dout),
        .y_addr(l0_y_addr), .y_we(l0_y_we), .y_din(l0_y_din)
    );

    logic l1_start, l1_done;
    logic [12:0] l1_x_addr;
    logic [12:0] l1_y_addr;
    logic        l1_y_we;
    logic signed [7:0] l1_y_din;
    relu1_kernel u_relu1 (
        .clk(clk), .rst(rst),
        .start(l1_start), .done(l1_done),
        .x_addr(l1_x_addr), .x_dout(a1_dout),
        .y_addr(l1_y_addr), .y_we(l1_y_we), .y_din(l1_y_din)
    );

    logic l2_start, l2_done;
    logic [12:0] l2_x_addr;
    logic [10:0] l2_y_addr;
    logic        l2_y_we;
    logic signed [7:0] l2_y_din;
    pool1_kernel u_pool1 (
        .clk(clk), .rst(rst),
        .start(l2_start), .done(l2_done),
        .x_addr(l2_x_addr), .x_dout(a2_dout),
        .y_addr(l2_y_addr), .y_we(l2_y_we), .y_din(l2_y_din)
    );

    logic l3_start, l3_done;
    logic [10:0] l3_x_addr;
    logic [10:0] l3_y_addr;
    logic        l3_y_we;
    logic signed [7:0] l3_y_din;
    conv2_kernel u_conv2 (
        .clk(clk), .rst(rst),
        .start(l3_start), .done(l3_done),
        .x_addr(l3_x_addr), .x_dout(a3_dout),
        .y_addr(l3_y_addr), .y_we(l3_y_we), .y_din(l3_y_din)
    );

    logic l4_start, l4_done;
    logic [10:0] l4_x_addr;
    logic [10:0] l4_y_addr;
    logic        l4_y_we;
    logic signed [7:0] l4_y_din;
    relu2_kernel u_relu2 (
        .clk(clk), .rst(rst),
        .start(l4_start), .done(l4_done),
        .x_addr(l4_x_addr), .x_dout(a4_dout),
        .y_addr(l4_y_addr), .y_we(l4_y_we), .y_din(l4_y_din)
    );

    logic l5_start, l5_done;
    logic [10:0] l5_x_addr;
    logic [8:0] l5_y_addr;
    logic        l5_y_we;
    logic signed [7:0] l5_y_din;
    pool2_kernel u_pool2 (
        .clk(clk), .rst(rst),
        .start(l5_start), .done(l5_done),
        .x_addr(l5_x_addr), .x_dout(a5_dout),
        .y_addr(l5_y_addr), .y_we(l5_y_we), .y_din(l5_y_din)
    );

    logic l6_start, l6_done;
    logic [8:0] l6_x_addr;
    logic [3:0] l6_y_addr;
    logic        l6_y_we;
    logic signed [7:0] l6_y_din;
    fc_kernel u_fc (
        .clk(clk), .rst(rst),
        .start(l6_start), .done(l6_done),
        .x_addr(l6_x_addr), .x_dout(a6_dout),
        .y_addr(l6_y_addr), .y_we(l6_y_we), .y_din(l6_y_din)
    );

    logic l7_start, l7_done;
    logic [3:0] l7_x_addr;
    logic [0:0] l7_y_addr;
    logic        l7_y_we;
    logic signed [7:0] l7_y_din;
    argmax_kernel u_argmax (
        .clk(clk), .rst(rst),
        .start(l7_start), .done(l7_done),
        .x_addr(l7_x_addr), .x_dout(a7_dout),
        .y_addr(l7_y_addr), .y_we(l7_y_we), .y_din(l7_y_din)
    );

    // ─── BRAM port routing ───
    // BRAM 0 (input): driven externally before `start`,
    //                 read by L0 during execution.
    // BRAM N (output): driven by L{N-1}, exposed as `pred`.
    // Intermediate BRAMs are muxed: read by L{i}, written by L{i-1}.

    always_comb begin
        if (start) begin
            a0_addr = l0_x_addr;
            a0_we   = 1'b0;
            a0_din  = 8'sd0;
        end else begin
            a0_addr = in_addr;
            a0_we   = in_we;
            a0_din  = in_din;
        end
    end

    // BRAM 1 ← L0.y, → L1.x
    always_comb begin
        // During L0's active state, BRAM 1 accepts writes.
        // During L1's active state, BRAM 1 provides reads.
        a1_we   = l0_y_we;
        a1_din  = l0_y_din;
        a1_addr = l0_y_we ? l0_y_addr : l1_x_addr;
    end

    // BRAM 2 ← L1.y, → L2.x
    always_comb begin
        // During L1's active state, BRAM 2 accepts writes.
        // During L2's active state, BRAM 2 provides reads.
        a2_we   = l1_y_we;
        a2_din  = l1_y_din;
        a2_addr = l1_y_we ? l1_y_addr : l2_x_addr;
    end

    // BRAM 3 ← L2.y, → L3.x
    always_comb begin
        // During L2's active state, BRAM 3 accepts writes.
        // During L3's active state, BRAM 3 provides reads.
        a3_we   = l2_y_we;
        a3_din  = l2_y_din;
        a3_addr = l2_y_we ? l2_y_addr : l3_x_addr;
    end

    // BRAM 4 ← L3.y, → L4.x
    always_comb begin
        // During L3's active state, BRAM 4 accepts writes.
        // During L4's active state, BRAM 4 provides reads.
        a4_we   = l3_y_we;
        a4_din  = l3_y_din;
        a4_addr = l3_y_we ? l3_y_addr : l4_x_addr;
    end

    // BRAM 5 ← L4.y, → L5.x
    always_comb begin
        // During L4's active state, BRAM 5 accepts writes.
        // During L5's active state, BRAM 5 provides reads.
        a5_we   = l4_y_we;
        a5_din  = l4_y_din;
        a5_addr = l4_y_we ? l4_y_addr : l5_x_addr;
    end

    // BRAM 6 ← L5.y, → L6.x
    always_comb begin
        // During L5's active state, BRAM 6 accepts writes.
        // During L6's active state, BRAM 6 provides reads.
        a6_we   = l5_y_we;
        a6_din  = l5_y_din;
        a6_addr = l5_y_we ? l5_y_addr : l6_x_addr;
    end

    // BRAM 7 ← L6.y, → L7.x
    always_comb begin
        // During L6's active state, BRAM 7 accepts writes.
        // During L7's active state, BRAM 7 provides reads.
        a7_we   = l6_y_we;
        a7_din  = l6_y_din;
        a7_addr = l6_y_we ? l6_y_addr : l7_x_addr;
    end

    // BRAM 8 ← L7.y, → L8.x
    always_comb begin
        a8_we   = l7_y_we;
        a8_din  = l7_y_din;
        a8_addr = l7_y_addr;
    end

    // Expose the final BRAM's word at addr 0 as `pred`.
    assign pred = a8_dout;

    // ───────────────────────────────────────────────────────────
    // controller — assert each layer's `start`, wait for `done`
    // ───────────────────────────────────────────────────────────
    logic [3:0] stage;
    typedef enum logic [1:0] {
        C_IDLE, C_RUN, C_STEP, C_DONE
    } ctrl_t;
    ctrl_t cstate, cnext;

    always_comb begin
        l0_start = (cstate == C_RUN) && (stage == 0);
        l1_start = (cstate == C_RUN) && (stage == 1);
        l2_start = (cstate == C_RUN) && (stage == 2);
        l3_start = (cstate == C_RUN) && (stage == 3);
        l4_start = (cstate == C_RUN) && (stage == 4);
        l5_start = (cstate == C_RUN) && (stage == 5);
        l6_start = (cstate == C_RUN) && (stage == 6);
        l7_start = (cstate == C_RUN) && (stage == 7);
        done = (cstate == C_DONE);
    end

    always_ff @(posedge clk) begin
        if (rst) begin
            cstate <= C_IDLE;
            stage  <= '0;
        end else begin
            cstate <= cnext;
            if (cstate == C_IDLE && start) stage <= '0;
            if (cstate == C_STEP) stage <= stage + 1;
        end
    end

    always_comb begin
        cnext = cstate;
        unique case (cstate)
            C_IDLE : if (start) cnext = C_RUN;
            C_RUN  : begin
                // wait for the active layer to assert done
                if    (stage == 0 && l0_done) cnext = C_STEP;
                else if (stage == 1 && l1_done) cnext = C_STEP;
                else if (stage == 2 && l2_done) cnext = C_STEP;
                else if (stage == 3 && l3_done) cnext = C_STEP;
                else if (stage == 4 && l4_done) cnext = C_STEP;
                else if (stage == 5 && l5_done) cnext = C_STEP;
                else if (stage == 6 && l6_done) cnext = C_STEP;
                else if (stage == 7 && l7_done) cnext = C_STEP;
            end
            C_STEP : cnext = (stage == 7) ? C_DONE : C_RUN;
            C_DONE : if (!start) cnext = C_IDLE;
        endcase
    end
endmodule  // top

