// AUTO-GENERATED by rlx-torch-import (tensor style) — do not edit by hand.
#![allow(nonstandard_style, unused_parens, clippy::all)]

use rlx_ir::op::MaskKind;

/// Weight keys to bind after compiling (loaded from safetensors).
pub const PARAM_KEYS: &[&str] = &["enc.p.q.weight", "enc.p.k.weight", "enc.p.v.weight", "enc.p.o.weight", "dec_self.p.q.weight", "dec_self.p.k.weight", "dec_self.p.v.weight", "dec_self.p.o.weight", "dec_cross.p.q.weight", "dec_cross.p.k.weight", "dec_cross.p.v.weight", "dec_cross.p.o.weight", "n.0.weight", "n.0.bias", "n.1.weight", "n.1.bias", "n.2.weight", "n.2.bias"];
/// Synthesized zero params (key, numel).
pub const ZERO_PARAMS: &[(&str, usize)] = &[];

/// Build the model as an `rlx_tensor` graph (PyTorch-like DSL).
pub fn build_graph() -> rlx_ir::Graph {
    rlx_tensor::graph("encoder_decoder", |g| {
        let t_src = g.input("src", rlx_ir::Shape::new(&[1, 5, 32], rlx_ir::DType::F32));
        let t_tgt = g.input("tgt", rlx_ir::Shape::new(&[1, 3, 32], rlx_ir::DType::F32));
        let t_p_enc_p_q_weight = g.param("enc.p.q.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
        let t_p_enc_p_k_weight = g.param("enc.p.k.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
        let t_p_enc_p_v_weight = g.param("enc.p.v.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
        let t_p_enc_p_o_weight = g.param("enc.p.o.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
        let t_p_dec_self_p_q_weight = g.param("dec_self.p.q.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
        let t_p_dec_self_p_k_weight = g.param("dec_self.p.k.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
        let t_p_dec_self_p_v_weight = g.param("dec_self.p.v.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
        let t_p_dec_self_p_o_weight = g.param("dec_self.p.o.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
        let t_p_dec_cross_p_q_weight = g.param("dec_cross.p.q.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
        let t_p_dec_cross_p_k_weight = g.param("dec_cross.p.k.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
        let t_p_dec_cross_p_v_weight = g.param("dec_cross.p.v.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
        let t_p_dec_cross_p_o_weight = g.param("dec_cross.p.o.weight", rlx_ir::Shape::new(&[32, 32], rlx_ir::DType::F32));
        let t_p_n_0_weight = g.param("n.0.weight", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
        let t_p_n_0_bias = g.param("n.0.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
        let t_p_n_1_weight = g.param("n.1.weight", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
        let t_p_n_1_bias = g.param("n.1.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
        let t_p_n_2_weight = g.param("n.2.weight", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
        let t_p_n_2_bias = g.param("n.2.bias", rlx_ir::Shape::new(&[32], rlx_ir::DType::F32));
        // aten.layer_norm.default  (src[1, 5, 32], p_n_0_weight[32], p_n_0_bias[32]) -> [1, 5, 32] f32
        let t_layer_norm = t_src.layer_norm(&t_p_n_0_weight, &t_p_n_0_bias, 0.00001f32);
        // aten.layer_norm.default  (src[1, 5, 32], p_n_0_weight[32], p_n_0_bias[32]) -> [1, 5, 32] f32
        let t_layer_norm_1 = t_src.layer_norm(&t_p_n_0_weight, &t_p_n_0_bias, 0.00001f32);
        // aten.permute.default  (p_enc_p_q_weight[32, 32]) -> [32, 32] f32
        let t_permute = t_p_enc_p_q_weight.transpose(vec![1usize, 0usize]);
        // aten.view.default  (layer_norm[1, 5, 32]) -> [5, 32] f32
        let t_view = t_layer_norm.reshape(vec![5i64, 32i64]);
        // aten.mm.default  (view[5, 32], permute[32, 32]) -> [5, 32] f32
        let t_mm = t_view.mm(&t_permute);
        // aten.view.default  (mm[5, 32]) -> [1, 5, 32] f32
        let t_view_1 = t_mm.reshape(vec![1i64, 5i64, 32i64]);
        // aten.view.default  (view_1[1, 5, 32]) -> [1, 5, 4, 8] f32
        let t_view_2 = t_view_1.reshape(vec![1i64, 5i64, 4i64, 8i64]);
        // aten.permute.default  (view_2[1, 5, 4, 8]) -> [1, 4, 5, 8] f32
        let t_permute_1 = t_view_2.transpose(vec![0usize, 2usize, 1usize, 3usize]);
        // aten.permute.default  (p_enc_p_k_weight[32, 32]) -> [32, 32] f32
        let t_permute_2 = t_p_enc_p_k_weight.transpose(vec![1usize, 0usize]);
        // aten.view.default  (layer_norm_1[1, 5, 32]) -> [5, 32] f32
        let t_view_3 = t_layer_norm_1.reshape(vec![5i64, 32i64]);
        // aten.mm.default  (view_3[5, 32], permute_2[32, 32]) -> [5, 32] f32
        let t_mm_1 = t_view_3.mm(&t_permute_2);
        // aten.view.default  (mm_1[5, 32]) -> [1, 5, 32] f32
        let t_view_4 = t_mm_1.reshape(vec![1i64, 5i64, 32i64]);
        // aten.view.default  (view_4[1, 5, 32]) -> [1, 5, 4, 8] f32
        let t_view_5 = t_view_4.reshape(vec![1i64, 5i64, 4i64, 8i64]);
        // aten.permute.default  (view_5[1, 5, 4, 8]) -> [1, 4, 5, 8] f32
        let t_permute_3 = t_view_5.transpose(vec![0usize, 2usize, 1usize, 3usize]);
        // aten.permute.default  (p_enc_p_v_weight[32, 32]) -> [32, 32] f32
        let t_permute_4 = t_p_enc_p_v_weight.transpose(vec![1usize, 0usize]);
        // aten.view.default  (layer_norm_1[1, 5, 32]) -> [5, 32] f32
        let t_view_6 = t_layer_norm_1.reshape(vec![5i64, 32i64]);
        // aten.mm.default  (view_6[5, 32], permute_4[32, 32]) -> [5, 32] f32
        let t_mm_2 = t_view_6.mm(&t_permute_4);
        // aten.view.default  (mm_2[5, 32]) -> [1, 5, 32] f32
        let t_view_7 = t_mm_2.reshape(vec![1i64, 5i64, 32i64]);
        // aten.view.default  (view_7[1, 5, 32]) -> [1, 5, 4, 8] f32
        let t_view_8 = t_view_7.reshape(vec![1i64, 5i64, 4i64, 8i64]);
        // aten.permute.default  (view_8[1, 5, 4, 8]) -> [1, 4, 5, 8] f32
        let t_permute_5 = t_view_8.transpose(vec![0usize, 2usize, 1usize, 3usize]);
        // aten.scaled_dot_product_attention.default  (permute_1[1, 4, 5, 8], permute_3[1, 4, 5, 8], permute_5[1, 4, 5, 8]) -> [1, 4, 5, 8] f32
        let t_scaled_dot_product_attention = t_permute_1.attention(&t_permute_3, &t_permute_5, 4, 8, MaskKind::None);
        // aten.permute.default  (scaled_dot_product_attention[1, 4, 5, 8]) -> [1, 5, 4, 8] f32
        let t_permute_6 = t_scaled_dot_product_attention.transpose(vec![0usize, 2usize, 1usize, 3usize]);
        // aten.view.default  (permute_6[1, 5, 4, 8]) -> [1, 5, 32] f32
        let t_view_9 = t_permute_6.reshape(vec![1i64, 5i64, 32i64]);
        // aten.permute.default  (p_enc_p_o_weight[32, 32]) -> [32, 32] f32
        let t_permute_7 = t_p_enc_p_o_weight.transpose(vec![1usize, 0usize]);
        // aten.view.default  (view_9[1, 5, 32]) -> [5, 32] f32
        let t_view_10 = t_view_9.reshape(vec![5i64, 32i64]);
        // aten.mm.default  (view_10[5, 32], permute_7[32, 32]) -> [5, 32] f32
        let t_mm_3 = t_view_10.mm(&t_permute_7);
        // aten.view.default  (mm_3[5, 32]) -> [1, 5, 32] f32
        let t_view_11 = t_mm_3.reshape(vec![1i64, 5i64, 32i64]);
        // aten.add.Tensor  (src[1, 5, 32], view_11[1, 5, 32]) -> [1, 5, 32] f32
        let t_add = (&t_src + &t_view_11);
        // aten.layer_norm.default  (tgt[1, 3, 32], p_n_1_weight[32], p_n_1_bias[32]) -> [1, 3, 32] f32
        let t_layer_norm_2 = t_tgt.layer_norm(&t_p_n_1_weight, &t_p_n_1_bias, 0.00001f32);
        // aten.layer_norm.default  (tgt[1, 3, 32], p_n_1_weight[32], p_n_1_bias[32]) -> [1, 3, 32] f32
        let t_layer_norm_3 = t_tgt.layer_norm(&t_p_n_1_weight, &t_p_n_1_bias, 0.00001f32);
        // aten.permute.default  (p_dec_self_p_q_weight[32, 32]) -> [32, 32] f32
        let t_permute_8 = t_p_dec_self_p_q_weight.transpose(vec![1usize, 0usize]);
        // aten.view.default  (layer_norm_2[1, 3, 32]) -> [3, 32] f32
        let t_view_12 = t_layer_norm_2.reshape(vec![3i64, 32i64]);
        // aten.mm.default  (view_12[3, 32], permute_8[32, 32]) -> [3, 32] f32
        let t_mm_4 = t_view_12.mm(&t_permute_8);
        // aten.view.default  (mm_4[3, 32]) -> [1, 3, 32] f32
        let t_view_13 = t_mm_4.reshape(vec![1i64, 3i64, 32i64]);
        // aten.view.default  (view_13[1, 3, 32]) -> [1, 3, 4, 8] f32
        let t_view_14 = t_view_13.reshape(vec![1i64, 3i64, 4i64, 8i64]);
        // aten.permute.default  (view_14[1, 3, 4, 8]) -> [1, 4, 3, 8] f32
        let t_permute_9 = t_view_14.transpose(vec![0usize, 2usize, 1usize, 3usize]);
        // aten.permute.default  (p_dec_self_p_k_weight[32, 32]) -> [32, 32] f32
        let t_permute_10 = t_p_dec_self_p_k_weight.transpose(vec![1usize, 0usize]);
        // aten.view.default  (layer_norm_3[1, 3, 32]) -> [3, 32] f32
        let t_view_15 = t_layer_norm_3.reshape(vec![3i64, 32i64]);
        // aten.mm.default  (view_15[3, 32], permute_10[32, 32]) -> [3, 32] f32
        let t_mm_5 = t_view_15.mm(&t_permute_10);
        // aten.view.default  (mm_5[3, 32]) -> [1, 3, 32] f32
        let t_view_16 = t_mm_5.reshape(vec![1i64, 3i64, 32i64]);
        // aten.view.default  (view_16[1, 3, 32]) -> [1, 3, 4, 8] f32
        let t_view_17 = t_view_16.reshape(vec![1i64, 3i64, 4i64, 8i64]);
        // aten.permute.default  (view_17[1, 3, 4, 8]) -> [1, 4, 3, 8] f32
        let t_permute_11 = t_view_17.transpose(vec![0usize, 2usize, 1usize, 3usize]);
        // aten.permute.default  (p_dec_self_p_v_weight[32, 32]) -> [32, 32] f32
        let t_permute_12 = t_p_dec_self_p_v_weight.transpose(vec![1usize, 0usize]);
        // aten.view.default  (layer_norm_3[1, 3, 32]) -> [3, 32] f32
        let t_view_18 = t_layer_norm_3.reshape(vec![3i64, 32i64]);
        // aten.mm.default  (view_18[3, 32], permute_12[32, 32]) -> [3, 32] f32
        let t_mm_6 = t_view_18.mm(&t_permute_12);
        // aten.view.default  (mm_6[3, 32]) -> [1, 3, 32] f32
        let t_view_19 = t_mm_6.reshape(vec![1i64, 3i64, 32i64]);
        // aten.view.default  (view_19[1, 3, 32]) -> [1, 3, 4, 8] f32
        let t_view_20 = t_view_19.reshape(vec![1i64, 3i64, 4i64, 8i64]);
        // aten.permute.default  (view_20[1, 3, 4, 8]) -> [1, 4, 3, 8] f32
        let t_permute_13 = t_view_20.transpose(vec![0usize, 2usize, 1usize, 3usize]);
        // aten.scaled_dot_product_attention.default  (permute_9[1, 4, 3, 8], permute_11[1, 4, 3, 8], permute_13[1, 4, 3, 8]) -> [1, 4, 3, 8] f32
        let t_scaled_dot_product_attention_1 = t_permute_9.attention(&t_permute_11, &t_permute_13, 4, 8, MaskKind::None);
        // aten.permute.default  (scaled_dot_product_attention_1[1, 4, 3, 8]) -> [1, 3, 4, 8] f32
        let t_permute_14 = t_scaled_dot_product_attention_1.transpose(vec![0usize, 2usize, 1usize, 3usize]);
        // aten.view.default  (permute_14[1, 3, 4, 8]) -> [1, 3, 32] f32
        let t_view_21 = t_permute_14.reshape(vec![1i64, 3i64, 32i64]);
        // aten.permute.default  (p_dec_self_p_o_weight[32, 32]) -> [32, 32] f32
        let t_permute_15 = t_p_dec_self_p_o_weight.transpose(vec![1usize, 0usize]);
        // aten.view.default  (view_21[1, 3, 32]) -> [3, 32] f32
        let t_view_22 = t_view_21.reshape(vec![3i64, 32i64]);
        // aten.mm.default  (view_22[3, 32], permute_15[32, 32]) -> [3, 32] f32
        let t_mm_7 = t_view_22.mm(&t_permute_15);
        // aten.view.default  (mm_7[3, 32]) -> [1, 3, 32] f32
        let t_view_23 = t_mm_7.reshape(vec![1i64, 3i64, 32i64]);
        // aten.add.Tensor  (tgt[1, 3, 32], view_23[1, 3, 32]) -> [1, 3, 32] f32
        let t_add_1 = (&t_tgt + &t_view_23);
        // aten.layer_norm.default  (add_1[1, 3, 32], p_n_2_weight[32], p_n_2_bias[32]) -> [1, 3, 32] f32
        let t_layer_norm_4 = t_add_1.layer_norm(&t_p_n_2_weight, &t_p_n_2_bias, 0.00001f32);
        // aten.permute.default  (p_dec_cross_p_q_weight[32, 32]) -> [32, 32] f32
        let t_permute_16 = t_p_dec_cross_p_q_weight.transpose(vec![1usize, 0usize]);
        // aten.view.default  (layer_norm_4[1, 3, 32]) -> [3, 32] f32
        let t_view_24 = t_layer_norm_4.reshape(vec![3i64, 32i64]);
        // aten.mm.default  (view_24[3, 32], permute_16[32, 32]) -> [3, 32] f32
        let t_mm_8 = t_view_24.mm(&t_permute_16);
        // aten.view.default  (mm_8[3, 32]) -> [1, 3, 32] f32
        let t_view_25 = t_mm_8.reshape(vec![1i64, 3i64, 32i64]);
        // aten.view.default  (view_25[1, 3, 32]) -> [1, 3, 4, 8] f32
        let t_view_26 = t_view_25.reshape(vec![1i64, 3i64, 4i64, 8i64]);
        // aten.permute.default  (view_26[1, 3, 4, 8]) -> [1, 4, 3, 8] f32
        let t_permute_17 = t_view_26.transpose(vec![0usize, 2usize, 1usize, 3usize]);
        // aten.permute.default  (p_dec_cross_p_k_weight[32, 32]) -> [32, 32] f32
        let t_permute_18 = t_p_dec_cross_p_k_weight.transpose(vec![1usize, 0usize]);
        // aten.view.default  (add[1, 5, 32]) -> [5, 32] f32
        let t_view_27 = t_add.reshape(vec![5i64, 32i64]);
        // aten.mm.default  (view_27[5, 32], permute_18[32, 32]) -> [5, 32] f32
        let t_mm_9 = t_view_27.mm(&t_permute_18);
        // aten.view.default  (mm_9[5, 32]) -> [1, 5, 32] f32
        let t_view_28 = t_mm_9.reshape(vec![1i64, 5i64, 32i64]);
        // aten.view.default  (view_28[1, 5, 32]) -> [1, 5, 4, 8] f32
        let t_view_29 = t_view_28.reshape(vec![1i64, 5i64, 4i64, 8i64]);
        // aten.permute.default  (view_29[1, 5, 4, 8]) -> [1, 4, 5, 8] f32
        let t_permute_19 = t_view_29.transpose(vec![0usize, 2usize, 1usize, 3usize]);
        // aten.permute.default  (p_dec_cross_p_v_weight[32, 32]) -> [32, 32] f32
        let t_permute_20 = t_p_dec_cross_p_v_weight.transpose(vec![1usize, 0usize]);
        // aten.view.default  (add[1, 5, 32]) -> [5, 32] f32
        let t_view_30 = t_add.reshape(vec![5i64, 32i64]);
        // aten.mm.default  (view_30[5, 32], permute_20[32, 32]) -> [5, 32] f32
        let t_mm_10 = t_view_30.mm(&t_permute_20);
        // aten.view.default  (mm_10[5, 32]) -> [1, 5, 32] f32
        let t_view_31 = t_mm_10.reshape(vec![1i64, 5i64, 32i64]);
        // aten.view.default  (view_31[1, 5, 32]) -> [1, 5, 4, 8] f32
        let t_view_32 = t_view_31.reshape(vec![1i64, 5i64, 4i64, 8i64]);
        // aten.permute.default  (view_32[1, 5, 4, 8]) -> [1, 4, 5, 8] f32
        let t_permute_21 = t_view_32.transpose(vec![0usize, 2usize, 1usize, 3usize]);
        // aten.scaled_dot_product_attention.default  (permute_17[1, 4, 3, 8], permute_19[1, 4, 5, 8], permute_21[1, 4, 5, 8]) -> [1, 4, 3, 8] f32
        let t_scaled_dot_product_attention_2 = t_permute_17.attention(&t_permute_19, &t_permute_21, 4, 8, MaskKind::None);
        // aten.permute.default  (scaled_dot_product_attention_2[1, 4, 3, 8]) -> [1, 3, 4, 8] f32
        let t_permute_22 = t_scaled_dot_product_attention_2.transpose(vec![0usize, 2usize, 1usize, 3usize]);
        // aten.view.default  (permute_22[1, 3, 4, 8]) -> [1, 3, 32] f32
        let t_view_33 = t_permute_22.reshape(vec![1i64, 3i64, 32i64]);
        // aten.permute.default  (p_dec_cross_p_o_weight[32, 32]) -> [32, 32] f32
        let t_permute_23 = t_p_dec_cross_p_o_weight.transpose(vec![1usize, 0usize]);
        // aten.view.default  (view_33[1, 3, 32]) -> [3, 32] f32
        let t_view_34 = t_view_33.reshape(vec![3i64, 32i64]);
        // aten.mm.default  (view_34[3, 32], permute_23[32, 32]) -> [3, 32] f32
        let t_mm_11 = t_view_34.mm(&t_permute_23);
        // aten.view.default  (mm_11[3, 32]) -> [1, 3, 32] f32
        let t_view_35 = t_mm_11.reshape(vec![1i64, 3i64, 32i64]);
        // aten.add.Tensor  (add_1[1, 3, 32], view_35[1, 3, 32]) -> [1, 3, 32] f32
        let t_add_2 = (&t_add_1 + &t_view_35);
        t_add_2
    })
}
