// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
// SPDX-License-Identifier: MIT OR Apache-2.0

//! A chaining DSL over the same graph builder.
//!
//! Threading integer node ids reads inside-out — the first operation applied is
//! the innermost token, so a transformer block becomes a paragraph of nested
//! calls you have to unwrap backwards:
//!
//! ```js
//! g.setOutputs([g.add(x, g.matmul(g.silu(g.matmul(g.rmsNorm(x, w, b, 1e-6), wg)), wd))]);
//! ```
//!
//! `rlx.dsl` returns the same `Graph` (so `Session.compile` takes it unchanged)
//! but with `input` / `param` / `constant` handing back a `Tensor`, which reads
//! in the order the data flows:
//!
//! ```js
//! const m = rlx.dsl("block");
//! const x = m.input("x", [1, 8, 256]);
//! const h = x.rmsNorm(m.param("nw", [256]), m.param("nb", [256]), 1e-6);
//! m.output(x.add(h.matmul(m.param("wg", [256, 512])).silu()
//!                 .matmul(m.param("wd", [512, 256]))));
//! ```
//!
//! # No second op table
//!
//! `Tensor`'s methods are generated by **enumerating `Graph.prototype` at
//! install time**, not from a list kept here. Every op the graph gains — now or
//! later — is chainable the moment it is registered, and there is no list to
//! drift out of date. Each forwarder is one shared `NativeFn` that reads its
//! target's name back out of a slot on itself.

use quickrs_core::context::Context;
use quickrs_core::gc::Gc;
use quickrs_core::object::{ClassId, JsObject, ObjectData, PropFlags};
use quickrs_core::value::{JsResult, PropKey, Value};
use rlx_ir::infer::GraphExt;
use rlx_ir::{Graph, NodeId};

use crate::api::graph::{graph_of, parse_dtype, wrap_graph};
use crate::convert::*;
use crate::handle::{self, CLASS_GRAPH, CLASS_TENSOR};

/// A node id plus, in the host object's traced `data`, the graph it belongs to.
pub struct TensorSlot {
    pub id: u32,
}

/// Graph methods that do **not** take a node first, so there is nothing to
/// chain them onto. `input`/`param`/`constant` are sources; `zeros`/`full`/
/// `fftfreq` are constants; `concat`/`customFn` take a list; `shapeOf` is what
/// `.dims` and `.dtype` are built from.
const NOT_CHAINABLE: &[&str] = &[
    "input",
    "param",
    "constant",
    "setOutputs",
    "outputs",
    "nodeCount",
    "name",
    "toString",
    "toJSON",
    "shapeOf",
    "paramNames",
    "opKinds",
    "zeros",
    "full",
    "fftfreq",
    "rfftfreq",
    "concat",
    "customFn",
    "__class",
];

/// Graph methods that take a *string* selector first and the node second, so
/// the receiver is spliced in at index 1 rather than 0.
const SELECTOR_FIRST: &[&str] = &["binary", "compare", "activation"];

/// Ops whose every operand is a tensor, so a plain JS number in an argument
/// slot means "a constant of that value" — `x.mul(0.5)`, `x.add(bias)`.
///
/// Only these: elsewhere a number is a real scalar (`narrow(1, 0, 2)` is an
/// axis and two offsets), and lifting it would build garbage. Before this, a
/// number here was read as a *node id*, so `x.add(2)` silently referred to
/// whatever node 2 happened to be — or panicked when there wasn't one.
const ALL_OPERANDS_ARE_TENSORS: &[&str] = &["add", "sub", "mul", "div", "where"];

fn tensor_of<'a>(ctx: &mut Context, this: &Value) -> JsResult<&'a mut TensorSlot> {
    handle::borrow_mut(ctx, this, CLASS_TENSOR, "rlx.Tensor")
}

/// The graph a tensor belongs to, kept in the host object's traced data.
fn owner(ctx: &mut Context, this: &Value) -> JsResult<Value> {
    match handle::host_data(this, CLASS_TENSOR).and_then(|d| d.into_iter().next()) {
        Some(graph) => Ok(graph),
        None => ctx.throw_type("rlx.Tensor: lost its graph"),
    }
}

/// Lift a node id into a `Tensor` bound to `graph`.
pub fn new_tensor(ctx: &mut Context, graph: &Value, id: NodeId) -> Value {
    handle::wrap_with(
        ctx,
        CLASS_TENSOR,
        vec![graph.clone()],
        TensorSlot { id: id.0 },
    )
}

/// A `Tensor` argument reads as its node id; anything else passes through, so
/// `t.narrow(0, 0, 4)` and `t.add(other)` both work.
fn unwrap_arg(v: &Value) -> Value {
    match handle::host_data(v, CLASS_TENSOR) {
        Some(_) => {
            // Re-read the id without a Context: the slot is plain data.
            let Some(obj) = v.as_object() else {
                return v.clone();
            };
            let borrowed = obj.borrow();
            if let ObjectData::Host(host) = &borrowed.data {
                if host.class_id == CLASS_TENSOR && host.opaque != 0 {
                    // SAFETY: the word came from `Box::into_raw::<TensorSlot>`
                    // under this class id and the object is alive for the call.
                    let slot = unsafe { &*(host.opaque as *const TensorSlot) };
                    return Value::number(slot.id as f64);
                }
            }
            v.clone()
        }
        None => v.clone(),
    }
}

/// Wrap a graph method's result: a node id becomes a `Tensor`, a pair of ids
/// becomes an array of them, anything else passes through untouched.
fn wrap_result(ctx: &mut Context, graph: &Value, result: Value) -> JsResult<Value> {
    match &result {
        Value::Int(n) => Ok(new_tensor(ctx, graph, NodeId(*n as u32))),
        Value::Float(x) => Ok(new_tensor(ctx, graph, NodeId(*x as u32))),
        Value::Object(_) if Context::typed_array_type(&result).is_none() => {
            // The two-output ops (`rfft`, `eigh`, …) return a plain array.
            let is_array = ctx.length_of(&result).is_ok()
                && matches!(&result, Value::Object(o) if o.borrow().array().is_some());
            if !is_array {
                return Ok(result);
            }
            let n = ctx.length_of(&result)? as usize;
            let mut items = Vec::with_capacity(n);
            for i in 0..n {
                let element = ctx.get_property(&result, &PropKey::Index(i as u32))?;
                items.push(match element {
                    Value::Int(v) => new_tensor(ctx, graph, NodeId(v as u32)),
                    Value::Float(x) => new_tensor(ctx, graph, NodeId(x as u32)),
                    other => other,
                });
            }
            Ok(new_array(ctx, items))
        }
        _ => Ok(result),
    }
}

/// Is this a bare JS number (so a candidate for lifting to a constant)?
fn is_plain_number(v: &Value) -> bool {
    matches!(v, Value::Int(_) | Value::Float(_))
}

/// Lift `value` into a `Constant` node typed like the receiver, so
/// `x.mul(2)` follows `x`'s dtype rather than forcing f32 into an f64 graph.
fn lift_scalar(ctx: &mut Context, graph: &Value, receiver: NodeId, value: f64) -> JsResult<Value> {
    let dtype = {
        let g: &mut Graph = graph_of(ctx, graph)?;
        g.shape(receiver).dtype()
    };
    let id = {
        let g: &mut Graph = graph_of(ctx, graph)?;
        match g.try_constant(value, dtype) {
            Ok(id) => id,
            Err(e) => {
                let message = e.to_string();
                return ctx.throw_range(&message);
            }
        }
    };
    Ok(Value::number(id.0 as f64))
}

/// The one forwarder behind every chained method.
///
/// Reads its target name and the receiver's argument position from slots on
/// itself, so a single `NativeFn` serves the whole prototype.
fn forward(ctx: &mut Context, this: &Value, args: &[Value], _m: i32) -> JsResult<Value> {
    let target = ctx.callee_slot("__target")?;
    let name = ctx.to_rust_string(&target)?;
    let self_at = match ctx.callee_slot("__selfAt")? {
        Value::Int(n) => n as usize,
        _ => 0,
    };
    // -1 means "no argument in this op is a tensor operand".
    let lift_from = match ctx.callee_slot("__liftFrom")? {
        Value::Int(n) => n,
        _ => -1,
    };

    let graph = owner(ctx, this)?;
    let receiver = NodeId(tensor_of(ctx, this)?.id);
    let id = Value::number(receiver.0 as f64);

    let mut call_args: Vec<Value> = Vec::with_capacity(args.len() + 1);
    for (i, a) in args.iter().enumerate() {
        if i == self_at {
            call_args.push(id.clone());
        }
        let lift = lift_from >= 0 && i as i32 >= lift_from && is_plain_number(a);
        let mapped = if lift {
            let value = ctx.to_number(a)?;
            lift_scalar(ctx, &graph, receiver, value)?
        } else {
            unwrap_arg(a)
        };
        call_args.push(mapped);
    }
    if call_args.len() <= self_at {
        call_args.push(id);
    }

    let key = PropKey::from_string(&ctx.intern(&name));
    let method = ctx.get_property(&graph, &key)?;
    let result = ctx.call(method, graph.clone(), &call_args)?;
    wrap_result(ctx, &graph, result)
}

/// `a.concat([b, c], axis)` — bespoke because `Graph.concat` takes the list
/// first, so the generic "splice the receiver in" rule would build
/// `concat(a, [b, c], axis)`.
fn t_concat(ctx: &mut Context, this: &Value, args: &[Value], _m: i32) -> JsResult<Value> {
    let graph = owner(ctx, this)?;
    let first = NodeId(tensor_of(ctx, this)?.id);

    let rest = arg(args, 0).clone();
    let mut ids: Vec<Value> = vec![Value::number(first.0 as f64)];
    // A single tensor is the same call as a one-element list.
    if handle::host_data(&rest, CLASS_TENSOR).is_some() || is_plain_number(&rest) {
        ids.push(unwrap_arg(&rest));
    } else if !is_nullish(&rest) {
        let n = ctx.length_of(&rest)? as usize;
        for i in 0..n {
            let element = ctx.get_property(&rest, &PropKey::Index(i as u32))?;
            ids.push(unwrap_arg(&element));
        }
    }
    let axis = if is_nullish(arg(args, 1)) {
        Value::number(0.0)
    } else {
        arg(args, 1).clone()
    };

    let list = new_array(ctx, ids);
    let key = PropKey::from_string(&ctx.intern("concat"));
    let method = ctx.get_property(&graph, &key)?;
    let result = ctx.call(method, graph.clone(), &[list, axis])?;
    wrap_result(ctx, &graph, result)
}

// ── Tensor accessors ────────────────────────────────────────

fn t_id(ctx: &mut Context, this: &Value, _args: &[Value], _m: i32) -> JsResult<Value> {
    Ok(Value::number(tensor_of(ctx, this)?.id as f64))
}

/// `t.dims` / `t.dtype` — read straight off the graph, so they reflect the
/// shape inference that actually happened rather than what the caller assumed.
fn t_shape_field(ctx: &mut Context, this: &Value, _args: &[Value], magic: i32) -> JsResult<Value> {
    let id = tensor_of(ctx, this)?.id;
    let graph = owner(ctx, this)?;
    let (dims, dtype) = {
        let g: &mut Graph = graph_of(ctx, &graph)?;
        let shape = g.shape(NodeId(id));
        let dims: Vec<Value> = shape
            .dims()
            .iter()
            .map(|d| match d {
                rlx_ir::Dim::Static(n) => Value::number(*n as f64),
                rlx_ir::Dim::Dynamic(_) => Value::number(-1.0),
            })
            .collect();
        (dims, crate::api::graph::dtype_label(shape.dtype()))
    };
    if magic == 0 {
        Ok(new_array(ctx, dims))
    } else {
        Ok(new_string(ctx, dtype))
    }
}

fn t_to_string(ctx: &mut Context, this: &Value, _args: &[Value], _m: i32) -> JsResult<Value> {
    let id = tensor_of(ctx, this)?.id;
    let graph = owner(ctx, this)?;
    let text = {
        let g: &mut Graph = graph_of(ctx, &graph)?;
        let shape = g.shape(NodeId(id));
        let dims: Vec<String> = shape
            .dims()
            .iter()
            .map(|d| match d {
                rlx_ir::Dim::Static(n) => n.to_string(),
                rlx_ir::Dim::Dynamic(binding) => format!("?{binding}"),
            })
            .collect();
        format!(
            "Tensor(%{id} [{}] {})",
            dims.join(", "),
            crate::api::graph::dtype_label(shape.dtype())
        )
    };
    Ok(new_string(ctx, &text))
}

// ── DSL graph overrides ─────────────────────────────────────

/// `m.input(name, dims, dtype?)` → `Tensor`. `dtype` defaults to `"f32"`,
/// which is the only thing a DSL caller writes 95% of the time.
fn d_input(ctx: &mut Context, this: &Value, args: &[Value], magic: i32) -> JsResult<Value> {
    let name = ctx.to_rust_string(arg(args, 0))?;
    let dims = to_usize_vec(ctx, arg(args, 1), "shape")?;
    let label = to_string_or(ctx, arg(args, 2), "f32")?;
    let dtype = parse_dtype(ctx, &label)?;
    let shape = rlx_ir::Shape::new(&dims, dtype);
    let id = {
        let g: &mut Graph = graph_of(ctx, this)?;
        if magic == 0 {
            g.input(name, shape)
        } else {
            g.param(name, shape)
        }
    };
    Ok(new_tensor(ctx, this, id))
}

fn d_constant(ctx: &mut Context, this: &Value, args: &[Value], _m: i32) -> JsResult<Value> {
    let value = to_f64(ctx, arg(args, 0))?;
    let label = to_string_or(ctx, arg(args, 1), "f32")?;
    let dtype = parse_dtype(ctx, &label)?;
    let id = {
        let g: &mut Graph = graph_of(ctx, this)?;
        match g.try_constant(value, dtype) {
            Ok(id) => id,
            Err(e) => {
                let message = e.to_string();
                return ctx.throw_range(&message);
            }
        }
    };
    Ok(new_tensor(ctx, this, id))
}

/// `m.lift(id)` — bring a raw node id from the imperative API into the chain.
fn d_lift(ctx: &mut Context, this: &Value, args: &[Value], _m: i32) -> JsResult<Value> {
    let raw = unwrap_arg(arg(args, 0));
    let id = to_usize(ctx, &raw, "lift")? as u32;
    Ok(new_tensor(ctx, this, NodeId(id)))
}

/// `m.output(t)` / `m.output(a, b)` — takes `Tensor`s (or ids, or one array).
fn d_output(ctx: &mut Context, this: &Value, args: &[Value], _m: i32) -> JsResult<Value> {
    let mut ids: Vec<NodeId> = Vec::with_capacity(args.len());
    // A single *array* argument is the same call spelled the other way. A bare
    // number is not array-like, and treating it as one silently produced a
    // graph with zero outputs.
    let single_array = args.len() == 1
        && matches!(args[0], Value::Object(_))
        && handle::host_data(&args[0], CLASS_TENSOR).is_none();
    let flat: Vec<Value> = if single_array {
        match ctx.length_of(&args[0]) {
            Ok(n) => {
                let mut items = Vec::with_capacity(n as usize);
                for i in 0..n as usize {
                    items.push(ctx.get_property(&args[0], &PropKey::Index(i as u32))?);
                }
                items
            }
            Err(_) => vec![args[0].clone()],
        }
    } else {
        args.to_vec()
    };
    for v in &flat {
        let raw = unwrap_arg(v);
        ids.push(NodeId(to_usize(ctx, &raw, "output")? as u32));
    }
    graph_of(ctx, this)?.set_outputs(ids);
    Ok(Value::Undefined)
}

// ── installation ────────────────────────────────────────────

/// `rlx.dsl(name)` — a graph whose sources return chainable `Tensor`s.
fn f_dsl(ctx: &mut Context, _this: &Value, args: &[Value], _m: i32) -> JsResult<Value> {
    let name = to_string_or(ctx, arg(args, 0), "graph")?;
    let graph = wrap_graph(ctx, Graph::new(name));
    // Same class tag, so `Session.compile` accepts it; only the prototype
    // differs, and it inherits every imperative method.
    if let (Some(obj), Some(proto)) = (graph.as_object(), dsl_prototype(ctx)) {
        obj.borrow_mut().set_proto(Some(proto));
    }
    Ok(graph)
}

const DSL_PROTO_SLOT: &str = "__rlx_dsl_proto";

fn dsl_prototype(ctx: &mut Context) -> Option<Gc<JsObject>> {
    let key = PropKey::from_string(&ctx.intern(DSL_PROTO_SLOT));
    let global = Value::Object(ctx.global());
    ctx.get_property(&global, &key)
        .ok()
        .and_then(|v| v.as_object().cloned())
}

pub fn install(ctx: &mut Context, namespace: &Gc<JsObject>) {
    // ── Tensor.prototype, generated from Graph.prototype ──
    let tensor_proto = js_class! {
        ctx, namespace;
        name: "Tensor",
        class: CLASS_TENSOR,
        methods: { "toString" => t_to_string, 0; }
    };
    let graph_proto = handle::prototype_of(ctx, CLASS_GRAPH)
        .expect("api::graph::install runs before api::dsl::install");

    let keys = ctx
        .own_property_keys(&graph_proto)
        .unwrap_or_default()
        .into_iter()
        .filter_map(|k| match k {
            PropKey::Str(s) => Some(s.to_string_lossy()),
            _ => None,
        })
        .collect::<Vec<_>>();

    for name in keys {
        if NOT_CHAINABLE.contains(&name.as_str()) {
            continue;
        }
        // One shared body; the name and the receiver's slot live on the
        // function object, so adding an op to the graph adds it here too.
        let f = ctx.new_native_function(forward, &name, 1, 0);
        let target = Value::Str(ctx.intern(&name));
        ctx.set_slot(&f, "__target", target);
        let selector_first = SELECTOR_FIRST.contains(&name.as_str());
        let self_at = if selector_first { 1 } else { 0 };
        ctx.set_slot(&f, "__selfAt", Value::Int(self_at));
        // `binary`/`compare` take their operands after the selector, so lifting
        // starts one slot later than for `add`/`mul`/`where`.
        let lift_from = if ALL_OPERANDS_ARE_TENSORS.contains(&name.as_str()) {
            0
        } else if selector_first && name != "activation" {
            1
        } else {
            -1
        };
        ctx.set_slot(&f, "__liftFrom", Value::Int(lift_from));
        let key = PropKey::from_string(&ctx.intern(&name));
        ctx.define_own(
            &tensor_proto,
            key,
            quickrs_core::object::Property::data(Value::Object(f), PropFlags::C_W),
        );
    }

    ctx.define_method(&tensor_proto, "concat", t_concat, 2, 0);
    ctx.define_accessor(&tensor_proto, "id", Some(t_id), None);
    // Accessors rather than methods: `t.dims` reads like a property because it
    // is one — the graph already knows the answer.
    let dims = ctx.new_native_function(t_shape_field, "get dims", 0, 0);
    let dtype = ctx.new_native_function(t_shape_field, "get dtype", 0, 1);
    for (name, getter) in [("dims", dims), ("dtype", dtype)] {
        let key = PropKey::from_string(&ctx.intern(name));
        ctx.define_own(
            &tensor_proto,
            key,
            quickrs_core::object::Property::accessor(
                Some(Value::Object(getter)),
                None,
                PropFlags::CONFIGURABLE,
            ),
        );
    }

    // ── the DSL graph prototype, inheriting the imperative one ──
    let dsl_proto = ctx.new_object_with(ClassId::Object, Some(graph_proto), ObjectData::None);
    ctx.define_method(&dsl_proto, "input", d_input, 3, 0);
    ctx.define_method(&dsl_proto, "param", d_input, 3, 1);
    ctx.define_method(&dsl_proto, "constant", d_constant, 2, 0);
    ctx.define_method(&dsl_proto, "lift", d_lift, 1, 0);
    ctx.define_method(&dsl_proto, "output", d_output, 1, 0);
    ctx.define_method(&dsl_proto, "outputs", d_output, 1, 0);

    let global = ctx.global();
    ctx.define_value(
        &global,
        DSL_PROTO_SLOT,
        Value::Object(dsl_proto),
        PropFlags::NONE,
    );
    ctx.define_method(namespace, "dsl", f_dsl, 1, 0);
}
